### ISSUE TITLE
🆕 Software Suggestion | Slackware / FreeNix / Other 

### ISSUE THREAD

**Issue by asddsaz** [privacytoolsIO/privacytools.io#1011]
## Basic Information

**Name:** Slackware
**Category:** OS
**URL:** https://www.wikipedia.org/wiki/Slackware
**Description**: Slackware aims for design stability and simplicity and to be the most "Unix-like" Linux distribution. (Source: Wikipedia)

**Name:** Freenix
**Category:** OS
**URL:** https://www.wikipedia.org/wiki/Freenix
**Description**: Freenix is a GNU+Linux-libre distribution, and a Free eXpansion Pack for Slackware. (Source: Freenix.net)

## Description

Discuss the possibilities of list Slackware and forks like Freenix.
Similar to how Parabola is listed as free'd version of Arch.

**Comment by Mikaela** [comment]
Could you add more reasons why it should be listed, when it has been last updated etc.? 

Ref: https://github.com/privacytoolsIO/privacytools.io/issues/977

**Comment by Atavic** [comment]
Slackware is one of the oldest distributions in existence. Very stable.

**Comment by jkhgvfgvsth** [comment]
@Mikaela Slackware is "the oldest surviving Linux distribution"[1](https://distrowatch.com/dwres.php?resource=major) and highly stable. 

In case you need OS reviews:
https://www.linuxquestions.org/reviews/showcat.php/cat/6

**Comment by blacklight447-ptio** [comment]
I dont really see an reason to add slackware. we already have a a bunch of recommendations which are privacy friendly, adding more distros just because they are stable doesnt seem like a smart idea. every distro added is another distro that can turn out to be bad news privacy wise. @JonahAragon @Mikaela @nitrohorse  thoughts? I recommend closure.

**Comment by Mikaela** [comment]
I have never used Slackware so I don't have personal experience with it and I don't feel like starting to research it.

When I hear of it, I start thinking of when netbooks came to stores and originally had Slackware instead of Windows on them and I have heard that they failed due to using Slackware which is said to not be as beginner friendly as Ubuntu.

I agree with closure.

**Comment by dawidpotocki** [comment]
Slackware is KISS distribution, which means "Keep It Simple Stupid", so it does not come with "smart overcomplicated" software like systemd. It comes also with some rather old package versions, like KDE 4. While it is great distro, you probably will know yourself if you want to use it. I don't think we should list Slackware just because someone likes it, just like I will not create an issue to list Void Linux, even though I use it and like it.

**Comment by blacklight447-ptio** [comment]
Right, closing issue.
