### ISSUE TITLE
🆕 Software Suggestion | Snowflake extension

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1039]
## Basic Information

**Name:** Snowflake
**Category:**  Excellent Firefox Privacy Add-ons
**URL:** https://snowflake.torproject.org/

## Description

> Snowflake is a system to defeat internet censorship. People who are censored can use Snowflake to access the internet. Their connection goes through Snowflake proxies, which are run by volunteers. For more detailed information about how Snowflake works see our documentation wiki.

Snowflake extension turns users into Snowflake proxies letting censored Tor users use them as a bridge to Tor network.

See also https://github.com/privacytoolsIO/privacytools.io/issues/295 https://trac.torproject.org/projects/tor/ticket/23888

**Comment by Mikaela** [comment]
Quoting a Matrix discussion:

> I guess it should be on a "please consider." And also to check if there's any possible way for the extention to be more harmful than not using it, in which case there should be a warning.

*I don't think there is much room for harm, snowflakes are more temporary than usual bridges and the usual bridges aren't publicly listed either*

> Well, fingerprinting, costing bandwidth, idk

I guess bandwidth cost may be a real issue, so this should probably be mentioned in case someone installed it on a phone.

* https://matrix.to/#/!tYmNuaXMRnHEZWdDqp:privacytools.io/$156364157721379ALURj:privacytools.io?via=privacytools.io&via=matrix.org&via=librem.one

**Comment by nitrohorse** [comment]
Quoting what I mentioned in Riot:
> I can see some confusion from users who follow [PTIO's guide to disable WebRTC](https://www.privacytools.io/browsers/#webrtc) and then see they'd need to revert these steps for the extension to work.

But I do like the idea of putting this extension in a new "Please Consider"-type of category under the "For Experts Only" section since its use is to help _others_ achieve privacy who potentially can't by other means. So in that regard it does seem to stand on its own.

**Comment by JonahAragon** [comment]
This is pretty sweet actually, I'm installing it now.

I don't think this needs to be in a separate category (unless there are many more similar tools that would fit in the category I suppose). We can just include this in "Firefox Privacy Add-ons", especially because that category in particular has long descriptions for each recommended items where we can explain essentially what's been said here: Snowflake doesn't provide privacy benefits to your own browser, rather it enables users with hostile ISPs to access the Tor network anonymously.

Not sure on the exact working, and maybe I'd include something about how it runs silently in the background and doesn't reveal your IP to websites because it isn't an exit node. I'd definitely approve a PR though.
