### ISSUE TITLE
🆕 Software Suggestion | BolehVPN

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1046]
> No logging policy at BolehVPN
> 
> BolehVPN.net is operating outside the USA and FVEY. They have a strict no logging policy too.
> 
> Also they accept btc, XMR, dash etc.
> 
> 
> Shouldn't they be considered being on the list on https://www.privacytools.io/providers/vpn/ too?

* https://www.reddit.com/r/privacytoolsIO/comments/ch4ilp/no_logging_policy_at_bolehvpn/

Blocked by https://github.com/privacytoolsIO/privacytools.io/issues/914 in my opinion.

## Basic Information

**Name:**
**Category:**
**URL:**

**Comment by Mikaela** [comment]
> https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fwww.bolehvpn.net
> 
> "We take your privacy really seriously, but our website connects to bunch of trackers, hopefully you don't mind it".

* https://www.reddit.com/r/privacytoolsIO/comments/ch4ilp/no_logging_policy_at_bolehvpn/eup49zg

**Comment by blacklight447-ptio** [comment]
IMO we should recommend less vpns, not more. What would this provider bring over the other providers? Also, how do we know that we can actually trust their privacy policies.

**Comment by blacklight447-ptio** [comment]
With some internal discussion, we wont be accepting new VPN s anymore till another one gets removed. This is because we already list enough off them, and we don't want to become a huge catelouge listing every vpn provider uner the sun with a good privacy policy. closing for now, with a possibility to be re opened again once we have more room in the VPN section.
