### ISSUE TITLE
🆕 Software Suggestion | Privacy Browser

### ISSUE THREAD

**Issue by GrimPixel** [privacytoolsIO/privacytools.io#1051]
## Basic Information

**Name:** Privacy Browser
**Category:** Web Browsers
**URL:** https://www.stoutner.com/privacy-browser/

## Description

This program started in 2016 and is active.

I think it can be introduced to more people, if it still needs improvements to be formally recommended.

**Comment by nitrohorse** [comment]
[Here’s a thread](https://old.reddit.com/r/privacytoolsIO/comments/7jhmtl/privacy_browser_for_android/) where the creator shared it on the subreddit a year ago.

Definitely think Privacy Browser is worth recommending on PTIO. I follow [Stoutner’s news updates for it](https://www.stoutner.com/category/privacy-browser/), and it’s awesome how far the app has come.

**Comment by beerisgood** [comment]
Problem with privacy browser is: usage of Android internal webview.

That means: if your Android isn't up2date, your browser isn't too.

+1 for Bromite

**Comment by nitrohorse** [comment]
Ah, that’s a good call out.

**Comment by nitrohorse** [comment]
I’m not sure if that’s really a significant problem though, is it? If one’s base OS is outdated (with open security vulnerabilities) then I wouldn’t expect security in any applications I run on top of it.

**Comment by beerisgood** [comment]
Well, most users don't get fast updates nor any at all.
Of course you can say that the whole OS/ device isn't secure then, but how stop using it just of that?

Also what is outdated? A system which got updates 1 day later then Google devices? 2 days?
In theory it is, but as i say: who stop using then the device until it's up2date?

Anyway it exist much better and more secure browser like Bromite

**Comment by Mikaela** [comment]
I think that Android is outdated by default unless you get a [Android One](https://android.com/one) phone within the three years support period and won't use it further.

On my Samsung Galaxy S3 with resurrection remix (that I am using for a few apps that are too heavy for my main Nokia 1), I was wondering why did so many sites tell me to update my browser as I didn't understand that the webview wasn't receiving updates. I looked into Bromite, but I remember that it was a bit too advanced for me or would have required installing a different custom ROM or something I wasn't comfortable doing, so I resolved the issue by just installing Android System Webview from Aurora Store thus googlifying my phone a bit more, but getting those security updates.

I am not sure if Privacy Browser should be listed due to this issue or if it should just have a warning label that it's using webview and either a suggestion to install Bromite from ? or Android System Webview from Aurora Store and mark it as the default webview in developer settings.

I guess an alternative would be installing Google Chrome, but I am a bit more comfortable with the webview from Google than full Chrome.

**Comment by beerisgood** [comment]
You can install bromite from (their own) F-Droid repository.
No config at browser required.

**Comment by Mikaela** [comment]
I looked into Bromite a bit more and it seems that I was just confused about [Installing SystemWebView in Bromite Wiki](https://github.com/bromite/bromite/wiki/Installing-SystemWebView) which clearly says:

> BEWARE: this is not an officially supported procedure, it may or may not work. Be prepared to restore original SystemWebView if something goes wrong.

**Comment by sorenstoutner** [comment]
I am the developer of Privacy Browser.  I can answer a few of the questions raised here.

1.  Beginning with Android Lollipop (5.0, API 21), WebView can be updated via an APK (either automatically through the Play store or via an app like Yalp). So, for example, my Nexus 4 running 5.1.1 currently has WebView 75.0.3770.143. Even if you don't use Privacy Browser, you should always keep your WebView up to date because it is used by a lot of other apps to render content. https://www.stoutner.com/privacy-browser/common-settings/webview/

2.  Privacy Browser is currently Android-only, but in the future there will also be a desktop version. https://www.stoutner.com/3-x-series-roadmap/

**Comment by Mikaela** [comment]
Thanks, so if we add a warning to keep Android Webview up-to-date, there also needs to be a note that it's only possible on 5.0+.

**Comment by sorenstoutner** [comment]
Oh, yes.

You should also include a warning for your desktop browsers that Windows need to be kept up to date with the latest security fixes and that it is only possible on Windows 7 and newer.  ;)

**Comment by blacklight447-ptio** [comment]
I would propose we would create a sub section on the browser page, with desktop, android and IOS browser, where we could list privacy browser as one of the options among the android browsers.

**Comment by GrimPixel** [comment]
I don't think it is necessary to create a sub section, because it means that a browser will be mentioned repeatedly.

I think sticking with the platform icons is good. It would be better to add platform filters.

**Comment by blacklight447-ptio** [comment]
As we will now be listing privacy browser under the worth mentioning section on Android, I will be closing  this issue.
