### ISSUE TITLE
❌ Software Removal | Forget (forget.codl.fr)

### ISSUE THREAD

**Issue by JonahAragon** [privacytoolsIO/privacytools.io#1061]
**Research required.** If anyone has information related to this please let me know.

In Matrix I received this message:

> forget collects and saves posts it deletes from some masto instances. please delist it.

> this is listed on privacytools.io https://forget.codl.fr/about/

> couple of the instances it does it on are librem one and mstdn.io

I don't have a source on this information, or know whether or not this is true. But the claim may be worth looking in to.

**Comment by JonahAragon** [comment]
Also, is anyone aware of a self-hostable script that could be run instead of this service for Twitter and/or Mastodon? Might be worth listing such a script in replacement of this instead.

**Comment by jacnoc** [comment]
Someone that knows python could look through the source (available [here on github](https://github.com/codl/forget)) to see if this is true.  Also, in response to @JonahAragon, Forget is self-hostable.

IF these claims are true, it could be recommended to self-host it instead of one hosted by someone else.

**Comment by blacklight447-ptio** [comment]
I have not been able to find any evidence for this when looking into it, closing issue until anyone can find further evidence.
