### ISSUE TITLE
❌ Software Removal | Blokada

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1123]
## Description

Related to https://github.com/privacytoolsIO/privacytools.io/issues/533#issuecomment-520053405 I wonder if we should delist Blokada for now until they implement DoT or DoH support (https://github.com/blokadaorg/blokada/issues/198) or DNSCrypt (https://github.com/blokadaorg/blokada/issues/147) support as currently if user has DoT (Private DNS) enabled, Blokada disables it allowing network attacker spoof DNS queries and spy on them?

I am not sure how realistic concern DNS query spying is though as SNI is going to leak most of visited domains and not all IP addresses are hosting multiple sites.

**Comment by Mikaela** [comment]
Looking at them better, this [seems to be in their highest popularity label](https://github.com/blokadaorg/blokada/labels/popularity-3) and in their [Rustification project](https://github.com/blokadaorg/blokada/projects/11#card-24405845) so delisting may be a bit hasty.

**Comment by blacklight447-ptio** [comment]
I recommend holding off for a bit to see what happens, could you keep an eye on this for us?

**Comment by Mikaela** [comment]
I am subscribed to the issues at least.

CC: @beerisgood whom I have seen on both issue trackers.

**Comment by beerisgood** [comment]
Blokada is still the best tracking blocker. We should wait until they fix the problems

**Comment by blacklight447-ptio** [comment]
In that case I will be closing this is, and propose that @beerisgood and @Mikaela  could have a little eye on it, and reevaluate later on.

**Comment by Mikaela** [comment]
I wonder if we should reconsider this due to https://github.com/privacytoolsIO/privacytools.io/issues/1187#issuecomment-523313881,

> Correct me if I'm wrong, but except for a handful of features Nebulo offers all functionality Blokada has. You can block ads by importing DNS rules from host lists, you can blacklist/whitelist apps, you can configure a lot about the app and how it handles stuff. It isn't themed as an AdBlocker though because it is mainly distributed over the Play Store. I have a F-Droid repo as well though (which contains ad-blocking DNS servers and ad-blocking host lists by default).

Nebulo F-Droid lists these DNS by default:

* AdGuards
* Blahdns
* DnsWardens

And these adblock lists (in dns rules):

* AdAway
* CoinBlockerList
* Energized Basic
* Energized Blu
* Energized Porn

I am not sure if there is more as it looks like the last one doesn't fit my screen entirely and it's not scrollable.

**Comment by nitrohorse** [comment]
From my understanding it sounds like Blokada provides a subset of Nebulo’s features. I can’t personally test these but it sounds like users only gain functionality with Nebulo.

**Comment by blacklight447-ptio** [comment]
is nebulo as easy to use as blokada?

**Comment by Ch4t4r** [comment]
I'd say yes. You have a main view which contains just three buttons, one labeled "Start" to start the app, one for selecting the server to use and one for comparing the various servers. An image indicates at a glance whether the app is currently active.

![image](https://user-images.githubusercontent.com/26578153/63997458-dbd23080-cafe-11e9-896d-c69c3b001dab.png)

I'm not sure whether Blokada should be removed though. Whilst I still believe that Nebulo contains most (and if not close to all) functionality of Blokada it isn't themed as an AdBlocker and is more of an all-purpose DNS changer. GPlay doesn't allow AdBlockers in the store, which is why Nebulo only contains servers which block ads in the F-Droid version.
If purely focusing on the privacy Nebulo should have the upper hand though, as it encrytps the queries whilst Blokada does not.

Some more Screenshots:
[1](https://user-images.githubusercontent.com/26578153/63997837-f0fb8f00-caff-11e9-9119-0fe5b2d2c400.jpg)
[2](https://user-images.githubusercontent.com/26578153/63997908-2d2eef80-cb00-11e9-8789-ca27ca81ff9e.png)
[3](https://user-images.githubusercontent.com/26578153/63997931-36b85780-cb00-11e9-9116-ae8e6f4b0124.png)
[4](https://user-images.githubusercontent.com/26578153/63997938-3d46cf00-cb00-11e9-840e-582337752eea.png)
[5](https://user-images.githubusercontent.com/26578153/63997953-433cb000-cb00-11e9-894e-623ee107ca2d.png)

**Comment by ph00lt0** [comment]
I don't understand this delist, Netguard is still recommended? I think apps like these also including TrackerControl (#2333) can add privacy, a warning about DOH should do. It obviously depends on your thread model, but I consider ISP's more trustworthy then all these advertising and big data companies. It is a trade off, but I think this choice is country and user specific. If this decision stays Netguard should be delisted for the same reason.
