### ISSUE TITLE
🆕 Software Suggestion | Fedora Workstation

### ISSUE THREAD

**Issue by dawidpotocki** [privacytoolsIO/privacytools.io#1130]
**Name:** Fedora
**Category:** OS
**URL:** https://getfedora.org

I think we lack easy-to-use distribution that will work on most devices.
At the moment there are 3 operating systems for PCs listed:
* Debian
* Trisquel
* Qubes OS

### Problems with Debian
It is not the most noob-friendly distro and does comes with 100% free kernel, which means that a lot of devices will not work.

### Problems with Trisquel
Comes with 100% free kernel and 100% free repos, which means that a lot of devices will not work… and sorry, but it looks like trash.

### Problems with Qubes OS
It isn't the easiest distro to use, for sure.

### Why Fedora?
It is distro which comes with easy to use installer and _"standard"_ Linux kernel.
It means that it should work fine for most devices.
Repos are 100% free (other than Linux), but when you open GNOME Software, there is an option to enable 3rd party repo to install NVIDIA drivers, which may be needed.
Fedora uses SELinux, Flatpak (but without any repo enabled like Flathub) and Wayland (GNOME Shell) by default, which is better for security, I guess.
There are also [Fedora Spins](https://spins.fedoraproject.org/), which are just Fedora + different desktop environment, everyone can choose whatever they like.
It is developed by Fedora Project, which is sponsored by Red Hat.

### Why not just Ubuntu?
There was an Amazon controversy.
> From October 2012, it sent the user's queries through a secure HTTPS connection from the home lens to productsearch.ubuntu.com, which then polled Amazon.com to find relevant products; Amazon then sent product images directly to the user's computer through HTTP. If the user clicked on one of these results and then bought something, Canonical received a small commission on the sale.
…as the home lens is the normal means to search for content on the local machine, reviewers were concerned about the disclosure of queries that were intended to be local, creating a privacy problem.

Because of it and new system usage data collection, some people are skeptical.

### Why not Linux Mint?
Their site was compromised few times and was pointing at modified ISOs with a backdoor in it.

### Why not Manjaro?
It is not the most user-friendly OS, but better than Arch.
They hold updates (2-3 weeks), just for the sake of it (it is supposed to be more _"stable"_), even security updates.
They also forgot to update SSL certificates, twice and suggested stupid workarounds, like changing system time.
First time: https://archive.fo/JeOLo
Second time: https://archive.fo/XV70t

### Why not elementaryOS?
I don't like what developers of it done/do.
It makes look GTK apps not made specially for elementary like crap, because… who knows.
Developers saying that people cheat by downloading it for free (and they give such option to everyone at the same time): https://archive.fo/XV70t ([discussion on reddit](https://old.reddit.com/r/linux/comments/2vi6qo/you_are_a_cheater_if_you_download_elementryos_for/))
> We want users to understand that they’re pretty much __cheating__ the system when they choose not to pay for software.

Author of elementary OS does not like when people distribute his software that is under GPLv3, but he is fine with distributing software from GNU, Linux, PulseAudio, systemd and every other thing that is in Ubuntu repos.
> I'm really not happy with this approach of FlatHub of packaging up other people's apps and distributing them without their consent. I don't want my name and links to my repo and my website attached to software that I never intended to distribute to FlatHub's users and that won't be getting any support from me.

### Why not openSUSE?
I don't know, I guess it could be considered instead of Fedora, but I can't say a lot about it.

**Comment by Mikaela** [comment]
> I think we lack easy-to-use distribution that will work on most devices.

I am not confident that Fedora is this distribution, or at least it wasn't in the past.

From their [editions page](https://getfedora.org/en/workstation/):

> Created for Developers.
> Fedora Workstation is a reliable, user-friendly, and powerful operating system for your laptop or desktop computer. It supports a wide range of developers, from hobbyists and students to professionals in corporate environments.

I think this may not be a good advertisement for a basic user who is not a developer.

Another issue I have with Fedora is that traditionally their OS updates have been every 9 months or so making the previous release EOL, and I don't remember how the update process is launched, but I know that a family member I don't see often had years old Fedora and the best thing I thought of that time was to just backup everything and remove all traces of it.

Debian I think is supported for 5 years at a time, and Ubuntu LTS has a long support too.

Personally I would recommend Debian or Ubuntu, but Fedora reminds me of CentOS, is it still alive? However my touch with it is older software than with Debian and removing support for not so recent hardware such as ethernet adapter of one machine at my family, so I couldn't honestly recommend it either.

**Comment by dawidpotocki** [comment]
> > Created for Developers.
> > Fedora Workstation is a reliable, user-friendly, and powerful operating system for your laptop or desktop computer. It supports a wide range of developers, from hobbyists and students to professionals in corporate environments.
>
> I think this may not be a good advertisement for a basic user who is not a developer.

Does this matter really, egh? It's just advertising. It's not like
Ubuntu does not put on the homepage stuff like IoT, Kubernetes,
OpenStack, multi-cloud and machine learning… and still they are the most
popular one.

> Another issue I have with Fedora is that traditionally their OS updates have been every 9 months or so making the previous release EOL, and I don't remember how the update process is launched, but I know that a family member I don't see often had years old Fedora and the best thing I thought of that time was to just backup everything and remove all traces of it.

Though I don't think that this family member even if would run Ubuntu or
Debian, would update packages.
Update process now seems really easy. Soon after release, a notification
appears to tell you that there is an update available.
Or just go to GNOME Software and you will see big update banner.

> Personally I would recommend Debian or Ubuntu, but Fedora reminds me of CentOS, is it still alive?

Red Hat Enterprise Linux is based on Fedora. CentOS is just a rebrand of
RHEL.

**Comment by blacklight447-ptio** [comment]
I run fedora on a few machines, it actully is really usable, the installation was just a  typ of  "next next next" and after that everything worked out of the box.

**Comment by nitrohorse** [comment]
Not hijacking this discussion, but throwing in [Pop!_OS](https://system76.com/pop) by System76 for consideration. Very usable imo also.

**Comment by Mikaela** [comment]
> or at least it wasn't in the past.

due to unrelated things I remember that this has been between 2012-2016 and if @privacytoolsIO/editorial supports Fedora, I am fine with it's inclusion.

> Though I don't think that this family member even if would run Ubuntu or
Debian, would update packages.

They do on Debian, with help from Plasma Discover and backends, but I do have SSH access and update at times when I notice it online in case that hasn't been done otherwise.

**Comment by nitrohorse** [comment]
I just add a disclaimer that I haven't personally used Fedora so I'll have other team members weigh in :smile:

**Comment by TNTBOMBOM** [comment]
Fedora bad side:

- It made some exceptions for non-free firmware to be included. 
Ref: https://www.gnu.org/distros/common-distros.html#Fedora

- The distro and their packages comes to you with no stability (distro breaks down , packages issues thus not the best stability and as a result not security)

- It came to public to support to stabilize the commercial distro RH , its not really meant to be standalone service by itself distro like Debian. (as they already mentioned its for developers not noob users)

- Not the best With Security: 

```
The Fedora Project (on which we have based Qubes dom0 and whose tools we use for building the final ISO) is, sadly, another example of build security negligence: not only do Fedora tools not verify signatures on the downloaded packages (from which the ISO is to be built), their developers have also avoided merging our patches to fix that problem for nearly a year now!
```
Source: https://www.qubes-os.org/news/2016/05/30/build-security/

- Owned by IBM now and even before , their interest are not for the user or community but only for enterprises methodology which intern the distro can become proprietary or include wider proprietary support ...etc depends on the how the X will pay them. (IBM already backdoored their products for the NSA anyway, so to see it in RH/Fedora not something surprises)

Suggestion to watch: https://invidio.us/watch?v=dy3-QZLTpbQ

...etc 

The best thing to do if someone want to mention Fedora in anyway is in worth mentioning distro. But as a recommended distro for sure. 

ThX!

**Comment by ghbjklhv1** [comment]
> **Name:** Fedora
> **Category:** OS
> **URL:** https://getfedora.org
> 
> I think we lack easy-to-use distribution that will work on most devices.
> At the moment there are 3 operating systems for PCs listed:
> 
>     * Debian
> 
>     * Trisquel
> 
>     * Qubes OS
> 
> 
> ### Problems with Debian
> 
> It is not the most noob-friendly distro and does comes with 100% free kernel, which means that a lot of devices will not work.
> ### Problems with Trisquel
> 
> Comes with 100% free kernel and 100% free repos, which means that a lot of devices will not work… and sorry, but it looks like trash.
> ### Problems with Qubes OS
> 
> It isn't the easiest distro to use, for sure.
> ### Why Fedora?
> 
> It is distro which comes with easy to use installer and _"standard"_ Linux kernel.
> It means that it should work fine for most devices.
> Repos are 100% free (other than Linux), but when you open GNOME Software, there is an option to enable 3rd party repo to install NVIDIA drivers, which may be needed.
> Fedora uses SELinux, Flatpak (but without any repo enabled like Flathub) and Wayland (GNOME Shell) by default, which is better for security, I guess.
> There are also [Fedora Spins](https://spins.fedoraproject.org/), which are just Fedora + different desktop environment, everyone can choose whatever they like.
> It is developed by Fedora Project, which is sponsored by Red Hat.
> ### Why not just Ubuntu?
> 
> There was an Amazon controversy.
> 
> > From October 2012, it sent the user's queries through a secure HTTPS connection from the home lens to productsearch.ubuntu.com, which then polled Amazon.com to find relevant products; Amazon then sent product images directly to the user's computer through HTTP. If the user clicked on one of these results and then bought something, Canonical received a small commission on the sale.
> > …as the home lens is the normal means to search for content on the local machine, reviewers were concerned about the disclosure of queries that were intended to be local, creating a privacy problem.
> 
> Because of it and new system usage data collection, some people are skeptical.
> ### Why not Linux Mint?
> 
> Their site was compromised few times and was pointing at modified ISOs with a backdoor in it.
> ### Why not Manjaro?
> 
> It is not the most user-friendly OS, but better than Arch.
> They hold updates (2-3 weeks), just for the sake of it (it is supposed to be more _"stable"_), even security updates.
> They also forgot to update SSL certificates, twice and suggested stupid workarounds, like changing system time.
> First time: https://archive.fo/JeOLo
> Second time: https://archive.fo/XV70t
> ### Why not elementaryOS?
> 
> I don't like what developers of it done/do.
> It makes look GTK apps not made specially for elementary like crap, because… who knows.
> Developers saying that people cheat by downloading it for free (and they give such option to everyone at the same time): https://archive.fo/XV70t ([discussion on reddit](https://old.reddit.com/r/linux/comments/2vi6qo/you_are_a_cheater_if_you_download_elementryos_for/))
> 
> > We want users to understand that they’re pretty much **cheating** the system when they choose not to pay for software.
> 
> Author of elementary OS does not like when people distribute his software that is under GPLv3, but he is fine with distributing software from GNU, Linux, PulseAudio, systemd and every other thing that is in Ubuntu repos.
> 
> > I'm really not happy with this approach of FlatHub of packaging up other people's apps and distributing them without their consent. I don't want my name and links to my repo and my website attached to software that I never intended to distribute to FlatHub's users and that won't be getting any support from me.
> 
> ### Why not openSUSE?
> 
> I don't know, I guess it could be considered instead of Fedora, but I can't say a lot about it.

Fedora has too many non-free components, IMO.
There was some hope with BLAG but has since been discontinued.

**Comment by ghbjklhv1** [comment]
> Why not elementaryOS?

I think your asking the wrong question. 

The question is "Why add x?". 

These OSes provide no advantage over existing distros and have no libre alternatives as is different from Debian (gNewSense), Arch (Parabola), OpenBSD (LibertyBSD), Slackware (Freenix), Knopper (Musix - Discontinued), e.c.t. Most major OSes have an FSDG mirror or some form of wiki like FreeSlack.

**Comment by TNTBOMBOM** [comment]
> Most devices without nonfree firmware will not work properly.
Not software issue , This is hardware manufacture needs to resolve. Other meaning user should pick up the right equapment when choose to buy things to work with free software and there are alot of markets providing totally free stuff like laptops , desktops/workstaions , printers , wifi chips  ...etc. 

We are not in early 2000s , your speech would be effective before 20 years but not now. 

> Qubes OS, 

Qubes has way much different design than any existent distro, it has no comparison to fedora even with nonfree firmwares. Thus Qubes until today searching for free hardware to run it needs and until now none at the moment. Tried Power9 processors but sadly doesnt support Xen virtualization so until then no body know when it will come. So hardware available for totally free GNU/Linux just not for Qubes. Also Qubes is security focused distro (means hardening of things within it , not as Fedora)

>  LineageOS, GrapheneOS

im not a fan of android based things as well. 

> I have no idea what you just said.

Packages not stable so as in debian (or debian based philosophy) thus leading to alot of issues.

> Maybe I don't quite get it, but seems to not be a problem for their use-case of the tool and I think it is "fixed" now.

Yeah thats why its written by the end of the ticket: "If you still want to have this feature, it would have to be ported to the new codebase." 

> Fedora is community project, it is not owned by Red Hat. Most of the contributions to Fedora are not from Red Hat employees.

I dont know who to believe...

> Red Hat provides the Fedora project with a wide variety of resources, including full-time employee support, infrastructure hardware and bandwidth, event funding, and legal counsel. 

https://getfedora.org/sponsors/

**Comment by ghbjklhv1** [comment]
Debian is a really cool OS. They prioritize freedom.
If you want non-free they have a port: https://cdimage.debian.org/cdimage/unofficial/non-free/

**Comment by dawidpotocki** [comment]
> > Most devices without nonfree firmware will not work properly.
> Not software issue , This is hardware manufacture needs to resolve. Other meaning user should pick up the right equapment when choose to buy things to work with free software and there are alot of markets providing totally free stuff like laptops , desktops/workstaions , printers , wifi chips  ...etc.
>
> We are not in early 2000s , your speech would be effective before 20 years but not now.

Do you understand that most of the people will not buy another
PC/laptop, just because you do? They have hardware and they want that to
work. I'm not going to throw away my 3 laptops, I want to use them, because
they are still working and will work for ages. I think you don't get the
point of this issue that I created.

> >  LineageOS, GrapheneOS
>
> im not a fan of android based things as well.

I'm also not fan of Android, I actually hate it, but does it matter?
Will you suggest to only list Replicant, because it is 100% free?

> Packages not stable so as in debian (or debian based philosophy) thus leading to alot of issues.

Sorry but I'm running even more bleeding edge distro, called Void Linux.
I was before running Arch and I can tell you, that they are stable. Most
people don't want to run 5 year old software. And also remember that old
software has bugs, that are fixed in new versions. They are only stable
in sense that they don't change and you can expect how it works and what
does not.

> > Fedora is community project, it is not owned by Red Hat. Most of the contributions to Fedora are not from Red Hat employees.
>
> I dont know who to believe...
>
> > Red Hat provides the Fedora project with a wide variety of resources, including full-time employee support, infrastructure hardware and bandwidth, event funding, and legal counsel.
>
> https://getfedora.org/sponsors/

They are sponsored, not owned by them. Just like RISC-V is not NVIDIA,
Facebook or Google project, even if they also work on the codebase.

**Comment by TNTBOMBOM** [comment]
> Do you understand that most of the people will not buy another PC/laptop, just because you do?

You throw away the blob firmware like wifi chip or so which will cost couple of dollars. 

Note: Debian or FSDG or similar distros doesnt prevent user to install nonfree firmwares manually (because thats prevention is DRM) , it just doesnt come with blobs like fedora and sometimes nor packaging  it. so you can still download and install it. 

So i thin your point here is useless to ship blob distro by default. 

> Will you suggest to only list Replicant, because it is 100% free?

its android based as well. i said not android based thing something like librem5 which is Debian GNU/Linux (once its finished) 

> Most people don't want to run 5 year old software. And also remember that old software has bugs, that are fixed in new versions. They are only stable in sense that they don't change and you can expect how it works and what does not.

Thats not Debian philosophy. Stable doesnt mean not working  or containing bugs otherwise it will be deprecated.  Please read/know debian packaging system how it works. 

Having instant upgrades to testing phase software actually which causes bugs (some of them security flaws) and distro collapsing. 

>They are sponsored, not owned by them. Just like RISC-V is not NVIDIA, Facebook or Google project, even if they also work on the codebase.

hmm do you know they already merged since 16 years ago? 

https://web.archive.org/web/20031001204515/http://www.fedora.us/

**Comment by dawidpotocki** [comment]
> Having instant upgrades to testing phase software actually which causes bugs (some of them security flaws) and distro collapsing.

How are release versions "testing"? No distro is really pushing
beta/alpha versions or just random newest commit from repository.

**Comment by ghbjklhv1** [comment]
@dawidpotocki IMO, Replicant should at least be recommended ahead of LineageOS.
The team has a much better focus on privacy, while Lineage just cares about customization and hardware  support.

**Comment by blacklight447-ptio** [comment]
@ghbjklhv1 not really, as replicant is, last I checked,hardly usable IRL,with no 3/4g support , and only WiFi support with a dongle, and last I also checked, it only supports heavily dated devices like the S3.
You should not forget that ptio isn't only a site for whistleblowers and stallmans, but also the general public which wants some privacy. And that same general public is VERY unlikely to run a Samsung galaxy s3, and deal with the lack of cellular service and WiFi over a dongle.

**Comment by JonahAragon** [comment]
> whistleblowers

not even whistleblowers should be using 100% FOSS, especially something as outdated as Replicant lol

**Comment by JonahAragon** [comment]
@TNTBOMBOM FYI, Red Hat Enterprise Linux is *based on* Fedora Linux. This means that Red Hat employees have an incentive to develop and improve Fedora, because changes to Fedora will make their way to RHEL. This does not mean Red Hat controls or owns the Fedora Project.

Saying Fedora is owned by Red Hat would be like saying Debian is owned by Canonical.

**Comment by WorryTheBirds12** [comment]
> @ghbjklhv1 not really, as replicant is, last I checked,hardly usable IRL,with no 3/4g support , and only WiFi support with a dongle, and last I also checked, it only supports heavily dated devices like the S3.

**To add onto what others stated**:
Replicant is out of date, but they put a lot of work into privacy.

> not even whistleblowers should be using 100% FOSS, especially something as outdated as Replicant lol

I really don't mean to be rude, but what do the heck do you recommend? XD
FOSS fixes security bugs a lot quicker if it is a public;y made bug. 

Replicant is especially good at this: https://www.wikipedia.org/wiki/Replicant_(operating_system)#Security

Please stop making jokes at FOSS. Some people seem to think it is funny, but it really just spreads false info. Github is for civilized discussion not to mock whole industries like FSM.

**Comment by WorryTheBirds12** [comment]
F-Droid is totally awesome:
https://www.wikipedia.org/wiki/F-droid
Plus is 100% supported in Replicant.

**Comment by TNTBOMBOM** [comment]
> How are release versions "testing"? No distro is really pushing beta/alpha versions or just random newest commit from repository.

Not sure i got your question.

> also, fedora is out of the box a lot more secure then debian. it has Selinux out of the box, it applies a ton of hardening patches aswell, it also uses wayland, which is all listed above.

ha! seems you dont know debian has apparmor pre-installed already as well plus with all what you have mentioned. packages quality and stability for debian it cant be compared to fedora. like i said pushing the latest changes to distro causes alot of problem , fedora just with me collapsed 2 times what are you talking about.

compare fedora to ubuntu trash sound ok, but dont compare it to debian.

> just because an distro is less stable does not mean its less secure then a distro with heavily outdated packages like debian

Im sorry but seems you dont know about long testing phase is essential to guarantee that there is no way of bugs. pushing it to the end user causes alot of problems and fedora users know that already. packages in debian outdated but not insecured, because security patches only allowed to be pushed directly to the stable phase. like i said fedora is not debian at all to be compared with, other word debian too high for fedora ;)

> not even whistleblowers should be using 100% FOSS, especially something as outdated as Replicant lol

say that to edward snowden: 

https://media.libreplanet.org/u/libreplanet/m/libreplanet-2016-the-last-lighthouse-3d51/

True Replicant is outdated , true they are forced to shutdown 3g/4g because google/samsung ..etc from shitty companies doesnt allow you to twist their software without loosing benefits (needs blobs). But hey let us just back to 80s or 90s or even early 2000s where there was no to very little free software on the field if ppl or even stallman following your philosophy no body gonna be free today.

>@TNTBOMBOM FYI, Red Hat Enterprise Linux is based on Fedora Linux. This means that Red Hat employees have an incentive to develop and improve Fedora, because changes to Fedora will make their way to RHEL. This does not mean Red Hat controls or owns the Fedora Project.

LMAO if that is not mean controlling it then what is it? 

> Saying Fedora is owned by Red Hat would be like saying Debian is owned by Canonical (the creators of Ubuntu, which is based on Debian).

Debian has not been merged with Canonical , Debian doesnt depend on anyway what Canonical is doing. Buying Ubuntu has no relation with Buying Debian. While its not the same case with IBM/RH: 

Pray that IBM will not vanish Fedora lol

https://ask.fedoraproject.org/en/question/128211/whats-going-to-happen-to-fedora-if-ibm-buys-red-hat/

**Comment by blacklight447-ptio** [comment]
With all do respect tntbombom, most of what you are saying are just opinions and fear mongering, not facts. It seems that you have a particular dislike for Fedora, I don't know why. Anyway, If you keep up with the useless fear mongering, then we will just ignore your comments, until you can come back to make proper arguments.

**Comment by blacklight447-ptio** [comment]
@WorryTheBirds12 I would recommend graphene is, as is supports modern security features like verified boot, isolated basebands SMMU and keeps all firmware up to date. With lineage as a second best, as while it keeps android up to date, it does not update firmware, nor does it have verified boot.

Also, I really don't want to make fun of Foss, I'm a big foss activist myself, but just because an os is not completely open source is acceptable for me, as long as its just a bunch of drivers. As an example: say some guy wants to move to Linux, he  couldn't before because his new fancy graphics card wasn't supported by the open source drivers. Now what if he can move to Linux, but with a closed source driver? IMO running Linux with a closed source driver is already a enormous improvement over running windows.

**Comment by SISheogorath** [comment]
You might want to consider as one positive aspect about Fedora, that it provides (at least from my perspective) some quite nice and user-friendly articles about the distro in the [Fedora Magazine](https://fedoramagazine.org/) Including [upgrade instructions for each release](https://fedoramagazine.org/upgrading-fedora-29-to-fedora-30/). Also an [active community](https://discussion.fedoraproject.org/) around the distro that tires to help. Due to the usage of Disqus hopefully a bit friendlier towards end user than classic mailing lists.

Also easy ways to find your own way into the community even without being a programmer or similar:
https://whatcanidoforfedora.org

And of course all of this while working specifically towards upstream and not to custom patched versions within the distro.

For the concerned people about updates, yes, they were a problem in past, but in the recent 2-4 years things got really smooth and as long as people don't start to disassemble the distro (i.e. trying to to do things that are not supposed to be done) it's really nice. So I would recommend it for people who look for a distro with strong defaults and freedom in the home directory. Some people prefer fully customized setups but personally I don't consider Fedora to be made for that. But also don't think that you need a recommendation for a distro when you do things like that. So from that perspective it probably fits the requirements for the list quite well :)

**Comment by TNTBOMBOM** [comment]
@SISheogorath you are the only one who is truly used and old Fedora user ;). (except Fedora isnt totally freedom distro)
