### ISSUE TITLE
❌ Software Removal | NordVPN

### ISSUE THREAD

**Issue by isbewnsjv** [privacytoolsIO/privacytools.io#1162]
As I use NordVPN both on my computer and on Android. There was an update to the Android version which turns on Telemetry or Tracking by DEFAULT. Without any notification to the user. I was lucky and went into the settings that day to set a new custom DNS and saw an option called "Help us improve" turned ON by default and I didn't know about it. 

Another thing is the speed of the servers goes down like 50%, not always, but almost everytime you start downloading files or torrents. And Linux support sucks. Does not look like they care for anything related to security nor privacy.

Been using them for 2 years now and I can tell you even the Windows version is bad because sometmes it just disconnects without me noticing, even on Linux.

I don't see NordVPN as a great option anymore. After my subscription is over I am never coming back to Nord and I will pay for better services like Mullvad!!

**Comment by TNTBOMBOM** [comment]
> There was an update to the Android version which turns on Telemetry or Tracking by DEFAULT. Without any notification to the user. I was lucky and went into the settings that day to set a new custom DNS and saw an option called "Help us improve" turned ON by default and I didn't know about it.

you were able to turn it off? have you checked your out connection with wireshark or any tool to see any leaks? 

Although telemetry collected by any VPN provider doesnt add too much sense to the fact they can already see your traffic , who you are and where are you going what are you doing..etc  thats just the VPN design. 

> Been using them for 2 years now and I can tell you even the Windows version is bad because sometmes it just disconnects without me noticing, even on Linux.

Thats every VPN issue , thats why there is kill switch option created so that when the VPN goes down your traffic will not go on the clearnet until the VPN connection back again. 

> I don't see NordVPN as a great option anymore. After my subscription is over I am never coming back to Nord and I will pay for better services like Mullvad!!

I do see Mullvad good option because they have good team behind but lets not forget is already located in one of the eyes countries around the world (Sweden) thus making NordVPN higher rank since its located in Panama which is they are out of the eyes control.  

idont see any additional security between Mullvad over NordVPN. They are equal with what they provide through their tools. (unless there is a serious test report that im not aware of)

**Comment by merlinnusr** [comment]
>Another thing is the speed of the servers goes down like 50%,

But privacytools.io is a website to recommed good VPN with good transparency and a good opsec, no to recommed the speediest vpns

**Comment by TNTBOMBOM** [comment]
@JonahAragon Can you put some details on why you choose to delete NordVPN?

**Comment by JonahAragon** [comment]
NordVPN does not have public-facing leadership or ownership, so it's difficult to determine their motives. Sending all your data to a certain provider is a big ask. It's easier to trust [a provider who shares their team members and ownership publicly](https://mullvad.net/en/what-is-privacy/) compared to a faceless corporation from Panama.

**Comment by TNTBOMBOM** [comment]
> NordVPN does not have public-facing leadership or ownership, so it's difficult to determine their motives. Sending all your data to a certain provider is a big ask. It's easier to trust [a provider who shares their team members and ownership publicly](https://mullvad.net/en/what-is-privacy/) compared to a faceless corporation from Panama.

I see , what about others like IVPN or ProtonVPN do you have links for who by team members and ownership behind them?

**Comment by JonahAragon** [comment]
> what about others like IVPN or ProtonVPN

IVPN: https://www.ivpn.net/aboutus lists all(?) 8 team members.

ProtonVPN: does not list team on their site, but is owned by ProtonMail which does https://protonmail.com/about

**Comment by TNTBOMBOM** [comment]
Yep you are right, i opened a ticket about clarifying their agenda but
no reply.

Jonah Aragon:
>> what about others like IVPN or ProtonVPN
> 
> IVPN: https://www.ivpn.net/aboutus lists all(?) 8 team members.
> 
> ProtonVPN: does not list team on their site, but is owned by ProtonMail which does https://protonmail.com/about
>
