### ISSUE TITLE
✨ Feature Suggestion | <wifi|wlan>.privacytools.io (openwireless.org revived)?

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1184]
## Description:

I was thinking about open WLAN networks and https://openwireless.org/ and it's issues and started wondering at the team chat if it's something PTIO could do. I am not sure how to format the issue, so I am quoting myself from Wire team chat:

*if you aren't familiar with [the Open Wireless Movement, you may want to check openwireless.org](https://openwireless.org/)*

> Silly idea: https://wlan.privacytools.io/ or similar to https://openwireless.org/ with actually having a community? And fixing it's issues like _nomap and having 5Ghz WiFi?
> 
> I should probably forum it though
>
> see also:
> * https://github.com/EFForg/OpenWireless/issues?utf8=✓&q=author%3AMikaela+
> * https://github.com/EFForg/OpenWireless/issues?utf8=✓&q=commenter%3AMikaela+
> 
> I think the base could be similar to openwireless, but 5GHz would need to be docuemnted as something like wlan.privacytools.io_fast_nomap and there should be the be nice badge and probably some tools on staying safe on the open WLAN like linking to our encrypted DNS page as otherwise the hotspot owner can control the traffic and maybe a suggestion to use Tor Browser
> 
> I have given up hope with openwireless a long time ago judging by the issue tracker and my WLAN has been Piraattipuolue.fi_nomap and now stationary piraattipuolue.fi_nomap advertising PPFI, but I have a properish router now that can have multiple SSIDs and happened to think about it again as it would be nice if the openwireless idea could be reality and WLAN roaming just worked

@nitrohorse commented:

> That’s a really cool idea; til about openwireless.org. Now I’m sad it’s no longer a focus for the EFF 😢

and I continued:

> Oh, another problem is what to do if there are multiple similar SSIDs in close proximity

replied to @nitrohorse :

> It never was for more than two blog posts or so, judging by me on the website
> 
> I have apparently last talked about it in January and gotten suggested to start a movement in Helsinki, but I didn't get pirates interested, because we were simultaneously in the middle of elections
> https://github.com/EFForg/OpenWireless/issues/305#issuecomment-456495091

@nitrohorse :

> yeah I went through the issues you posted which were good questions
>  We should create an issue to track this; i like this idea.

me again:

> 👍 I will after returning home, currently in supermarket

and here is the issue.

**Comment by Mikaela** [comment]
> ...I have a properish router now that can have multiple SSIDs...

*\*sigh\** apparently my current router only supports a single SSID while in SSID mode and I am staying with `piraattipuolue.fi_nomap` for now, so I wouldn't be able to contribute.

**Comment by ggg27** [comment]
So like a community wireless network?
https://www.wikipedia.org/wiki/Community_wireless_network

**Comment by Mikaela** [comment]
That Wikipedia page seems closer to a mesh network to me, while I am after more like
https://en.wikipedia.org/wiki/OpenWireless.org

**Comment by hugoncosta** [comment]
A movement similar to this is basically the norm in Portugal. AFAIK, two of the biggest telcom providers started introducing that a couple of years ago for the wrong reasons. Basically, using the home/guest division, they started creating this "telcom-wifi" network, where people that owned that a wireless router with that protocol active could use other people's router using their telcom login, while others would be free to buy access to it for a certain hourly/daily amount (like in hotels).

The movement makes perfect sense, especially due to the possible redundancy of IP as evidence of a crime, but with "enhanced" metrics and the easier access to internet through your phone (the device you are most likely to use while outside the house in the scenario they describe), this movement doesn't have the weight it probably once had. 

Nonetheless, I believe that it could still be implemented with the framework I described above. I don't believe we can do much using the website.

**Comment by Mikaela** [comment]
> Basically, using the home/guest division, they started creating this "telcom-wifi" network, where people that owned that a wireless router with that protocol active could use other people's router using their telcom login, while others would be free to buy access to it for a certain hourly/daily amount (like in hotels).

This sounds like captive portals and I think they are going to break the majority of privacy tools, if not all :(

> What about captive portals? +
> Oftentimes, logging onto an open wireless network in an airport or cafe takes you to a login page where you either have to enter your credentials or click an "I agree" button (agreeing to certain terms of service) before being connected to the Internet. This is known as a captive portal (or a catch-and-release).
> 
> The Open Wireless Movement seeks to create an environment where devices can connect to "openwireless.org" networks seamlessly and easily; captive portals, which are a barrier between the user and a connection, are the antithesis of good design for openness.
> 
> Captive portals interfere with Internet security and protocol innovation—and the efficiency that lies at the heart of the Open Wireless Movement—without providing many benefits, and we discourage their use, especially for networks named "openwireless.org"

* https://openwireless.org/

> ...but with "enhanced" metrics and the easier access to internet through your phone (the device you are most likely to use while outside the house in the scenario they describe)...

I don't know what you mean with the first part, but access to the internet through phone is not so easy or at least will get expensive especially abroad. In the EU, roaming prices should be reasonable, but at least Finnish carriers have a permission to charge higher prices abroad due to mostly having unlimited data in homeland and the prices are even more expensive outside the EU, I don't know how it works for non-EU carriers.

I have been in the situation where I have wanted to download OSMAnd~ map for foreign country while actually in the country as I wasn't thinking about it when I should have.

**Comment by hugoncosta** [comment]
They're indeed captive portals. 
Regarding roaming, in the EU there is none assuming your trip takes less than 3 months. Obviously tourism is a big factor when it comes to the OWM, I just think that captive portals, even though with their problems (data mined, etc), might be a compromise, because I don't see a plausible way to get the millions of routers out there open if not done by default by the telecom providers.

**Comment by blacklight447-ptio** [comment]
Now: would this REALLY be in the scope of our site?

**Comment by Mikaela** [comment]
I think it's enough on the border to fall out of scope.
