### ISSUE TITLE
DNS Server Suggestion Removal

### ISSUE THREAD

**Issue by ProgressiveArchitect** [privacytoolsIO/privacytools.io#1215]
The DNS Sever Suggestion section is already packed with suggestions and there many more constantly being recommended here on Github. Currently, there are many DNS Server Suggestions that conduct logging or lack certain privacy practices.

Since you are recommending these on PrivacyTools.io, I'd suggest that any DNS Servers that don't meet basic criteria be removed.

Basic Criteria:
- DoH (DNS over HTTPS)
- DNSSEC
- No Logging 
- QNAME Minimization
- Open Source Code (Server)

**Comment by Mikaela** [comment]
> Currently, there are many DNS Server Suggestions that conduct logging or lack certain privacy practices.

Could you specify which ones?

> I'd suggest that any VPN Servers that don't meet basic criteria be removed.

I am assuming that you mean DNS.

> DoH (DNS over HTTPS)

DoH while being better for censorship, is worse for privacy/anonymity due to leaking more metadata. It's also more difficult to setup from what I understood, so I disagree.

* https://tools.ietf.org/html/rfc8484#section-8.2

> No Logging

This would remove 4/11 providers including 3/5 of our Anycast providers and combined with the DoH-only rule would only leave AdGuard which also does DNS level filtering potentially being undesirable to some users. We also don't have DNS server recommendations around the globe, while most of users wish DNS to be close to them, or they may fall back to Google DNS.

> Open Source Code (Server)

Judging by the current listing, only 4 servers would be left of which 1 is not using Cloudflare, so I think that list would promote centralization. (I am going to send a PR to make them more obvious)

* * * * *

I wouldn't remove any providers for now and as we currently have the only list of encrypted DNS servers that is focused on privacy, I hope we can set these standards on DNS providers and make the DNS providers mention these features instead of having users check them by themselves.

@privacytoolsIO/editorial thoughts?

**Comment by Mikaela** [comment]
Additional note after creating #1218: 5/11 of our recommendations are behind Cloudflare confirming my worry on decentralization, so I would be happy to include Snopyta #1207 and Nixnet #1206.

#1208 has a subdomain using Cloudflare (report-uri.lelux.fi) according to True Sight, but I wouldn't mind including it.

**Comment by Amolith** [comment]
> #1208 has a subdomain using Cloudflare (report-uri.lelux.fi) according to True Sight, but I wouldn't mind including it.

It's an NGINX reverse proxy to [Report-URI](https://report-uri.com). You can check it's a Hetzner IP address by running `dig report-uri.lelux.fi` and looking the output up with whois or something similar.

Lelux.fi isn't using Cloudflare for anything; you can check their nameservers by running `dig NS lelux.fi @a.fi` and it won't return anything malicious.

You can't even use Cloudflare with non-Cloudflare DNS if you aren't on a paid plan either: https://support.cloudflare.com/hc/en-us/articles/360020348832-Understanding-a-CNAME-Setup

**Comment by Mikaela** [comment]
Strange, I wonder why True Sight misdetected it. I think I will report it to them later.

**Comment by Amolith** [comment]
It's just due to the `cf-ray` not being stripped in the reverse proxy
