### ISSUE TITLE
Suggested Changes To "Encrypted Instant Messenger" section

### ISSUE THREAD

**Issue by ProgressiveArchitect** [privacytoolsIO/privacytools.io#1216]
In The Encrypted Instant Messenger section, I'd suggest "Wire" be moved to "Worth Mentioning" due to the service's server storing all metadata permanently and in plaintext.

Then Add "Briar" & "XMPP" to the main section next to "Signal"

This would provide a balanced recommendation
- Signal (Centralized)
- Briar (P2P)
- XMPP (Decentralized)

**Comment by Mikaela** [comment]
Page in question: https://www.privacytools.io/software/real-time-communication/#im

> I'd suggest "Wire" be moved to "Worth Mentioning" due to the service's server storing all metadata permanently and in plaintext.

What is the source for *permanently*? How does it differ from XMPP storing metadata on servers in plaintext?

I think Briar's Play Store release is still missing the support for remote contacts and I am not sure I would recommend it for it being Android-only and battery drain (like all P2P apps tend to be).

With XMPP, I think the problem is that we don't recommend protocols and it would probably need it's own section if it was promoted from worth mentioning. What are the apps that you would list? I have observed it to be very difficult especially on iOS and encrypted MUCs, even if it's still my preferred platform.
