### ISSUE TITLE
Android Private DNS: clarify Automatic vs Private DNS provider hostname (recommend the latter)

### ISSUE THREAD

**Issue by madosss** [privacytoolsIO/privacytools.io#1239]
hi guys,
is it safe and privacy friendly! to choose "Automatic" option in Private DNS on android 9 pie or should choose custom DNS?

![privatednsc](https://user-images.githubusercontent.com/54702660/64001788-d0423200-cb1d-11e9-83a8-6fff7660bcf4.jpg)

**Comment by dawidpotocki** [comment]
> is it safe and privacy friendly! to choose "Automatic" option in Private DNS on android 9 pie 

Secure? Privacy friendly? No. It will try to connect to your ISPs
DNS over TLS, if it will fail, it will fallback to using cleartext DNS.

> or should choose custom DNS?

Yes.

Next time I would recommend you to come to our Matrix chat
https://chat.privacytools.io, post on forum or subreddit.

GitHub is more for issues with website and not questions :).

**Comment by Mikaela** [comment]
To expand,

> Secure? Privacy friendly? No. It will try to connect to your ISPs
DNS over TLS, if it will fail, it will fallback to using cleartext DNS.

The automatic mode is also known as opportunistic mode and just means that it will attempt to form a DoT connection to any DNS server that it receives via DHCP, generally your ISP. If it succeeds at that, it won't validate the certificate leaving your DNS vulnerable to man-in-the-middle attacks. You can see whether you currently have a DoT connection by looking at whether the option says "Enabled" or "Automatic" (disabled) when you look at the previous screen-

Setting it to *Private DNS Provider hostname* will attempt to use the selected DNS server everywhere and if it fails to connect to it (due to a strict) firewall, Android will error about the hotspot not having connectivity.

* https://forum.privacytools.io/t/behaviour-of-android-9-private-dns-with-restricted-networks-and-a-quick-comparsion-of-dns-over-tls-providers-or-why-i-use-quad9/1088?u=mikaela

I think I am going to reopen this and made a small clarification to the website when I can.

**Comment by Mikaela** [comment]
Oh, I forgot to say that you may want to remove your screenshot as it shows the SSID that you are currently connected to and that may be turnable into your physical location.

* https://mikaela.info/blog/english/2015/11/29/SSID_optout_nomap.html

**Comment by Mikaela** [comment]
So I think the todo here is:

* [ ] clarify that Android 9 users should use *Private DNS provider hostname* instead of automatic
* [ ] document the two modes of DoT; Opportunistic mode & Strict mode

I just learned that FInland is having DNSSEC launch day next week and the report I saw on it wasn't very detailed and it didn't mention encrypted DNS at all and our DNS page (as this issue has noticed) leaves it unclear whether DoT is automagic without the user having to do anything and is it centralized (like DoH currently).

PR upcoming soonish.
