### ISSUE TITLE
AOKP Rom

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#126]
How do you feel about the AOKP rom?  Is it trustworthy enough as it is based on Cyanogenmod?

aokp.co  

anything comments are helpful here

**Comment by privacytoolsIO** [comment]
I'm surprised by the fact how many devices are support by AOKP: http://aokp.co/devices

**Comment by z751** [comment]
Actually that list is very old.  A more current list is available here:

https://basketbuild.com/devs/aokp

However the question is, are they trustworthy enough to list on the site?

**Comment by soaringowl2145** [comment]
They did remove CM stats from the rom.

**Comment by CHEF-KOCH** [comment]
AOKP is open source but more or less dead. The topic can be closed cause there will be no magical comeback, even if someone decided to pickup the code it's so far behind AOSP that you better start over with.

Custom ROM's are also more or less dead, and I'm not the only one telling this and there are multiple reasons why 1) OEM rom's getting better 2) Warranty 3) Google detects now custom roms and you might not receive Google Play Store Updates 4) No need to install a custom rom when you can do the same with Xposed modules 5) The argumentation that 'open source' ROM's are better is BS without proof, you can run into faked LineageOS downloads same like getting fake apps, updates etc. 6) Most people still using gapps because MicroG / NanoMod is crippled due the fact that some functions won't work (yet) or properbly never will 7) Most people don't give a shit about custom or not, they want to use the features, sadly some AOSP based roms have problems with that because they use old drivers which are crippled or partially working, as a result, video encoding etc are half-functional ...

**Comment by beerisgood** [comment]
@CHEF-KOCH the facts with custom ROM is wrong.:
1 Their not dead & OEMs dont got better
2 Most companys dont give a fuck about
3 Google itself provide the option to whitelist custom ROM so you can get playstore Updates
4 you cant get the status like LOS have with a stock Android, Not even with xposed
5 Just no. The updates are signed and checked before installed
6 Most users which use LOS use it because no gapps is wanted
7 isnt true. The opposite is

So please dont spread FUD

**Comment by CHEF-KOCH** [comment]
- Most custom roms's are dead, it's a fact since every custom rom is based on original AOSP. The ones which aren't based on AOSP are the ones which are on the sinking ship or they don't do thinks better than OEM's.
- This topic is about AOKP which is dead. It's not about YOUR opinion on 'most companies' which is also far away from been correct.
- Google provides a workaround, for now but you can be sure this will also come to an end soon or later. Root apps are already blocked which you only can 'unblock' with several xposed/magisk modules in order to cheat on google security mechanism, what they don't say it's that it might weaken your security since most things triggering sepolicy related things which then opens you device to several threats.
- You can get a lot with Xposed, for sure.
- Signed doesn't mean anything if you won't verify that the source where it's come is valid or not, we had the story with faked Linux Mint OS already.
- You can use custom roms's without gapps too, just deactivate or uninstall them. There is not much difference cause you need for both things room if you install another OS or root and then uninstall it.
- Yes most people don't give a shit about custom roms, look google's statistic, and then check statistics from custom roms e.g. LOS.

Please don't argue argument with me when it's obvious that you like to spread your opinion as fact which is horribly wrong. 

My points are valid and proven by several pages, stats etc. Even XDA had bigger articles that custom roms's are on the sinking ship. No one in his right mind by 1000 dollar phone and cripples it with LineageOS or a custom rom and break function which takes years to fix (if ever) .. but maybe in your world. 

Only reason why custom roms still exist is to get e.g. security or newer os on older phones which aren't officially supported anymore but that's the only valid point. However, the topic is about AOKP which is dead and a comeback will not happen.

Ref:
* https://forum.xda-developers.com/nexus-6p/general/custom-roms-slowly-dying-t3302455
* https://news.slashdot.org/story/17/01/22/2249241/do-android-users-still-use-custom-roms
* https://www.golem.de/news/android-alternativen-wo-sind-all-die-roms-hin-1612-124981.html
* proberly 1000 links more telling that custom rom times are over ....

**Comment by Atavic** [comment]
Most "recent" ROMS were released in 2017 (Huawei, Oppo).

**Comment by blacklight447-ptio** [comment]
looking at the devices supported, AOKP really does seem to be dead, closing issue.
