### ISSUE TITLE
🆕 Software Suggestion | Criptext

### ISSUE THREAD

**Issue by Rocknpools** [privacytoolsIO/privacytools.io#1287]
## Basic Information

**Name:** Criptext
**Category:** email service
**URL:** https://www.criptext.com/en/

## Description
Criptext is an encrypted email service based on the signal protocol. They claim no access to  emails nor store any emails in their servers.

**Comment by Atavic** [comment]
It's [open source](https://github.com/Criptext)

**Comment by dngray** [comment]
The answer is no: see [the post from the forums](https://forum.privacytools.io/t/which-domain-or-country-has-the-most-privacy/1811/14?u=dngray)

This one came up in the [privacytools.io AMA](https://reddit.com/comments/dn09g8/comment/f58od0c/).

> They mislead potential users by stating very odd and a bit contradictory statements e.g they say "*We don‘t have access to your emails nor do we store them in our servers.*" which isn't true, they have servers and those that were sent or received by other e-mail providers, the e-mails will be stored in their servers and their apps do in fact have API to their servers. Not to mention it's still in beta phase. Them claiming "*Quite possibly the most private email service — ever*" is very blunt and arrogant. Snowden stated:

> > [...] Email is a fundamentally insecure protocol that, in 2019, can and should be abandoned for the purposes of any meaningful communication. Email is unsafe. [...]
([Source](https://nitter.net/Snowden/status/1175437588129308672))

> Edit: To add to this, them saying "*No Cloud Storage*" and "*Decentralized Architecture*" is outright false and lie. If they go down, criptext will go down as well. E-mail protocol needs servers and eventually, whatever e-mail you send by it, it will go through their servers and then to other e-mail providers.

Essentially it comes down to it being [snake oil](https://en.wikipedia.org/wiki/Snake_oil_(cryptography)).

Also perfect forward secrecy protocols don't work with asynchronous communication like email anyway. They require a handshake, which is why things like PGP have persisted for email encryption. See [Op-ed: Why I’m not giving up on PGP](https://arstechnica.com/information-technology/2016/12/signal-does-not-replace-pgp/).

What Snowden is saying essentially comes down email having a lot of metadata in the headers of an email. For a [SMTP](https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol) relay (every mail provider has one and it is used when you send an email) to transmit a message from one mail server to another it must know things such as, who it was from, where it is going to, date, subject etc.

Even email providers like Protonmail and Tutanota cannot claim to keep this secure when sending email other email providers as they need to be able to process this information in order to work. They may be able to implement facilities to keep it secure at rest however (this only protects stored email not email being transmitted).

It's also worth noting this service centralizes email. Emails sent from criptext to other email providers **are not encrypted**, so this completely defeats the purpose.
