### ISSUE TITLE
Semaphor by SpiderOak

### ISSUE THREAD

**Issue by g-monk** [privacytoolsIO/privacytools.io#129]
I wanted to know what is the view of SpiderOak's Semaphor. Since Encryptr is a product by them featured, I think Semaphor should also be shared about.

**Comment by CHEF-KOCH** [comment]
Yet another IM, that's what we need, more un-audited IM's which claim things which they never can promise. I remember everyone got hyped when WA and Signal worked together to integrate axolotl protocol and other things, even the big co-operatorship didn't prevented several holes. 

So I wonder if it's wise to suggest young messenger without anything, no [whitepaper](https://spideroak.com/whitepapers/) nor an audit. Besides the price is relatively high, only the first 5 users are free, then better buy Threema Business (Threema Work) which is over long-term cheaper and this was audited and still get regularly audits.

The thing is also that over and over recommend other messenger doesn't solve the problem that person a uses e.g. WhatsApp while person b prefers Threema and person c uses this one here. None of them are compatible with each other.

In order to suggest new IM's with closed protocols, we should better relay on networks which are open source so everyone can build his 'own' IM around it and you would not break compatibility since they use the same protocol network. Matrix is such a promising protocol, it's open source, does support audio, video, is free and their several clients out there, it works on all operating systems and developers have a good documentation around the protocol so it's easy peasy to build secure messenger without breaking the compatibility aspect.

**Comment by Vincevrp** [comment]
Couldn't find the source code, so I assume it is proprietary.
