### ISSUE TITLE
[privacytoolsIO/privacytools.io] 🌐 Website Issue | Add more categories for Browser Add-ons (#1327)

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1346]
Restoring issue created by flagged GitHub account.

> ## Description
> Currently, we only have two types of categories for add-ons:
> 
> Improve your privacy with these browser add-ons.
> These addons require quite a lot of interaction from the user. Some sites will not work properly > until you have configured the add-ons.
> However, like I previously mentioned, certain extensions don't really fit in either definitions.
> Namely:
> 
> Terms of Service; Didn’t Read
> Snowflake
> Cookie AutoDelete (might have uses?)
> I think there ought to be a new category for these kind of extensions.

**Comment by blacklight447-ptio** [comment]
how about three categories:
Essential,Extra, and For power users?

**Comment by Mikaela** [comment]
I need to read the extensions through with a better time. I think I am a bit of disagree'er on Privacy Badger, so I don't think your categories would work as we would have disagreement.

**Comment by Mikaela** [comment]
## General

uBlock Origin: Block Ads and Trackers

Cookie AutoDelete: Automatically Delete Cookies

HTTPS Everywhere: Secure Connections

## Optional

Decentraleyes: Block Content Delivery Networks

Terms of Service; Didn’t Read: Be Informed

Snowflake

Privacy Badger: Stop Tracking - if you are fine with non-tracking advertisements and don't want to use a external blocklist. May complement your µBlock.

# Advanced

uMatrix: Stop Cross-Site Requests

NoScript Security Suite: Be in total control

**Comment by Mikaela** [comment]
My list above doesn't take into account https://github.com/privacytoolsIO/privacytools.io/issues/1292 the CSP handling, so it may contain incompatible ones, so I think #1292 should be thought about together with this.

**Comment by blacklight447-ptio** [comment]
I think this would be okay, ill try and make a pr for this this morning

**Comment by blacklight447-ptio** [comment]
@Thorin-Oakenpants so technically, if people want the affect they think they get with cookie auto delete, we should advice them to configure firefox to basically always use private mode?

**Comment by Thorin-Oakenpants** [comment]
No, because in PB Mode you have even less control over persistent local storage (designed that way: e.g you can't see or control cookies etc: or at least in the past you couldn't: not really interested in it TBH) - hence I said "start in normal window mode". And in PB Mode you can't use containers.

If you start in normal mode, then when you open a PB window (or several), that's a separate session where everything (I think) is memory only: and everything is sanitized when **all** PB Mode windows are closed. Then when you open a new one, it starts again.

You can basically achieve almost everything PB Mode does in normal window sessions anyway
