### ISSUE TITLE
More Darknet Mirrors (Tor, Freenet, ZeroNet)

### ISSUE THREAD

**Issue by BurungHantu1605** [privacytoolsIO/privacytools.io#139]
Hi Guys,

we already have a I2P mirror. Does someone have experience with Tor, Freenet and ZeroNet? It would be nice to mirror this GitHub repo in more darknets.

Help wanted! 👍

**Comment by Shifterovich** [comment]
Note: [fork for darkwebs](https://github.com/dark-mirror/privacytools.i2p)

**Comment by Shifterovich** [comment]
I can try to take care of this.

**Comment by Shifterovich** [comment]
Tor mirror set up.
I'm generating onion addresses.
So far:
```
ptoolsg6yhcioili.onion (current)
ptoolsdl67nwcg2u.onion
```

**Comment by Shifterovich** [comment]
@beardog108 has experience with ZeroNet.

**Comment by beardog108** [comment]
Yep, i'm getting a ZeroNet mirror setup. Will post here & on the subreddit when Its up. 

I will need people to help me seed.

**Comment by beardog108** [comment]
Currently generating a vanity address for the ZeroNet mirror.

**Comment by beardog108** [comment]
Alright, so i've got a fork up.

I couldn't get a vanity address to work for it, because for some reason it would not list the site in my client. I could probably get it to work by fooling around with it more, but i don't really feel like it.

You can access the site (assuming i'm still seeding) with your ZeroNet client & a browser here: http://127.0.0.1:43110/14gSEpfWfF5Go7u5y7UidZQCnGa6eSBYZ9/

**Comment by beardog108** [comment]
Next we should do Freenet & IPFS would be good too.

**Comment by beardog108** [comment]
Corrected the ZeroNet site 'home' button, as it would take you to your ZeroNet router rather than the top of the page.

**Comment by privacytoolsIO** [comment]
Hi guys, thank you both so much. I've added links on the website, subreddit and posted it to the zeronet subreddit already: https://www.reddit.com/r/zeronet/comments/5lwomw/privacytoolsio_is_now_available_on_zeronet_please/

**Comment by OverlordQ** [comment]
If you want a freenet mirror you'll need a stripped down version that doesn't rely on JS.

**Comment by Shifterovich** [comment]
Which along with "no one uses Freenet" is an argument not to support Freenet :P

**Comment by chris-barry** [comment]
Hey guys, I have one suggestion to make this lower friction for your users.

By default I2P does not know the mapping from privacytools.i2p -> wfewiqkdt5bvowfp3igmkaksjvcvwj7bag2smqpqyu5x4hges2qa.b32.i2p . If you make the link on your site:

" http://privacytools.i2p/?i2paddresshelper=?i2paddresshelper=wfewiqkdt5bvowfp3igmkaksjvcvwj7bag2smqpqyu5x4hges2qa.b32.i2p "

then a user won't have to go through the I2P jump servers. That special URL will tell the I2P router the mapping quicker.

**Comment by MuxZeroNet** [comment]
Hi, the title of the ZeroNet mirror can be changed via the sidebar. Drag the `0` button to the left to see the sidebar.

`Zcash.png` was missing. It might be forgotten. Try adding this file and sign the site again.

The site is running out of size limit (10MB). You can define optional files so that these files will not be counted when ZeroNet is adding up file sizes. Don't worry, once an optional file is requested by browser, ZeroNet will download that file immediately. Open `content.json` with a text editor. After the `modified` key, add an `optional` key with a regular expression string bound to it.
```json
"modified": 1483650296.648398,
"optional": "(fonts/.*)",
```
Save all of your changes and sign the site.

**Comment by Shifterovich** [comment]
The limit can be increased and Zcash.png is missing on privacytools.io too.

**Comment by Anonymous002** [comment]
guys pleasee give me hacking sites on tor

**Comment by Mikaela** [comment]
@beardog108 Are you still maintaining the Zeronet mirror? It seems to default to /classic, so I think it's a bit outdated.

**Comment by Shifterovich** [comment]
Since we now have an actual server, @JonahAragon and @BurungHantu1605 could set up all these mirrors?

**Comment by JonahAragon** [comment]
Probably yeah. We have Tor up, what other ones do we need? I’m not super familiar with darknets so I’m not sure what’s “in” right now.

**Comment by Shifterovich** [comment]
I2P and ZeroNet, in my opinion. Both are extremely simple to set up. I suggest using i2pd for hosting the I2P service. It's written in C, so it has a much lower overhead than the "official" Java I2P. Also you don't need all the Java I2P features to host a service.

**Comment by Mikaela** [comment]
From darknets I agree on I2P (even if I am not sure on I2Pd as I am having https://github.com/PurpleI2P/i2pd/issues/1275), I guess ZeroNet is currently "in" and I would also like to see [Yggdrasil](https://yggdrasil-network.github.io) (https://github.com/privacytoolsIO/privacytools.io/issues/685) even if it's more of a graynet and [IPFS](https://ipfs.io) (https://github.com/privacytoolsIO/privacytools.io/issues/139#issuecomment-270243582) even if it currently has no darknet support.

**Comment by TNTBOMBOM** [comment]
- Zeronet: is not made to be anonymous protocol as someone might imagine similar to hidden services: 

https://zeronet.readthedocs.io/en/latest/faq/#is-zeronet-anonymous

- Freenet: not well studied/matured like Tor and I2P, its decentralized data store (not newbies friendly) because it needs you to maintian storage capacity ,  its still poses danger of the copied unknown data when downloaded in the user space like malicious PDF or docs or so which freenet cant protect the user, written in java = SLOWNESS , You need to design the web to work with freenet because for e.g it doesnt allow JS .... 

- I2P-Java: Not good for Eepsites since it eats alot of resources , its still on the old days of monolithic design where everything put together whether you need it or not thats why you will find email client, built-in webserver (jetty) , Console comes with JS ...etc not good at least for eepsites.

- I2Pd: Written in C++ , lighter than I2Pj , and comes as a router only. (needs Terminal/UI configurations in order to switch your preferences), Suitable for Eepsites.

**Comment by blacklight447-ptio** [comment]
I think we should now make the decision : do we want to spend time and resources on mirrors on lesser used and known anonymity networks.

**Comment by 1000i100** [comment]
I would like to publish some static website on to .onion, freenet, zeronet and why not some other. Is there some tools to help doing this from my CI ?
PS : where should i ask this in a better place than here ?
