### ISSUE TITLE
🆕 Software Suggestion | Pop!_OS

### ISSUE THREAD

**Issue by TauSigma5** [privacytoolsIO/privacytools.io#1414]
## Basic Information

**Name: Pop!_OS**
**Category: Desktop Operating Systems**
**URL: https://system76.com/pop**

## Description
Pop!_OS is a highly user-friendly, secure and private Linux distro based on Ubuntu (with tracking and telemetry disabled). They're open source on github and developed by System76, a manufacturer of Linux laptops. They enable full disk encryption using LUKS during install. 

I think this should be on the OS list as an user-friendly replacement for Windows 10 for people who are new to Linux. Pop!_OS offers preinstalled NVIDIA drivers and stuff like that as well as the Pop shop. I saw it talked about in the sub and I think it should be on the OSes list. I feel most people are driven away from Linux due to how difficult it is to use (or rather how it's perceived as this way) and how it "doesn't look good".

**Comment by dawidpotocki** [comment]
> Pop!_OS is a highly user-friendly, secure and private Linux distro
> based on Ubuntu

I wouldn't call it more user-friendly than Fedora or Ubuntu, but I would
say that Ubuntu is more user-friendly, because it has a dock and desktop
icons.

> (with tracking and telemetry disabled).

You are asked if you want to send telemetry after installation, you can
check what it is going to send before doing it and data is public.
https://ubuntu.com/desktop/statistics

> Pop!_OS offers preinstalled NVIDIA drivers

Ubuntu starting from 19.10 does it too.

> and stuff like that as well as the Pop shop.

How is Pop Shop different from just normal repos with GNOME Software
Center?

> and how it "doesn't look good".

Pop!_OS theme is buggy. Adwaita and Yaru look amazing too.

**Comment by danarel** [comment]
Yeah, I wouldn't recommend listing it because then you're just in the business of listing Ubuntu versions. May as well list Mint then, which is really more user friendly than both.

I think just listing Debian accomplishes the goal of the site perfectly.

**Comment by Mikaela** [comment]
Blocked by https://github.com/privacytoolsIO/privacytools.io/issues/1370 and seeing how it's affiliated with System76, I think this can be considered together with https://github.com/privacytoolsIO/privacytools.io/issues/904 assuming System76 gets involved (hardware is not my cup of tea).
