### ISSUE TITLE
❌ Software Removal | IVPN

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1431]
Linda
IVPN concern:

Founded in 2009 by a group of security professionals at the prestigious Information Security Group at the University of London (Royal Holloway)

Company registered out of country.

ping ping ping @room 🔔

Do you want to discuss if IVPN should be removed based on that stupid Five Eyes criteria? UK is still in the EU and subject to GDPR though, right?
Also, regarding just that. IVPN doesn't even list their office address at all. Not in Gibraltar, and not in the UK.
That's also a requirement in the GDPR, list a data controller.
They do on the ToS page.

Privatus Limited
5 Secretary's Lane
Gibraltar
GX11 1AA
Gibraltar

https://www.ivpn.net/refunds

This might be anti-consumer? Only 7 days. It's 14 days minimum in my country. Need to check if that's on EU level...
IVPN Refund Policy
Refund Policy IVPN strives to meet the expectations of all new users and offers unlimited support to help users with any problems they may face in configuring the service. If however you are unsatisfied with the service for any reason whatsoever you can request a full refund within 7 days of your service being activated. In exceptional circumstances e.g. there is a technical issue which prevents
https://europa.eu/youreurope/business/dealing-with-customers/consumer-contracts-guarantees/consumer-guarantees/index_en.htm

14 days.

Consumer guarantees - Your Europe - Business
Learn more about your after sales responsibilities, returns, legal guarantees, commercial warranties, and customer claims.
Not sure how that's legal for IVPN to only claim 7.
Remove IVPN
🔔

Would someone please be my issue tracker relaybot? I don't use GitHub. ❤️

**Comment by dngray** [comment]
> Founded in 2009 by a group of security professionals at the prestigious Information Security Group at the University of London (Royal Holloway)
> 
> Company registered out of country.
> 

How is this an issue?

> Do you want to discuss if IVPN should be removed based on that stupid Five Eyes criteria? UK is still in the EU and subject to GDPR though, right?

I think we should remove the five eyes criteria as does @Jonah the reason is because it doesn't really add any protection whatsoever.

Would you trust China or Russia or some other oppressive regime more? It really comes down to whether the user is doing something that aligns with the views of the state.

I also wouldn't underestimate the five-eyes's ability to "pressure" other non member states to do things. Eg Ecuador and Jullian Assange for example. It really just depends on "how much they care".

Therefore it is just a better recommendation to recommend encryption wherever possible. At a minimum TLS ie HTTPS, but ideally [end-to-end encryption](https://en.wikipedia.org/wiki/End-to-end_encryption)

> Also, regarding just that. IVPN doesn't even list their office address at all. Not in Gibraltar, and not in the UK.
> That's also a requirement in the GDPR, list a data controller.
> They do on the ToS page.
> 
> Privatus Limited
> 5 Secretary's Lane
> Gibraltar
> GX11 1AA
> Gibraltar
> 
> https://www.ivpn.net/refunds
> 

Maybe we should send an email to them and ask them about it. I'd prefer this to "removing" an otherwise good provider.

> This might be anti-consumer? Only 7 days. It's 14 days minimum in my country. Need to check if that's on EU level...
>
> IVPN Refund Policy
> Refund Policy IVPN strives to meet the expectations of all new users and offers unlimited support to help users with any problems they may face in configuring the service. If however you are unsatisfied with the service for any reason whatsoever you can request a full refund within 7 days of your service being activated. In exceptional circumstances e.g. there is a technical issue which prevents
> https://europa.eu/youreurope/business/dealing-with-customers/consumer-contracts-guarantees/consumer-guarantees/index_en.htm
> 
> 14 days.
> 

Right, we should ask them about that then.

**Comment by JonahAragon** [comment]
I would personally close this issue in favor of #1437 being resolved but I'll leave it open in case either of you think something still needs to be discussed, feel free to close otherwise.

> This might be anti-consumer? Only 7 days. It's 14 days minimum in my country.

Usually businesses have a set policy and then make exceptions when their policies don't meet the minimum requirements of their customer's jurisdiction. So this would only be an issue if someone like Linda asked for a refund after 7 but before 14 days and they refused (which I doubt, but if we want to get in touch we can).
