### ISSUE TITLE
Cloudflare domain filtering

### ISSUE THREAD

**Issue by quarno** [privacytoolsIO/privacytools.io#1441]
Cloudflare is marked as non-filtering, while websites like archive.is or 8ch.net are blocked

**Comment by Mikaela** [comment]
Archive.is is misconfigured and blocking Cloudflare DNS and I wouldn't be surprised if 8ch.net is also blocking Cloudflare DNS due to the deplatforming.

* https://community.cloudflare.com/t/archive-is-error-1001/18227/3
* https://blog.cloudflare.com/terminating-service-for-8chan/

Please request reopening if you can show sources proving otherwise.
