### ISSUE TITLE
🆕 Software Suggestion | Buster: Captcha Solver for Humans

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#1482]
## Basic Information

**Name:** Buster: Captcha Solver for Humans
**Category:** Firefox addons
**URL:** https://github.com/dessant/buster

## Description

Suggested in Wire, I am not sure if we list the Privacy Pass either though

**Comment by beerisgood** [comment]
Doesn't block Google the sound option which the addon use ?

**Comment by Mikaela** [comment]
I am having difficulties parsing your comment, but as far as I am aware, the audio captcha option gets blocked by enabling `privacy.resistfingerprinting`.

I have no personal experience with the Buster extension.

**Comment by Mikaela** [comment]
There is a comment on the forum saying that it's possibly blocked by Google.

* https://forum.privacytools.io/t/two-small-questions-about-google-workarounds/2157?u=mikaela

**Comment by zenithium** [comment]
1. Buster relies on solving the audio CAPTCHA by using speech recognition. This option is not available to users that follow the browser recommendations and tweaks listed on the site.
2. From what I've seen the add-on can be inconsistent with solving CAPTCHAs regardless of browser settings.
3. I personally think that it doesn't affect the user experience in any meaningful way as most users can just click the audio CAPTCHA and solve it themselves in reasonable time. This might be useful to hearing impaired users but I don't know whether we should be catering to such a small minority.
4. This add-on is in no way related to privacy and does not fit in with the rest of the add-ons. Perhaps it might fit into some new section from #1346 but I'm assuming that all sections will be related to privacy in some way so it's probably still unlikely.
5. I fundamentally disagree with normalizing and automating CAPTCHA solving. The currently most popular CAPTCHA is Google's reCAPTCHA (with the slogan "Easy on Humans, Hard on Bots", I have no words to express how insultingly wrong this is) which is dehumanizing to the users: gaslighting them by intentionally giving vague pictures, failing correctly solved CAPTCHAs on purpose, giving users with hardened browsers lower scores which results in harder CAPTCHAs, taking 5 seconds to load ridiculously low-quality images regardless of bandwidth speed, etc. The more users are frustrated by this, the more likely something is to change. The current system has no semblance to it's original purpose of distinguishing humans from bots because humans can't solve these CAPTCHAs either.

The 5th point is less relevant than the others but I think it's appropriate to add it when discussing this topic.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
There's an add-on that replaces the "I'm not a robot text" with something more accurate, "I want to do unpaid image classification", I think it fits the task of completing reCaptchas alright.

I don't know if it's worth it to add an add-on that might not even work, I think something like this would be great while on Tor, since you get bombarded with those, but you can't add add-ons there, so...
