### ISSUE TITLE
❌ Software Removal |Nextcloud

### ISSUE THREAD

**Issue by claudiojulioferraz** [privacytoolsIO/privacytools.io#1496]
## Description

Nextcloud should be removed because end-to-end encryption is never working. They announced this function as it is still in alpha and in their repository development is stalled. Still they brag on their website for having end to end encryption.
[https://nextcloud.com/endtoend](nextcloud.com/endtoend/)

We need to find other software that has end-to-end encryption.

**References**
[https://apps.nextcloud.com/apps/end_to_end_encryption](https://apps.nextcloud.com/apps/end_to_end_encryption)
[https://github.com/nextcloud/end_to_end_encryption](https://github.com/nextcloud/end_to_end_encryption)

_Automatically translated_

**Comment by beerisgood** [comment]
Why not help them instead of create the wheel new again?
Nextcloud is still the best solution for many projects and also have a huge community which a lot of guys working on it.

Also E2E isn't all. It's nice feature, but that's all.

**Comment by claudiojulioferraz** [comment]
The problem is that they are not being totally clear. This is very suspicious, saying that it has a very important functionality when not. E It's been a long time. Who is stopping them from working on this technology?

[ https://nextcloud.com/endtoend]( https://nextcloud.com/endtoend)

_Automatically translated._

**Comment by beerisgood** [comment]
Also your comment is only valid for the files sync to Nextcloud, not for eg. https://nextcloud.com/talk/ which have E2E

**Comment by danarel** [comment]
The website you link to clearly says "Currently in testing phase"

I am not sure how that is shady? They are open about the fact they are testing this feature and make no claims anywhere to the contrary.

Secondly, on their website's main page the mention encryption once:

"Nextcloud products are designed with compliance in mind, providing extensive data policy enforcement, encryption, user management and auditing capabilities."

And that's not a misleading statement. They offer server side encryption.

I feel this request is making a mountain of what is not even a molehill because Nextcloud has not made claims to the contrary or hidden the fact that E2EE encryption is in testing.
