### ISSUE TITLE
privacytools.io site fails on mozilla obervatory

### ISSUE THREAD

**Issue by p43b1** [privacytoolsIO/privacytools.io#151]
The site privacytools.io gets an awful score on mozilla oberservatory

https://observatory.mozilla.org/analyze.html?host=www.privacytools.io

**Comment by Shifterovich** [comment]
Thanks. All the points we lost are because of headers. Not sure whether this can be improved, as we use CloudFlare. @privacytoolsIO can you add headers with CF?

**Comment by Vincevrp** [comment]
The website also has a bad score on [gtmetrix](https://gtmetrix.com/). Prehaps @privacytoolsIO can optimize some of these issues?

**Comment by Shifterovich** [comment]
Doesn't GH support HTTPS without CF now?

**Comment by Vincevrp** [comment]
> Doesn't GH support HTTPS without CF now?

It does but Github cache settings aren't optimal, I think you could better optimize it with CF. Though if CF is seen as a privacy issue, we'd be better of without it.

**Comment by nikhiljha** [comment]
GitHub's server also scores an F on observatory for similar reasons.

**Comment by JonahAragon** [comment]
>The website also has a bad score on gtmetrix.

Here you go.

![image](https://user-images.githubusercontent.com/3637842/55269515-518d5400-5262-11e9-9c36-038ec2030b42.png)

We also [score fine](https://globalsign.ssllabs.com/analyze.html?d=www.privacytools.io&s=104.28.22.220&latest) on SSL Labs. I don't *think* Mozilla Observatory is a big deal since we redirect to HTTPS, nor something that we can fix while on GitHub Pages.

We could probably consider implementing HSTS though.

**Comment by JonahAragon** [comment]
Fixed, we now score an A on Mozilla Observatory and SSL Labs.
