### ISSUE TITLE
🌐 Website Issue | Snowflake browser browser addon does not work with WebRTC set to 'fasle'

### ISSUE THREAD

**Issue by Bosch-0** [privacytoolsIO/privacytools.io#1522]
The Tor project Snowflake browser add-on does not work when you disable WebRTC in Firefox. I thought this would be worth adding as a note in the Web Browser -> Recommended Browser Add-ons -> Snowflake section of the site.

**Comment by hugoncosta** [comment]
Want to revive this issue. Snowflake isn't necessarily a tool that would help with an individual's privacy, it can even be construed as a redflag, since it's basically like creating a bridge on the person's computer for others to benefit. And as mentioned, it does that using WebRTC, a technology we tell people to disable. Thus I'd propose we remove it.

**Comment by blacklight447-ptio** [comment]
We actually aimed to split snowflake into its own little optional addon category, explaining that you will help people in oppresive countries connect to the internet anonymously, while explaining the personal privacy tradeoff.
