### ISSUE TITLE
🌐 Website Issue | Breadcrumbs don't respect capitalization of acronyms

### ISSUE THREAD

**Issue by djoate** [privacytoolsIO/privacytools.io#1551]
## Description
https://www.privacytools.io/providers/dns/: DNS -> Dns
https://www.privacytools.io/providers/vpn/ VPN -> Vpn

**Comment by Mikaela** [comment]
I had difficulties understanding this issue, but apparently the problem is in navigation.

![kuva](https://user-images.githubusercontent.com/831184/69914094-c267ba00-1448-11ea-823c-f25ef50f80de.png)

![kuva](https://user-images.githubusercontent.com/831184/69914101-cdbae580-1448-11ea-8012-f7de07f9061a.png)

**Comment by JonahAragon** [comment]
The reason for this is the breadcrumbs code takes the names from the permalink rather than the page title, and uses [capitalize](https://shopify.github.io/liquid/filters/capitalize/) to make it look better. This makes sense for some pages, for example https://ipv6.privacytools.io/providers/email/ shows the breadcrumbs as "Home > Providers > Email", and not "Home > Providers > Best Secure Email Providers for Privacy" (which IMO is not useful navigation or SEO-wise), but obviously doesn't work well for others.

We could have a breadcrumb attribute in the YAML front matter for each page to solve cases where the breadcrumbs would have conflicting titles like that, instead of trying to figure them out automatically based on the permalink. I'd imagine that's the best solution here.
