### ISSUE TITLE
🆕 Software Suggestion | Toffeeshare

### ISSUE THREAD

**Issue by wuniversales** [privacytoolsIO/privacytools.io#1650]
Name: Toffeeshare
Category: Share files (P2P)
URL: https://toffeeshare.com/

Use p2p technology to share the files.
No size limit.
Encrypted
Pretty easy to use.

**Comment by Mikaela** [comment]
And what makes them better or worth mentioning compared to our current file sharing section?

**Comment by wuniversales** [comment]
It's p2p, sent from the web, encrypted point to point, I think it's worth mentioning.

**Comment by LukeSeers** [comment]
### What I have discovered:

Their DNS points to [wolfined.com](https://wolfined.com)
`ns1.wolfined.com`
`ns2.wolfined.com`

From going by their logo "Development & Hosting" I'm going to assume that they are the ones who have made [toffeeshare.com](https://toffeeshare.com/).

Also: in their contact details on [wolfined.com/contact](https://wolfined.com/contact) they are from **The Netherlands** while also ToffeeShare is in the **The Netherlands** [twitter.com/ShareToffee](https://twitter.com/ShareToffee)

### What puts me off:

1.  They are not open source.
2. When they say "End-to-End encrypted" that is very vague. That is a trick which most companies use to make the product seem more secure. Since the users think that their information is encrypted on there servers, which in most cases they are not talking about that. They are talking about the connection from you to their servers which is also known as **HTTPS**.
3. "Peer to peer" that is really up for debate. If you understand how p2p works you would know that a user would need to connect to their server first to be able to connect to the other user directly. But since it's not open source we can not verify as easily if it is even p2p. One way is to check the connection between 2 users, but thats too much effort for me.

If they was todo **zero-knowledge** and they was **open source** I would maybe would give them a shot.

I thought I would chip in. I recommend double checking my research and coming to your own conclusion because we are human after all :)

**Comment by Mikaela** [comment]
Thank you for your comment @LukeSeers, I am not able to find the source code either and as there are (better) open source options for file sharing I am closing this issue.
