### ISSUE TITLE
🌐 Website Issue | Issue on erine.email

### ISSUE THREAD

**Issue by sakura974201** [privacytoolsIO/privacytools.io#1770]
Why was #1480 deleted?

**Comment by Mikaela** [comment]
As far as I can see, @privacytoolsIO doesn't have issue deletions enabled (I don't have access to settings to check it, but I don't see a delete button e.g. with this issue) and the account that opened the issue is 404 error so I can only speculate that they have deleted their account or GitHub has done that.

On erine.email itself, there was a comment by @beerisgood

> IPv6 problems, bad Security Headers, and bad website security itself.

* https://www.ssllabs.com/ssltest/analyze.html?d=erine.email
* https://securityheaders.com/?q=https%3A%2F%2Ferine.email%2F&followRedirects=on
* https://observatory.mozilla.org/analyze/erine.email

so I think at least at that time it didn't pass the requirements at that time. I haven't checked if that has changed.

* https://www.privacytools.io/providers/email/#criteria

**Comment by dngray** [comment]
> As far as I can see, @privacytoolsIO doesn't have issue deletions enabled (I don't have access to settings to check it, but I don't see a delete button e.g. with this issue) and the account that opened the issue is 404 error so I can only speculate that they have deleted their account or GitHub has done that.

I think you're right. In any case it won't be added as it does not meet the [basic security requirements](https://www.privacytools.io/providers/email/#criteria) of our email criteria: https://www.hardenize.com/report/erine.email/1583588375

1. No server suite preference
2. Insecure anonymous suites supported
3. Insecure key exchange detected
4. No MTA-STS, TLS-RPT or DANE support

**Comment by sakura974201** [comment]
I understand. Thank you very much.
