### ISSUE TITLE
Self Contained Networks 🆕 Software Suggestion | Peer to Peer Networks

### ISSUE THREAD

**Issue by Hxmwqk79** [privacytoolsIO/privacytools.io#1788]
I would like to suggest two early peer to peer networks:
Gnutella and BitTorrent
for worth mentioning in the Self Contained Network Category.

Gnutella was the first successful peer to peer hosting after the failure of Napster by not requiring a central server. Kent University called it pure peer to peer. BitTorrent needs no introduction.

Why:
You already mention ZeroNet but I suggest also having BitTorrent as it is much more secure not having JavaScript. Gnutella and BitTorrent just like FreeNet are highly significant peer to peer hosting for censorship resistance.

Edit: No one here seems interested in Gnutella.

**Comment by Mikaela** [comment]
Which clients would you recommend for Gnutella and BitTorrent? Why?

How do you balance the privacy of BitTorrent with its P2P nature?

**Comment by Hxmwqk79** [comment]
> Which clients would you recommend for Gnutella and BitTorrent? Why?
> 
> How do you balance the privacy of BitTorrent with its P2P nature?

Transmission client because it is trusted by the Linux community.
When transferring something sensitive, connect to BitTorrent through I2P.

**Comment by Mikaela** [comment]
Forum thread: https://forum.privacytools.io/t/section-for-bittorrent-clients/2978?u=mikaela

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
I think the best option for desktop is qBitTorrent, since it has some good security and privacy measures (I know there's an anonymous mode, although I don't know what does it do, and it supports encryption for different protocols) besides it's the most recommended client on /r/piracy.
A good android client would be LibreTorrent  although it might be dead, then there are some other interesting software for different tasks although i don't know how important it is to list them under PT.

On qBitTorrent anonymous mode: https://github.com/qbittorrent/qBittorrent/wiki/Anonymous-Mode
A web client: https://btorrent.xyz/
Both of these are used to  automatically organize downloads and I think you can also continue to seed after changing the files name:
https://github.com/Sonarr/Sonarr
https://github.com/Radarr/Radarr
Another client which I read about on/r/piracy, but I haven't look into it: https://rakshasa.github.io/rtorrent/

There are also android applications that allow you to handle your client remotely, that may be interesting, someone give some feedback on what's interesting to mention. 

----

Certainly routing your traffic through I2P is the best way, but you need to have I2P working, which is not as straightforward as using Tor.

**Comment by mehlon** [comment]
Torrenting over I2P is arguably pretty good privacy-wise. However it is so non-trivial to set up for a regular user that it's not suitable for PTIO. And then you'd still have access to a small subset of what clearnet torrents provide. If you still want to torrent over I2P then https://github.com/majestrate/XD is probably your best bet.
I think torrenting without a VPN or I2P is so dangerous with total strangers being able to find a connection between your IP address and a specific file or torrent, it probably shouldn't be included on PTIO either, except as a "Worth Mentioning". 
I think in terms of being both reasonably secure and usable [Tribler](http://tribler.org) (backwards compatible with BitTorrent) is probably best with anonymized seeding and downloading by default. 
See also https://github.com/privacytoolsIO/privacytools.io/issues/1687

**Comment by Hxmwqk79** [comment]
> Torrenting over I2P is arguably pretty good privacy-wise. However it is so non-trivial to set up for a regular user that it's not suitable for PTIO. And then you'd still have access to a small subset of what clearnet torrents provide. If you still want to torrent over I2P then https://github.com/majestrate/XD is probably your best bet.
> 
> Torrenting without a VPN or I2P is so dangerous with total strangers being able to find a connection between your IP address and a specific file or torrent, it probably shouldn't be included on PTIO either, except as a "Worth Mentioning".
> 
> I think in terms of being both reasonably secure and usable [Tribler](http://tribler.org) (backwards compatible with BitTorrent) is probably best with anonymized seeding and downloading by default.
> See also #1687

I like your comment. Maybe instead of listing BitTorrent separately we could just add XD I2P BitTorrent Client in the I2P description.

**Comment by lrq3000** [comment]
I agree that PTIO should be primarily focused on providing concrete privacy-friendly applications, not frameworks. So for sure there should be at least one software prominently displayed for each network. I don't know XD I2P BitTorrent but if it allows for an easy setup of both bittorrent and I2P and the bridging then that may be a good option (just need to ensure it's stable, there are lots of great softwares on paper but in practice they are not maintained or forever in a state of alpha). Also Tribler is nice, I was the one opening a ticket on PTIO about it, so I support the statement it's easy enough to use ;-) But it's important to note it has some limitations as noted in the ticket #1687.

**Comment by blacklight447-ptio** [comment]
i also agree that this may be a bit out of scope for our recommendations. plus if someone becomes interested in p2p networks, its often pretty easy to spot the most popular ones out there. closing issue.
