### ISSUE TITLE
🆕 Software Suggestion | Trace - anti fingerprint

### ISSUE THREAD

**Issue by Hxmwqk79** [privacytoolsIO/privacytools.io#1801]
I would like to suggest the Trace browser extension,
the feature rich anti-browser fingerprint extension,
https://github.com/jake-cryptic/AbsoluteDoubleTrace/
https://absolutedouble.co.uk/trace/
https://addons.mozilla.org/en-US/firefox/addon/absolutedouble-trace/

Trace is the best of the best for making Firefox anti-fingerprint-able. Compared to others like CanvasBlocker or Chameleon, Trace is very feature rich, and more exhaustive.

I am making this suggestion because browser fingerprinting, similarly to cookies and IP address, are the ways website are able to track you.

I had the honour of contacting the developer (email) to report 2 fingerprinting aspects Trace is yet to adequately defend against, CSS screen size (different from other screen size tests) and Character Sizes. I used the browserprint.info site to test and find these weaknesses. It was the most sophisticated browser fingerprint tester I've ever seen, but the website is since down. Github: https://github.com/CryptoCubik/browserprint

## My connection with the software
I am enthusiastic about the software as I was an early user and I want to spread the news as I believe it is a great project.

**Comment by beerisgood** [comment]
Using browser add-ons against fingerprint doesn't help as the add-on itself increase the fingerprint.
This need to be done at browser level and enabled by default so all user have same config instead of create your own, unique fingerprint

**Comment by Hxmwqk79** [comment]
> Using browser add-ons against fingerprint doesn't help as the add-on itself increase the fingerprint.
> This need to be done at browser level and enabled by default so all user have same config instead of create your own, unique fingerprint

There are two ways to resist browser fingerprinting. One, by having a common fingerprint (what you are referring to). And two, by spoofing and changing your fingerprint frequently (what Trace does).

I am suggesting Trace for privacy.resistFingerprinting doesn't give you a common enough fingerprint.

**Comment by Thorin-Oakenpants** [comment]
First of all, no disrespects to the developer: this is just my opinion, and I haven't really deep dived this extension, but I have looked at it a few times in the past .. and my conclusion is
- it's trying to do too much (jack of all trades and master of none)
- it doesn't do it well (AT ALL)
- it's not as exhaustive as you think (it only partially protects and only against some methods)
- and there are lots of little things that indicate a lack of "experience" (for lack of a better word), such as the giant huge interface, the gaudy gradient, etc
- I also don't like the presence of a premium option

So I installed it in practically a vanilla profile on Firefox Nightly, and immediately found several flaws without even looking very hard: here's some
- UA: service workers leak
- UA: the spoofed navigator properties are not plausible for Firefox (I only looked at FF)
   - the buildID is missing
   - the oscpu contains a fucking language string and is missing the OS architecture
   - the appVersion is the same ^^
   - the userAgent is the same ^^
- domrect
  - Element.getBoundingClientRect is not protected at all
- hardware
  - I can tell an extension is blocking VR devices
- screen resolution
  - leaks via matchMedia
  - without looking at the code (and I'm not going to), I can also tell via another method that it's a lie, because the extension is incorrectly changing values it shouldn't in one of my tests
- canvas
   - does not protect against isPointinPath
   - does not protect against isPointInStroke
- audio
  - OMG .. I turned on all audio protections and it didn't do anything AFAICT
  - it failed to protect getChannelData
  - it failed to protect copyFromChannel
  - it failed audioContext properties, OscillatorNode, DynamicCompressor tests

^^ all that in 10 minutes

I'm not even going to dig any deeper. It's all well and good to protect against some methods, but you need to protect against all of them. I'd hate to see what exactly really leaks in his canvas, webgl, domrect, audio. Because if he can't even get something as basic as navigator properties right, then I doubt the other measures are any good.

And to be frank (without changing my name), when I see protection for Battery listed, I just cringe. The Battery API has been inaccessible to web content since Firefox 52 - that's **over three years ago** [https://wiki.mozilla.org/Release_Management/Calendar](2017-March-07) - here's the [proof](https://bugzilla.mozilla.org/1313580)

I had a quick look at the repo: the dev seems to think he can block font fingerprinting (yeah, nah!). And I don't know why you would think he could block css screen leaks

There's so much more I could say, but let's just leave it at that.

tl;dr: I wouldn't touch it with a barge-pole ... social distancing and all

> I used the browserprint.info site to test and find these weaknesses. It was the most sophisticated browser fingerprint tester I've ever seen, but the website is since down. Github: https://github.com/CryptoCubik/browserprint

That's not very comprehensive or sophisticated, sorry. At least not any more. A lot of it is outdated. It's over 3 years old, and not maintained, obviously. A quick search would find you far more up-to-date scripts/demos

Not sure if you're sincere, or shilling. You account is rather new, and you have no github history. Maybe you're really into this and trying to help. But when you state that you rate something better because it has more features, I can't take you seriously.

I've actually had a lot of contact with the CanvasBlocker developer, and some contact with the developer of Chameleon - and those guys **know** what they're doing. More so than me: I know sweet F all, but even I could tell Trace wasn't any good practically just by looking at it: now I've actually installed it and given it a 10 minute spin, my assumptions were correct

PS: sorry if I sound like a prick

**Comment by dngray** [comment]
I hadn't heard of this extension before.

I very much value your extensive experience on issues like this @Thorin-Oakenpants

As a result we're not going to be doing further research on this. It won't be added.

**Comment by Thorin-Oakenpants** [comment]
Got some time to kill, feel free to hide as OT

https://old.reddit.com/r/privacytoolsIO/comments/g3khse/what_browser_extensions_are_you_using_in_2020/ - Hi BatmanMiner

> didn't like the UI

Stated as an **opinion** that possibly indicates something. I clearly separated sections of "initial thoughts" vs "so then I installed it and tested it and here are some results"

> The person admitted to using it for only 10 minutes

I only needed 10 minutes - it was also not an "admission" but a stated fact to show that so many issues could be found in such a short time

> And, you can tell the person is testing here [TZP]

Actually, you can't tell, you're only guessing. Oh .. here's some proof, if you care to look at the commits - the UA worker tests weren't even at TZP when I did this. For the record: I actually used this test - https://securehomes.esat.kuleuven.be/~gacar/dev/worker_test.html

Also, how is any of this relevant (unless the test is faulty, in which case point that out)?

> To address a few flaws brought up, UA service workers can be blocked using uMatrix

So what? How is that relevant? I can also disable JS on all sites - there, job done, everything is solved, no need for any JS fingerprinting leaks to be addressed by addons. But wait, what about sites you need workers, or JS ... relying on third parties to fix your own issues is not how you go about providing **real** solutions (bugs permitting: it's actually very hard to with the WE APIs to block this particular leak: and don't take that as "cool, it works then": because I think that UA spoofing is a complete and utter waste of time, even for RFP: and only good for some compat issues as a last resort)

> Spoofing all canvas data points is not required to change your global fingerprint

It depends on the script being used and the application of the spoof. If the application of the spoof leaks, then knowing if something is spoofed or not can be determined. Fingerprinting likes stability, and most scripts are generic (e.g. derived from fpjs2) and use the same techniques. But that doesn't mean smarter scripts and techniques aren't out there. In the science of FPing, if it leaks, it's a FPing hole that can be exploited. It's also worth noting that FPing can still be linked despite instability

Either you do it properly, or you're just creating a false sense of achievement. 

> Actually, the less spoofing, the better the change goes undetected.

Wrong. It makes it easier to fingerprint and increases FP stability

> but it's silly to throw it [Trace] out if a some are not yet resolved

*some*? It's practically everything I bothered to test. And I tested quite a few things (I'm fast), but not all. That's a high success rate for showing a consistent lack of application. I even read some of the github tickets: like audio spoofing not working - which others, like me, can reproduce: but the dev just shut it down as couldn't reproduce (from memory). The actual 100% failure of a protection is not **some** aspect, it the **entire fucking promise** he claims

> Tor, for example, does not resist or spoof fingerprintjs, even with safer settings

Yes it does. Not sure if that's a typo: fingerprints .. or fingerprintjs2 (common base script) - but those techniques/scripts are resisted.

---

Not to be confused with blocking an API, but for spoofing to lower entropy vs raising entropy (constantly randomizing) there are pros and cons to both, and they need to be weighed up depending on the fingerprinting method being attempted. Generally speaking, randomizing is much more complex (leading to more scope for leakage and code fuckups), and it creates information paradoxes which lead to far more breakage, and those paradoxes create yet more entropy.

Personally, I want to see more randomizing where appropriate. And I don't care if it can be detected as spoofing: as all TB/RFP users would be the same. Adding complexity to spoof the same value per session or domain or eTLD+1 or iframe/workers or CORS or Origin Attribute or whatever is a nightmare.

For the record: Tor Browser/RFP does use some randomizing. I don't want to go into it, but there are approximately eight different methods to handle FPing (in my model). You mentioned three (blocking, spoofing a common value = lowering, randomizing = raising). Come back to me when you work out the other five, and then we can talk.

Anyway: chill out Batman, but FFS, stop promoting Trace: it's shit, especially since superior, proven products exist.
