### ISSUE TITLE
🆕❌ Removal/cleanup 2.0 Real-Time Communication

### ISSUE THREAD

**Issue by dngray** [privacytoolsIO/privacytools.io#1835]
This issue is documenting some discussion in Matrix. The community may have noticed over the past year or so we've been really trying to improve the quality of our recommendations.

This is because we cannot in good consequence recommend experimental software.

This issue documents a number of changes which I plan to put in a PR:

1. It is finally time to de-list Tox. We've been monitoring this issue https://github.com/TokTok/c-toxcore/issues/426 and others and it is just hasn't progressed sufficiently enough.

One of the things we've observed with all our recommendations, is that documentation of the protocol is necessary for a robust design. When things are scary and undocumented developers aren't interested in joining a project. This hurts the momentum of the project and people lose interest.

2. Removal of Bitmessage

While commit logs seem to show some regular activity by the main project developer, the site indicates a stable release has not occurred since 2016. Also looks as if it depends on python2.

3. Elevating status.im and corrections.

It appears now that status.im does now no longer use the Whisper protocol, but rather a fork, called Waku, which is apparently more efficient. https://github.com/status-im/nim-eth/issues/123 there was also this article https://decrypt.co/25629/status-wants-to-be-the-worlds-most-private-instant-messaging-app it also looks as if they're going to publish in f-droid which would be good https://github.com/status-im/status-react/issues/8512

A previous issue the idea was not of high importance as it was considered too alpha-quality: https://github.com/status-im/status-react/issues/1125#issuecomment-298214111

It also looks as if it now no longer depends on Firebase https://github.com/status-im/status-react/issues/8742

They also seem they are interested in deterministic building https://github.com/status-im/status-react/issues/5587

Would require some testing.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
I know there's already another issue regarding Session, but since this one is about re-structuring the entire IM section I think this can be discussed here, too.

So far the conclusion around it on #1678 was that it wasn't mature enough on stability terms and that its "onion" network may not be robust enough, from comments of the developer made on that same issue, and from testing it heavily for a month now, I can say that it functions properly in both aspects, even more than other recommendations that are listed (Jami can't even send/receive text messages properly, for instance).

Regarding the publication of the application to F-Droid, you can read issue (https://github.com/loki-project/session-android/issues/73#issuecomment-604152774( where it is discussed, and the conclusion is that once that they have solved some multi platform bugs, that's going to be worked on. Almost a month ago @KeeJef commented this:
>Depends on how quickly we can fix up multi device, push notifications and message sending reliability, maybe a month or two?

According to SecureChatGuide if acomplish all security measures except that messages are temporarily stored on servers, but this also happens with Signal, so I don't think it matters since anyway they are encrypted. Regarding the trackers that were there when they tested it, they are now gone, you can see (https://github.com/loki-project/session-android/issues/118) for that. 

You mentioned Status, I'm trying it now and it looks great, but so far it is only available on mobile, and that's not really good if you think that there are people who may not want to use their phones for that, or simply because of functionality, so that's another point in favor of it.

So, am I missing something or why it can't be listed?

**Comment by dngray** [comment]
> You mentioned Status, I'm trying it now and it looks great, but so far it is only available on mobile, and that's not really good if you think that there are people who may not want to use their phones for that, or simply because of functionality, so that's another point in favor of it.

Yeah that isn't really great. Ideally a desktop client i think would be necessary. Session does look promising though, I suppose we could add it under worth-mentioning, and then elevate it in the future if things continue to go well.

**Comment by dngray** [comment]
> 3. Elevating status.im and corrections.
> It appears now that status.im does now no longer use the Whisper protocol, but rather a fork, called Waku, which is apparently more efficient. [status-im/nim-eth#123](https://github.com/status-im/nim-eth/issues/123) there was also this article https://decrypt.co/25629/status-wants-to-be-the-worlds-most-private-instant-messaging-app it also looks as if they're going to publish in f-droid which would be good [status-im/status-react#8512](https://github.com/status-im/status-react/issues/8512)

It's worth mentioning this is now in F-Droid https://github.com/status-im/status-react/issues/1125#issuecomment-800897200

https://f-droid.org/en/packages/im.status.ethereum/
