### ISSUE TITLE
Adding Wire as EU-based encrypted Messenger

### ISSUE THREAD

**Issue by cityroler** [privacytoolsIO/privacytools.io#186]
Hi guys,
I have seen your website and it gives a great overview about all the tools to make life a bit more private. 👍🏻
But I was wondering about people should not use a US-based service but recommending Signal. What about adding Wire? It offers fully E2EE, audio- and videocalls, is open source, Swiss based and development center in Berlin, Germany with servers in the EU and works on iOS, Android, Windows, macOS, Linux and Web.
Disclaimer: I work at Wire. More about how we respect and protect users privacy: www.wire.com/privacy

**Comment by Shifterovich** [comment]
+1 for the disclosure (and because Wire is pretty awesome).

**Comment by qazip** [comment]
So? Is wire going to be added or not? There was a discussion here: https://www.reddit.com/r/privacytoolsIO/comments/5vr10k/adding_wire_as_eubased_encrypted_messenger/ and the consensus is that Wire should be added.

**Comment by Shifterovich** [comment]
Create a PR.

**Comment by mat1th** [comment]
@Shifterovich Hi, I've created a PR to add Wire to the list. Could you review it?

**Comment by mat1th** [comment]
Wire is now on the site. So this issue could be closed;

**Comment by jancborchardt** [comment]
@cityr0ler since you say it’s open source, did the Wire server get fully open-sourced too? Last I checked and talked to ppl from Wire it wasn’t completely open source yet, and also https://github.com/wireapp/wire-server#wire-server says (emphasis mine):

> This repository contains the source code for the Wire server. **At the moment it contains a subset of the libraries and services used by Wire.** We will keep releasing more libraries and services over time as we finish cleaning up and documenting the source code. Our goal is to publish the source code of the entire Wire server.

@Shifterovich @kewde especially since on the website you specifically advise against using apps like Telegram (which does the same thing: apps »open source« and server closed), this is important to know. The point being that if the service shuts down, Wire becomes useless.


Disclaimer also from me: I work on [Nextcloud](https://nextcloud.com/) and we operate in a similar field (collaboration & communication). But especially since that’s the reason we forked from Owncloud we care a lot about open source and 100% doing it (AGPLv3+): https://github.com/nextcloud/server/

**Comment by Shifterovich** [comment]
We discourage Telegram because of bad crypto.

**Comment by jancborchardt** [comment]
Ok, that's beside the point though. ;) Wire is not fully open source (the crucial part is not) but privacytools.io advertises it as such.

**Comment by teller** [comment]
@jancborchardt All Wire server code is now released, looks like the readme file needs an update though.

**Comment by jancborchardt** [comment]
@teller ah that's awesome, great to hear! Any blog post about that, or some other publication/documentation? :)

**Comment by teller** [comment]
https://medium.com/@wireapp/wire-server-code-now-100-open-source-the-journey-continues-88e24164309c
