### ISSUE TITLE
Consider dropping or moving stateless password managers

### ISSUE THREAD

**Issue by graysonkent** [privacytoolsIO/privacytools.io#187]
See article here: https://lwn.net/SubscriberLink/715090/e426fd5aff3e366d/

I'm not sure if you guys advocate for the most secure way or just low hanging fruit for most people, but if it the former then I think that Keepass+Addon should at least be moved to the first position. Thoughts?

**Comment by sevengali** [comment]
Agreed with this. Another article about it: https://tonyarcieri.com/4-fatal-flaws-in-deterministic-password-managers

BitWarden seems quite popular for online storage of passwords.

**Comment by g-monk** [comment]
I suggest why don’t we add the new sources and tell about the “flaws” as keep in mind safety measures. This is because in the recommendation for Wire, on the site it tells the company keeps a record of people you chatted with.

However, I feel like we should also have a stable recommendation, because I use Encryptr by SpiderOak, but because it was removed, I am now having to decide which one works the best. 

Granted that softwares and going decentralized to all forms is a bit of a challenge but a stable pick or recommendation can help with the goal of - easy to use, decentralized and meeting the original criteria.

**Comment by Vincevrp** [comment]
Master Password was moved to "Worth mentioning" in  #587.

**Comment by Shifterovich** [comment]
It's the same with LessPass. The issue with these password managers:
- not as secure, each password is based in your master password which some people don't like as they see that as a potential attack vector
- your master password being leaked results in all your passwords being leaked.

> I think we should recommend local password managers as the secure ones and stateless password managers as a less harmful alternative to one password for less important websites.

**Comment by beerisgood** [comment]
Yeah. Set KeePass as best solution and add cloud solution a warning label
