### ISSUE TITLE
Remove Mailfence

### ISSUE THREAD

**Issue by reportingforduty** [privacytoolsIO/privacytools.io#230]
Reasons

1. There is no monthly plan. All you can do is buy yearly plan(only choice).
2. They don't do any refund(remaining funds*). They will ignore your emails related to refund.
3. They will ask you for a reason, you answer it, and they never reply to further emails.

I call this a scam.

*
THIS IS A TRUE STORY. If you don't believe me, waste your money; just try it.

Let's say you use 4 months and decided to move to other provider.
You wrote an email about canceling your subscription AND request a refund (there is NO WAY to remove your credit card on website).
Wait 1 week and they will tell you about "customer satisfaction".
Wrote another email, and wait more days.
This time they told you that no further payment will be made to your card.
(They never delete your card information.)
And 1 day later, they will ask you "why you want to get a refund". (this is funny because I already told them that I don't use their service anymore <- primary reason)
You reply to them.
NO REPLY NOR MONEY RETURNED.

**Comment by reportingforduty** [comment]
Here's another victim story which [I found on reddit](https://www.reddit.com/r/ProtonMail/comments/5eqoyr/protonmail_vs_mailfence_any_opinions/);

> I had *requested Mailfence support for a refund* almost immediately after signing up.
> They asked me to use the service for a few days and then *if I'm not happy, they'll refund me*.
> Just a few hours later, after messing around with Mailfence and reading your post about incoming
> 2FA and third-party client support, *I emailed them again to go ahead with the refund*.
> They didn't respond in four days so I emailed them again yesterday. *Still no response*.
> *I have filed a dispute with my credit card company*.

If someone have reddit account, do me a favor - please post this github issue to reddit so other people can notice this.
I want my money back. This scam site should not be on the PrivacyToolsIO list.

**Comment by ocdtrekkie** [comment]
If it's clearly stated on their site they don't offer refunds, it's not a scam. They offer service on a yearly basis, according to you, which means when you buy, you buy for a year. If you decide not to use all the service you paid for, isn't that your problem?

**Comment by PatrickDeSchutter** [comment]
Dear reportingforduty,

We are terribly sorry you have had a bad experience with Mailfence and apologize for the unsatisfactory customer support follow up. We did an investigation following your post and did indeed not offer the level of customer support that we wish to give. In addition, your last mail was indeed not answered and we will take care of that.

However, as stated by ocdtrekkie, we do not promise 'money-back' or refund.
The reason for this is that we allow prospective users to test our application for free. The free subscription comprises all major functionalities of the paying ones, also the digital signing and encryption functionalities.  We thus believe there is no need for 'money-back' policy because anybody can test our service as long as they want before opting for a paying subscription.

This does however not excuse our bad follow-up of your refund request. We did not get back with a direct no to your request because in certain cases, where we did not deliver a function that was clearly promised in our site or blog, we have been doing refunds. This is not a general policy however.

Finally, Mailfence is clearly not a scam. It is a service launched by ContactOffice, a company active since 2000 offering private label collaboration and messaging tools. We have always put customer satifsfaction as our primary goal and duly regret your bad experience.

Respectfully,

Patrick
Co-founder Mailfence
