### ISSUE TITLE
Fix VPN list

### ISSUE THREAD

**Issue by haroon-ali** [privacytoolsIO/privacytools.io#232]
Hi,
The VPN list need some fixes.
1. One Item has no website or service name. Just this " 	$ 39.95 	Yes 	48 	Seychelles" ???

2. cryptostorm.is doesn't offer a free trial while it's listed counter-wise.

3. AirVPN.org doesn't have a real free trial on signup it's a contact form. Actually most of the service providers, by personal experience, - if not all - would be provide some free trial period if you contacted them. I found it meaningless.

**Comment by haroon-ali** [comment]
Also;
4. azirevpn is listed as "no trial" while it has free 24h trial.

**Comment by 3k2** [comment]
Also cryptostorm isn't from Iceland.. their website might be .is but they are hosted at Germany and they don't say anywhere they are from Iceland..

in interviews they say

> 2. We’re a decentralized project, with intentional separation of loosely-integrated project components. We own no intellectual property, patents, trademarks, or other such things that would require a corporate entity in which ownership could be enforced by the implied threat of State-backed violence; all our code is published and licensed opensource.

[As an example torrentfreak interview](https://torrentfreak.com/vpn-services-anonymous-review-2017-170304/)

and Perfect Privacy is not from Panama they are from 

> 2. Perfect Privacy is registered in Zug, Switzerland.

Also in the torrentfreak article..

But it's hard to tell because their website says following [Look here](https://www.perfect-privacy.com/imprint/)

**Comment by Atavic** [comment]
https://github.com/nylira/prism-break/issues/1520#issuecomment-247194357

**Comment by Vincevrp** [comment]
Seems to be fixed in the meantime.
