### ISSUE TITLE
Suggestion: Add a new VPN list

### ISSUE THREAD

**Issue by KhalidVIP** [privacytoolsIO/privacytools.io#266]
Hi

Some people can not buy through the currency bitcoins, so we have to add a new list that accepts payment by Visa or MasterCard by the rules set in the past ... etc

 The end is just a suggestion

**Comment by Atavic** [comment]
But in this way you're giving your real name to the VPN.

**Comment by dnguyen01** [comment]
As for a VPN list, that probably wouldn't change, since I believe all of the VPN providers accept usually Bitcoin, prepaid cards, and credit cards. Now just like @Atavic mentioned, if you are want true anonymity while buying the VPN service, you will have to use Bitcoin or buy a prepaid Visa (in which no name is associated or phone number). Or if you wish to mask your CC number to your VPN only, you might want to look into using a Virtual Visa number. Though, I'm not sure about who provides this (outside the US that is; I know of Privacy.com & Albine Blur but both US based).

All in all, it depends on what your mission is.

**Comment by kewde** [comment]
I don't recommend using credit cards to buy VPNs. I don't think a new list for this is a good idea..

**Comment by Shifterovich** [comment]
> I don't recommend using credit cards to buy VPNs

Depends on threat model.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@Atavic 

> But in this way you're giving your real name to the VPN.

The VPN already knows his IP either way.

**Comment by Shifterovich** [comment]
Not necessarily.
