### ISSUE TITLE
Stress that the Tor Browser should be used as much as possible 

### ISSUE THREAD

**Issue by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [privacytoolsIO/privacytools.io#273]
This is already done by a related project: https://prism-break.org/en/subcategories/gnu-linux-web-browsers/

>
> Try to use Tor Browser Bundle (TBB) for all of your web surfing. It will offer you far better anonymity than any other browser. Make sure to learn the basics of Tor before using it. If the site you want to visit will not work in the TBB, try Firefox intead, but realize these browsers do not anonymize your ip by default.
>
> TBB notes: Using the TBB to sign into websites that contain your real ID is counterproductive, and may trip the site's fraud protection. Make sure to check for HTTPS before signing in to a website through Tor. Signing into HTTP websites can result in your ID being captured by a Tor exit node.

Where should this be? Also I can tweak the above paragraph and add additional details into why using Tor for most browsing is a good idea and how by using it one helps others get more privacy.

**Comment by Shifterovich** [comment]
TPB is a high-value target when it comes to finding vulnerabilities in browsers.

You obviously shouldn't use TPB *only* for suspicious activity, but should generate some random noise as well. Also it's based on FF which is less secure than Chromium.

VPNs should be used as much as possible and we should explain how to use Tor properly. I will write a tutorial on using anonymity tools like Tor properly soon.

**Comment by privacytoolsIO** [comment]
#276

**Comment by Shifterovich** [comment]
I agree it should be the first browser we commend, but still am not sure how much should we stress using it.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
> TPB is a high-value target when it comes to finding vulnerabilities in browsers.

Chromium has the same status if you consider its crushing market share. I don't see what your point is here.

> VPNs should be used as much as possible and we should explain how to use Tor properly.

By that you mean that VPNs should be used as much as possible instead of Tor?

**Comment by Shifterovich** [comment]
HVTs use Tor, not Chromium.

And yes, you should definitely generate random noise with Tor even when not using it (if you intend to use it for something serious later), but using Tor as much as possible makes little sense.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
> HVTs use Tor, not Chromium.

My point was that even if Tor Browser was based on the most secure browser (Chromium) then a similar argument would conclude that Chromium shouldn't be used.

FWIW an example of good practice for HVTs with the Tor Browser: When you visit TheIntercept's SecureDrop (https://y6xjgkgwj47us5ca.onion/), if JS is enabled they put the warning: `We recommend turning the Security Slider to High to protect your anonymity: ...`

> And yes, you should definitely generate random noise with Tor even when not using it (if you intend to use it for something serious later), but using Tor as much as possible makes little sense.

Tor is 1/n anonymity network, as such, using Tor as much possible can only make sense since it's not just about protecting oneself but also others.

And just to clarify, by as much as possible I mean: 

+ For all websites with active content or that require logging in that block Tor (if some news site blocks Tor then the correct way would be to find cached version of it, or to use online proxies with websites such as https://searx.me or https://startpage.com ).
+ For websites that require identifying information such as bank websites.
+ For websites that require APIs disabled in the Tor Browser, such as websites that require WebVR...

**Comment by Shifterovich** [comment]
Logging in to a non-HTTPS website over Tor is a very bad idea. Using Tor for most of your browsing sacrifices a lot of usability, yet I can't see a single positive thing about it.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
@Shifterovich 

> Visiting non-HTTPS websites over Tor is a very bad  idea.

Unless it's because someone is logging into HTTP websites over Tor. Otherwise I don't think it's a bad idea, especially with higher security settings i.e. Medium or High.

> Using Tor for most of your browsing sacrifices a lot of usability,

Examples?

>  yet I can't see a single positive thing about it.

The whole "make covert traffic" (traffic analysis aspect) + "the bigger the crowd the easier it is to hide in it" (fingerprinting aspect).

**Comment by Shifterovich** [comment]
There are other ways to generate noise without having to use Tor for all browsing.

> Examples?

Low speed and a lot of things don't work in Tor.

**Comment by CHEF-KOCH** [comment]
It depends on what you’re trying to access and who you are trying to remain anonymous from.

* [Tor Network has it's own security problems](https://en.wikipedia.org/wiki/Tor_(anonymity_network)#Weaknesses).
* Some pages simply can block tor Browser so you can use Tor all day long it doesn't help if the site you like blocks it
* VPN can also same like Tor restricted, Netflix is a good example, you get flagged and then you can't watch anything
* Tor is only designed to prevent simple network-level eavesdropping and does not protect your anonymity against nation-state level adversaries. There are several types of attacks that can be carried out by timing traffic patterns to de-anonymize users. Mix-networks and Noise-networks are technologies that can be implemented to improve this, but require more computation and power than most users are willing to pay for.
* Downloading or watching Youtube is pain in the ass.
* Disabling JavaScript, Flash and Java already lowerrs 80% of all possible attacks. 


EFF has [several guides](https://ssd.eff.org/en#index). I find such information more valuable rather than listing only tools/VPN's/Providers because not everything is automatically secure by default or needs some adjustments and some hints and warnings, like no matter what encryption you use when someone is in the same room and copy & paste your text and leak it, it doesn't help. So, people should be aware what they post on the internet and what should be avoided. I think that are some basics which also applies for the Tor Network.

**Comment by blacklight447-ptio** [comment]
We now have a big explanation on our VPN provider page which describes the difference between vpns and Tor, including their usecases, which makes this issue no longer needed, closing.
