### ISSUE TITLE
Suggestion: WebRTC 

### ISSUE THREAD

**Issue by Jasper-Ben** [privacytoolsIO/privacytools.io#298]
Since the Website is also directed to users who lack in depth knowledge about the technical details I would suggest adding some more context to the WebRTC section. Otherwise those people following the guide might disable it and wonder why e.g. hangout, jitsi or similar isn't working.

Also followup question: The chrome section mentions that there only is a plugin that is easily circumvented. Is this only the case with this specific plugin or is the same problem present in other (firefox) plugins? So far I've been using https://github.com/ChrisAntaki/disable-webrtc-firefox for webRTC control.

**Comment by C-O-M-P-A-R-T-M-E-N-T-A-L-I-Z-A-T-I-O-N** [comment]
IIRC (tested one year ago) uBlock has that same problem in Firefox.

**Comment by Shifterovich** [comment]
Can't WebRTC be disabled completely in about:config?

**Comment by Jasper-Ben** [comment]
@Shifterovich It can. But from time to time I want to use WebRTC (e.g. for my selfhosted jitsi instance) without going through the hassle of enabling it in the about:config. The plugin mentioned above gives the possibility to enable/disable it with one click. So I was wondering if this is a widespread problem affecting multiple plugins.

**Comment by Shifterovich** [comment]
Ah. Well, we should definitely do some research as the claim about the Chrome extension may not be true anymore.

**Comment by Atavic** [comment]
Firefox and its forks can block WebTRC into [about:config](https://privacytoolsio.github.io/privacytools.io/#webrtc) or with addons.

Google Chrome has WebRTC built into the application. Alternatives:

Ungoogled Chromium modifies Chromium to eliminate these APIs, see:
https://github.com/Eloston/ungoogled-chromium/issues/179

[Unofficial Google Chromium](http://chromium.woolyss.com/) builds with No Sync • No WebRTC • No Widevine

**Comment by Datenschutz** [comment]
uBlock origin also has a setting that disables the IP leak created by WebRTC if that's what you're looking for

**Comment by CHEF-KOCH** [comment]
Chrome will get a feature to block insecure channels or the original stun to avoid any leaks even if you use a build with webrtc or in case you use official builds.

![webrtc](https://user-images.githubusercontent.com/727123/38247181-93ae4cd4-3744-11e8-950e-83d184caffe4.png)

So the options are as following:
* Don't use A Browser with WebRTC 
* Use a Browser with an option to disable WebRTC like Opera (Chromium tweaked Browser)
* Use Chromium build (unofficial) without WebRTC 
* Compile Chrome/Chromium without WebRTC flag `enable_webrtc = false`
* Start Chrome with `--disable-webrtc-encryption`
* Use uBlock/Nano Adblocker (uBo based) in order to block WebRTC connection via addon

Ungoogled Chromium is basically a Chromium fork which is behind other inofficial forks without any benefit. Why Google makes some random connection even if you disable everything is well explained in the Chromium bugtracker, but I can tell you in short. The connections are done in order to detect if you're behind a proxy / VPN or not so that the Browser quickly can decide if you're on a limited, fast or proxy connection. This applies also on mobile devices and comes same like on Windows (WPAD) from the OS (in Android called capital portal login checks) and some other fancy feature names to determine if you near home or not, this, however, has nothing to do with spying or tracking. The 'ungoogled' chromium people are 100% not experts otherwise they would have mentioned it. 

If there doubts I also willingly to search for this bug entry but I guess it was this one [here](https://bugs.chromium.org/p/chromium/issues/detail?id=795526).

**Comment by Hillside502** [comment]
For "capital portal login checks" read "captive portal login checks"

**Comment by blacklight447-ptio** [comment]
@thorin-oakenpants we also need to take note of this for the rewritten about:config section.

**Comment by Mikaela** [comment]
I think this may still be relevant as I don't think the new about:config came yet, assigning @blacklight447-ptio and reopening just in case.
