### ISSUE TITLE
Why is Tomato not listed in 'Open Source Router Firmware'?

### ISSUE THREAD

**Issue by GETandSELECT** [privacytoolsIO/privacytools.io#300]
Hey
thanks you guys for fantastic privacy resources collection.

I wonder why [Tomato](https://advancedtomato.com/) is not listed in 'Open Source Router Firmware'?

The same [question popped up on Reddit](https://www.reddit.com/r/privacytoolsIO/comments/38owio/tomato_router_firmware/) two years ago.

**Comment by Atavic** [comment]
It supports a few routers. OpenWrt/LEDE supports many more, see: [lede-project](https://lede-project.org/toh/start) vs [tomato](http://www.polarcloud.com/tomatofaq#what_will_this_run_on)

**Comment by 2E0PGS** [comment]
Tomato is a great WIFI AP and router software for the old series of WRT54G and more:
"Linksys' WRT54G/GL/GS, Buffalo WHR-G54S/WHR-HP-G54 and other Broadcom-based routers".

Yeah it maybe limited to the WRT line but there are a tonne of them out there. So I think its coverage is quite decent. I personally own 5 or so WRT54 devices. They are even manufacturing them again due to demand!

I would list it if it was me. Plus people maybe going back to using older routers due to modern backdoor hardware microcode.

**Comment by Atavic** [comment]
I would list it, too. All those projects that fork official router firmware are great. My previous comment was simply an opinion, maybe biased as I see few buffalo products on stores - I live in a EU country.

**Comment by Vincevrp** [comment]
[Quality over quantity](https://github.com/privacytoolsIO/privacytools.io/blob/master/.github/CONTRIBUTING.md#software-criteria), but it might worth mentioning?

**Comment by Atavic** [comment]
As long as the project is active, it's definitely a candidate for one of the three mentions or for a link on *Worth Mentioning* section.

**Comment by GETandSELECT** [comment]
development of Tomato derivates was long time not active. Now FreshTomato (new derivate) release regularly new builds. See http://freshtomato.org

I personally like very much Tomato based Firmware, but I an not an expert.

**Comment by JonahAragon** [comment]
https://github.com/privacytoolsIO/privacytools.io/pull/942#pullrequestreview-242576999
