### ISSUE TITLE
Add Containers to Firefox Privacy Add-ons

### ISSUE THREAD

**Issue by groovecoder** [privacytoolsIO/privacytools.io#341]
Now that [Containers is available on AMO](https://blog.mozilla.org/firefox/introducing-firefox-multi-account-containers/), [the Containers collection](https://addons.mozilla.org/en-US/firefox/collections/jkt/container-addons/) should be added to the Firefox Privacy Add-ons section. (Particularly, Multi-Account Containers and Containers on the Go)

**Comment by Atavic** [comment]
AMO page not found, containers options are into the browser.

/*** [SETTING-56+] Options>Privacy & Security>Tabs>Enable Container Tabs
[SETTING-ESR] Options>Privacy>Container Tabs>Enable Container Tabs ***/

**Comment by Atavic** [comment]
AMO page not found, containers options are into the browser:

[SETTING-56+] Options>Privacy & Security>Tabs>Enable Container Tabs
[SETTING-ESR] Options>Privacy>Container Tabs>Enable Container Tabs

**Comment by groovecoder** [comment]
Oops, the collection went away. Here's the link straight to the add-on on AMO: https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

**Comment by Mikaela** [comment]
I think this depends on https://github.com/privacytoolsIO/privacytools.io/issues/1327

**Comment by DF2NwasJiMYLNFyAOQarZtfPPj0qXh4G** [comment]
Perhaps consider Temporary Containers [1][2]. Firefox only, like multi-account-containers.
Listed on ghacks user.js extension list [3].

[1] https://github.com/stoically/temporary-containers
[2] https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/
[3] https://github.com/ghacksuserjs/ghacks-user.js/wiki/4.1-Extensions/44f04f0e2c32d88b3ce8b3f1e78ba6d42b2a9742

**Comment by stoically** [comment]
Just wanted to mention that Temporary Containers is a viable alternative (or complement, if you use permanent containers as well) to Cookie AutoDelete, since [almost all storage and cache](https://wiki.mozilla.org/Security/Contextual_Identity_Project/Containers#What_is_.28and_isn.27t.29_separated_between_Containers) is covered by containers and hence removed after the tab is closed - while cookie cleaners rely on manual API calls, and as of yet aren't able to clear some of the storage reliably.

Disclaimer: I'm the author - feel free to ask if there are any questions.

**Comment by smnthermes** [comment]
I don't think containers are useful if the user has others extensions properly configured (uBlock Origin and uMatrix). Let's not fall into marketing traps and incentive users to bloat their browsers with add-ons.

**Comment by stoically** [comment]
uBlock Origin / uMatrix aren't Data-Cleaners - without dedicated Data-Cleaners storage is persistent and lets e.g. the same first party domain easily recognize users on repeated visits. More details on that are here: https://github.com/stoically/temporary-containers/wiki/Comparison

Add-ons *can* increase fingerprinting, correct. Containers however don't really have an detectable surface, since they're basically "profile per tab/container", which isn't detectable in itself.
