### ISSUE TITLE
What is the significance of the colors (green, blue, yellow)?

### ISSUE THREAD

**Issue by gene1wood** [privacytoolsIO/privacytools.io#368]
I searched the page itself and then all open and closed issues for a legend or something explaining the colors but found nothing.

What is the significance of the color coding? I see most sections have 3 suggested solutions colored green, blue and yellow. What do the colors indicate?

If this is already called out somewhere and I just wasn't able to find it (search terms of color, green, blue and yellow on the page and through the repo) I'd recommend highlighting it better as it's hard to find.

If it's not, do please communicate somehow on the page what the colors are meant to indicate to the reader.

**Comment by sim-s-singh** [comment]
If you're talking about reccomendations and not lists (ie. what OS not the list of VPNs), I'm pretty sure that the color does not have anything to do with anything, other than aesthetics.

**Comment by gene1wood** [comment]
Ya, recommendations like [this one](https://screenshots.firefox.com/OoMFnIf1mdAqBWZu/www.privacytools.io).

If the colors are arbitrary that may be a bit confusing (was for me) as they're used consistently, ordered the same way, and have common associations with good, something and warning.

**Comment by Shifterovich** [comment]
> and have common associations with good, something and warning.

There are many tools that are very good, but some are (slightly) better than others. And recommending just one tool is not a good idea. It's just aesthetics, but helps when unsure which option to choose. A good example is the [PC OS](https://www.privacytools.io/#os) section. Debian is good, but Qubes is great.

**Comment by gene1wood** [comment]
So is the intent for green to mean "this is your best option", blue to mean "this is your second best option" and yellow to mean "this is your third best option"? If so, we should definitely indicate this somehow as this gradient is not clear.

**Comment by Shifterovich** [comment]
It's not always the case, it's really more of a matter of aesthetics.

**Comment by tasn** [comment]
I agree here, I also find the colours very confusing.

I assumed it was just a matter of aesthetics but no matter how hard I tried to ignore it, the third (yellow) option always felt like it's not as good as the rest.

**Comment by Shifterovich** [comment]
That's often the case. You sometimes need to show that some tool is way better than the others.

**Comment by woctezuma** [comment]
I have been using the website for a while and it never occurred to me that the colours meant something.

I thought it was just some random design. Part of the reason is that it is always (green, blue, yellow) from left to right. I would have imagined that if colours meant something, then there would exist ex-aequo of the same colour on the same row.

For most of the cases, it makes sense a posteriori, except for the password manager. I find it strange that the preferred solution is not KeePass, but an algorithm which generates password without any randomness. Imagine that your "master password" is known, then you have to change every password on every website. In contrast, with KeePass, even if your "master password" is known, people cannot do anything without the "database file", which is stored locally ; you would just change the "master password" which encrypts the "database file" and that is it.

![password managers](https://i.imgur.com/NiBI6nn.png)

**Comment by gene1wood** [comment]
> It's not always the case, it's really more of a matter of aesthetics.
> That's often the case. You sometimes need to show that some tool is way better than the others.

I still believe that a color scheme that in some cases is used for aesthetics and in other cases is used to convey an order of preference causes a poor user experience.

I really think that either it should convey a preference and this should be stated on the page, or no preference should be conveyed and the colors should be removed/changed to avoid confusing users.

**Comment by Shifterovich** [comment]
My point was that usually it's about preference but sometimes it's hard to say that some tool is way superior to the other tools. **Generally**, green is the best one.

**Comment by Mikaela** [comment]
Is there a legend on the webpage? I never noticed the colours either.
