### ISSUE TITLE
Suggestion: Passward Manager - BitWarden

### ISSUE THREAD

**Issue by amdelamar** [privacytoolsIO/privacytools.io#376]
I think [bitwarden](https://bitwarden.com/) should be listed under Password Managers [here](https://www.privacytools.io/#pw). 

For privacy features I know:

* Its open-source on GitHub https://github.com/bitwarden
* You can self-host your own server
* Master password + 2FA (also FIDO U2F, Yubikey, and more)
* Encryption via PBKDF2 AES 256bit

Maybe @kspearrin can elaborate a more on the privacy aspect of bitwarden over other competitors.

**Comment by dittaeva** [comment]
I think a comment on this is warranted. None of the current three suggestions will replace the most common password manager LastPass, but BitWarden can (and is designed to). Master Password relies on you remembering site address and username, KeePass is not in the browser (unless you install extra software with the usability advantages and security disadvantages implied), LessPass seems to be essentially the same as Master Password, and there seems to be several others like it.

I am not saying BitWarden deserves a place among the three, but from the descriptions it does seem to warrant place no. 3 more than LessPass. But then again maybe LessPass is a better choice for number 1 as it has syncing for complex passwords.

**Comment by beerisgood** [comment]
I never got why you guys need a password manager in Browser. And if this isnt bad enough, its in Cloud.  
I cant recommend both

**Comment by Primokorn** [comment]
@beerisgood Multi-users, multi-devices, multi-platforms.
Easy to use for everybody.
I use Bitwarden since it has been introduced by Kyle (Bitwarden's dev) on Reddit.

**Comment by beerisgood** [comment]
@Primokorn: KeePass can do that too. Even without a browser.
Of course the program is needed then

**Comment by swr7hr** [comment]
I would like to put forward Bitwarden again to be added to the password managers on privacytool.io.

To build apon the reasons already given, here are mine:

1.  Being able to self host is a great feature and I can use  my Bitwarden through bitwarden app
2.  While KeePass is also open source, it uses Google Authenticator which [no longer is](https://www.reddit.com/r/Bitcoin/comments/3fkmvi/using_google_authenticator_app_for_2fa/). 
For Bitwarden, I use (and would also recommend) [FreeOTP](https://lwn.net/Articles/581086/) so it remains open source.
2a. Trust in Google (and others) around [privacy and rights](https://www.techrepublic.com/article/why-passage-of-sestafosta-is-leading-some-cloud-providers-to-terminate-users/) has gone right down due to FOSTA
3. The support provided by Kyle is really good. He is quick to get back and provide help and keep it evolving.
4. I am not saying it should replace KeePass but it seems to be giving it a run of its money and [winning](https://www.slant.co/versus/2824/19421/~keepass_vs_bitwarden).
5. On privacy tools.io's [reddit](https://www.reddit.com/r/privacytoolsIO/comments/7vtrqm/keepass_vs_bitwarden_vs_enpass/), followers have also tested and liked Bitwarden.
6. They just released a [desktop app](https://www.ghacks.net/2018/03/01/bitwarden-desktop-app-released/) for those who want it.
7. The iSO app can be used with self hosting.

Even if its a mention, they seem to be hitting more rights than most. I also did a check on the site this time too. 
https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fvault.bitwarden.com%2F 

Thanks for your time.


Just a Privacy Fan - Not a Developer

**Comment by ProgressiveArchitect** [comment]
Bitwarden is a fantastic project with a lot of potential to overtake Keepass & KeepassXC from a User Interface perspective. It just has a much better GUI and has a dedicated app for most platforms out there with the ability to self host. The potential to host on Bitwarden's cloud is a big negative but is end to end encrypted which you can prove due to the client being open source. 

However, I don't believe privacytools.io should be recommending Bitwarden until it has has a Independent Third Party Security Audit. Once it has had one and passes, Then I think it has earned a spot on privacytools.io recommended list.

Most of the users who follow privacytools.io are already using Bitwarden and can verify it as a very good Password Manager.  But regardless, It still needs a proper Security Audit.

**Comment by Shifterovich** [comment]
Can anyone create a PR?

**Comment by Vincevrp** [comment]
@Shifterovich I can implement this. Which place should it take in the recommendations?

**Comment by Shifterovich** [comment]
Seems like it's cloud-based but with client-side encryption? I personally use KeePass and LessPass, I've never used Master Password. I'd replace either Master Password or LessPass, since they both do the same thing. That way we will have all 3 types there.

**Comment by Vincevrp** [comment]
I suggest:

1. LessPass
1. KeePass
1. Bitwarden

**Comment by Shifterovich** [comment]
I agree, use whatever order for LessPass and KeePass to make it aesthetically pleasing (I suspect the LessPass color will work great with `primary`).

**Comment by Vincevrp** [comment]
Okay, I will implement this. You can assign me to this issue.

**Comment by kspearrin** [comment]
@Vincevrp This repo might help: https://github.com/bitwarden/brand

**Comment by Shifterovich** [comment]
@Vincevrp I can't assign non-collaborators unfortunately. Nevermind. @kspearrin thanks.

**Comment by Aquakor** [comment]
To be honest this is the first audit that I've ever gave a quick glance. I guess 11 identified problems is a low number. But the conclusion is kinda worrying for me.

> On a less positive note, the assessment of the deployed cryptographic design led to the discovery of certain issues that must be addressed in due course. One was rated “Critical” because a malicious vault could obtain and modify organization items. This approach relied on MitM attack described in BWN-01-008. The overall code quality of the crypto implementations was deemed to be overly complex and frequently misleading, which led to reporting a false positive issue (see BWN-01-011). More generally, cryptographic libraries of the Bitwarden compound have not yet been optimized. They particularly need to be simplified as unnecessary complexity can lead to problems.

> Given the number and range of issues discovered, it seems necessary that a re-design takes place. This needs to reassess how certain features are implemented and ensure that the overall cryptography stands strong against the attackers’ efforts.

**Comment by kspearrin** [comment]
@Aquakor I am the lead developer of Bitwarden and was intimately involved in the security audit mentioned. I can understand that those two paragraphs may seem a bit concerning out of context. To provide more context, there were several points discussed between the Bitwarden developers and the auditing team about how we could redesign specific features so that the crypto implementations would be stronger and more resilient against certain attack vectors. A consensus was reached and that is what is being referenced here about re-designing things.

The purpose of an audit like this is to find issues. When issues are found, that is a good thing. We want to find problems so that they can be fixed. What would be bad is if we found issues that could not be fixed, or an abnormally large number of issues, neither of which was the case with Bitwarden. What I can tell you is that all issues referenced in this audit have been resolved in very short order (the audit was only completed just last week), with relatively simple fixes, and that Bitwarden is ever safer to use today than it was before.
