### ISSUE TITLE
Add osalt.com to Tools Section

### ISSUE THREAD

**Issue by 0verk1ll** [privacytoolsIO/privacytools.io#392]
osalt.com is a website similar to Alternative-To, but it only lists open-source alternatives to apps. This website makes it easier for people to find safe apps since closed-source alternatives are not suggested.

**Comment by Hillside502** [comment]
Here's why **not**:-

- https://www.osalt.com/ is unmaintained/discontinued.  Just because the Let's Encrypt certificate (automatically) renews every 3 months, doesn't mean otherwise.

- It's riddled with trackers
`google-analytics`
`googlesyndication`
`hotjar`
`quantserve`

- `apis.google.com` is used in such a way that it's also a tracker

- The last RSS feed post was nearly **eight** years ago

alternativeTo is very useable.  Just select Open Source in the License filter on any search.

Plenty of trackers there as well --- but then again, alternativeTo doesn't project itself otherwise.

**Comment by Atavic** [comment]
Commenting Hillside502 comment above: **Sad !!**

A site like osalt, but updated, is so needed IMHO.

**Comment by Hillside502** [comment]
Updating my comment above:-

- alternativeTo now has just 3 trackers, not "plenty" as I said previously
`googlesyndication`
`googletagmanager`
`viglink`

- the site improves daily (not least because of my contributions)

- IMHO, best to focus input there --- and, of course, **use the Open Source filter**
