### ISSUE TITLE
Tool suggestion: Write.as

### ISSUE THREAD

**Issue by fartattorney** [privacytoolsIO/privacytools.io#397]
Don't know if this would go better under Productivity Tools or Paste Services, but [Write.as](https://write.as) is a privacy-oriented blogging platform / nice looking pastebin.

* It's [cross-platform](https://write.as/apps) (iOS, Android, Windows / Mac / Linux with command-line, Chrome OS)
* Some clients and core code is [open source](https://github.com/writeas)
* Good [privacy policy](https://write.as/privacy)
* Publishes a [warrant canary](https://write.as/canary.txt)
* Runs a Tor hidden service: writeas7pm7rcdqg.onion

What does everyone think?

**Comment by 0verk1ll** [comment]
* It is very useful because you can post anonymously without creating an account.
* If you create an account, you only need to give a username and password (an email address is optional).
* There are paid options available, so write.as makes its money from subscriptions rather than selling our info to third parties.

**Comment by Shifterovich** [comment]
Create a PR.

**Comment by BurungHantu1605** [comment]
We're hosting it now: https://write.privacytools.io/
