### ISSUE TITLE
[Suggestion] Riot.im

### ISSUE THREAD

**Issue by g-monk** [privacytoolsIO/privacytools.io#411]
Hello everyone. I was wondering what are your thoughts on Riot.im. It’s a open source, has End to end encryption, video calling, chat and file transferring available as well. ![Image](https://i.imgur.com/UyxmtBr.jpg)

More info can be found on their website at: https://about.riot.im

**Comment by Atavic** [comment]
https://github.com/privacytoolsIO/privacytools.io/issues/220
https://github.com/vector-im

**Comment by g-monk** [comment]
@Atavic I see that you linked #220 and posted a github link. However what does that all mean? I’m not able to make sense out of it. Plus I am new in making contributions to the project, but I certainly would like to help and take part in this movement, so please guide me into understand what this means as I am a total rookie.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Atavic** [comment]
Welcome!

1st link is a similar issue (still open) and the 2nd one is the official organization page...

I should have written: *Related to* the 1st link, while the official page gives opportunity to ask in one of the repositories there, or eventually call someone involved in the project into this issue.

**Comment by CHEF-KOCH** [comment]
Vector IM exclude the Jitsi part which means no Audio & Video support. I see this not as alternative or preferable compared to the original Riot Client, besides the web-matrix client which works in every browser doesn't need any installation at all.

Matrix itself provides a version without the Jitsi part, but I heard that will be removed in order to move on.

![csv](https://user-images.githubusercontent.com/727123/38246114-faf39a2e-3740-11e8-9261-75ad82cc418c.png)

Considering this means there is no need for alternative clients since there is no benefit, the tracking argumentation is pointless since you can a) opt-out yourself b) the data which are been collected don't compromise you in any way ... You can read what they collect and verify this within the source code and on their official homepage.
