### ISSUE TITLE
Consider Cyberghost

### ISSUE THREAD

**Issue by c0rdis** [privacytoolsIO/privacytools.io#421]
Looks like all the criteria from https://www.privacytools.io/#vpn are met.
https://www.cyberghostvpn.com

**Comment by Hillside502** [comment]
In the top right corner of https://www.cyberghostvpn.com it gives my location as Sweden and shows my IP address, then goes on to say "EXPOSED".

I don't think so --- I'm connected to a competing **VPN** and --- guess what --- I'm not in Sweden.
The only conclusion is --- wait for it --- Tossers!

**Comment by c0rdis** [comment]
For the record - I'm not affiliated with them in any way, and I'm not even their customer. Yet the argument "they showed me I'm exposed on their main page when I used some other VPN, so this product sucks privacy-wise" doesn't sound valid to me.

**Comment by Hillside502** [comment]
So, when I'm connected via a **VPN**, am I "exposed" or not?

**Comment by Atavic** [comment]
You're exposed to the VPN Provider.

**Comment by Shifterovich** [comment]
VPN providers' websites say you're exposed when they detect an IP that doesn't belong to them. They don't know that you're using a different VPN. If you want to see if/how exposed you are, ipleak.net.

**Comment by CHEF-KOCH** [comment]
Exposing the IP is nothing that can't be fixed, most of the time the VPN provider needs to fix their configuration. [I wrote about this here](https://chefkochblog.wordpress.com/2018/03/30/vpn-providers-which-leaking-your-real-ip-due-webrtc/), my article also includes the latest research on one, particularly case: WebRTC.

Is cyber ghost reliable vpn?
I do think so, since there one of the bigger VPN players around here.  But I#m not sure if the project needs more recommendation on which providers are reliable because there are already several charts out there and they already showing the important things what you need to know. I guess [TheOnePrivacySite](https://thatoneprivacysite.net) is the most known one.

Instead of mention explicit providers I suggest to mention the charts and explain what to look at so everyone can choose their own provider, this is in my opinion more 'objective' than picking random providers and say 'these are the secure ones' which is mostly not or not entirely true, as said it's not that the provider is BS just because there is maybe one open hole, instead I suggest to contact them in order to close the hole.

**Comment by NeverDucky** [comment]
> In the top right corner of https://www.cyberghostvpn.com it gives my location as Sweden and shows my IP address, then goes on to say "EXPOSED".
I don't think so --- I'm connected to a competing VPN and --- guess what --- I'm not in Sweden.

@Hillside502 to be fair other providers do that too, [such as NordVPN](https://nordvpn.com/) which is currently on the list. It's just a rather presumptuous way of displaying that the user's current exit node does not belong to the provider.

**Comment by Hillside502** [comment]
https://www.cyberghostvpn.com/
Your Status: EXPOSED

https://nordvpn.com/
Your Status: Unprotected

https://trust.zone/
YOUR PROTECTION IS POOR!

All other Privacy Tools recommended VPNs give no such **misleading** banners!

**Comment by Shifterovich** [comment]
That's just marketing, and while it is misleading, it's not too bad when you know why such statuses are shown.

**Comment by c0rdis** [comment]
That's precisely my understanding of the issue.

**Additional links to support the initial proposal:**
EU-based: https://www.cyberghostvpn.com/en_US/about
Logging policy: https://support.cyberghostvpn.com/hc/en-us/articles/213898965-Does-CyberGhost-log-No-
OpenVPN support: https://support.cyberghostvpn.com/hc/en-us/articles/213983829-Which-native-protocols-do-you-support-
Bitcoin payments: https://blog.cyberghostvpn.com/en/pay-anonymously-with-bitcoins/

**Comment by Hillside502** [comment]
> That's just marketing, and while it is misleading, it's not too bad when you know why such statuses are shown.

So, we're going to give credence to "misleading" marketing?

**Comment by NeverDucky** [comment]
We already do with NordVPN and trust.zone as you showed. Are you proposing a policy change? Currently such "misleading marketing" is not criteria for being listed on the site. For that matter, FrootVPN, hide.me, NordVPN, VPN.ht, and VPNTunnel are marked as "falsely claims 100% effective" on [thatoneprivacysite.com](https://thatoneprivacysite.net/vpn-comparison-chart/). Should those be removed too?

**Comment by NeverDucky** [comment]
There is a similar issue going on in #72 where there is hesitation to add a new VPN provider to the list due to a controversy despite the issue being present in VPN providers already on the list.
I agree with @CHEF-KOCH that it's important to let the reader decide on a VPN provider on their own, but I think the point of the **list we maintain is to give the reader a good starting point**. To that end I think either Cyberghost (and VPNArea from #72) should be added because they meet the criteria and the reader should be able to consider them as such, or we should re-evaluate the criteria and remove offending providers. This is to maintain integrity and accuracy, which simply not adding them because some may see it as "pointless in my opinion" fails to do.

**Comment by NeverDucky** [comment]
I also agree with @Shifterovich when they say 
> If we removed every single VPN that isn't perfect, we'd be left with an empty list. The technical side is way more important.

So I think we should add both VPN providers and if we happen to later come to the decision to change the criteria, remove them at that point.

**Comment by CHEF-KOCH** [comment]
I partial agree in this, however, I think giving the reader a starting point should get some rules, maybe max 3 or 5 applications listed and the same amount of 'alternatives' but we shouldn't discuss every single new application/VPN etc with the same '_stupid_' arguments over and over. It's simply a waste of time for all of us.

That's imho the reason why I prefer to explain people in the first place what's going on so they can check themselves the software/provider they find on the net, this also reduces the annoying discussions if product x or provider y is trustworthy.

Moreover, I think it might be helpful to (based on findings/leaks) list or show providers which are known as 'problematically' with a notice or explanation if that is fixable or if the provider is aware of it or not, otherwise people coming in here saying 'hey I use your listed program x here but what you say is garbage cause it's fixed'.

I think some criteria must be written down to address this.

**Comment by NeverDucky** [comment]
It's also worth noting that below the VPN providers list there is a second set of criteria that is different than the first:

   - Operating outside the USA or other Five Eyes countries.
   - More: Avoid all US and UK based services.
   - OpenVPN software support.
   - Accepts Bitcoin, cash, debit cards or cash cards as a payment method.
   - No personal information is required to create an account. Only username, password and Email.

At there very least there appears to be some inconsistency that should be addressed. Maybe we should open a new issue for this.

**Comment by g-monk** [comment]
I as a beginning contributor and someone who has to study this, would say from a user stand point that regardless of what you add or don’t add. The pros and cons should be briefly explained. I posted here like a year or so ago, that I will be translating the website and making it more user friendly, however even at times I’m stumped on how to explain things. Now keep in mind that this is just to break down net privacy for beginners like me who are yet to learn of this stuff and are just stepping in the field.

**Comment by CHEF-KOCH** [comment]
The law is not really relevant, once the provider guarantee or prove that they zero-knowledge, etc is given no law/gov. can get the data since it wouldn't be possible (in theory). The fact that every country has it's own agencies, and that some of them working together makes a VPN not better once it's located in a country which is 'official' not under any surveillance. Every country 'logs' and the traffic goes over 13 DNS root servers around the world and some major 'nodes', They still can duplicate your traffic and crack it later once they found an exploit, weakness etc. That some agencies or governments don't give any shit about laws in their country is also well known. Remember when the NSA director told a lie that NSA did not collect any data around the world (after the Snowden leaks revealed they did).

The argumentation 'use an VPN service/server which isn't located in country x' is a horrible wrong. We know since Snowden they want your data from all over the world. On this matter, I say once again that people should get the points which identity which makes a VPN secure or not. This is in my opinion only partially given. 

The real points are:
* Which encryption or options do the provider give
* Are there any leaks (fixed / unfixed).
* Is the provider aware of known problems and are the things like WebRTC fixable.
* Does the provider offers a source code to it's clients or backend which shows zero-knowledge or other mechanisms in order to hide data from it's government/developers etc
*  Are there any audits, papers, documentation given which are reasonable 
* Does the provider offers openvpn support (which is known as 'more secure' than others).
* How does the provider handles your data/logins etc. Do they sell data etc?
* How is the support, how does it handles upcoming threats etc?

Again the myth about five eyes, six eyes or 1 billion eyes etc. is wrong together with other myths, which says that because there is a possible hole that's automatically insecure - cause most things are fixable some providers are not even aware of certain things and once you email them they fix it or change it if it's really security relevant. 

There will be always upcoming and unknown threats and it's more a thing how the VPN provider handles it. I think this with the zero-knowledge and source argumentation are the strongest one.

**Comment by blacklight447-ptio** [comment]
we are currently not looking to add more VPN providers. this issue will be closed with the possibility of being opened again once we remove another VPN provider.

**Comment by nitrohorse** [comment]
> we are currently not looking to add more VPN providers. this issue will be closed with the possibility of being opened again once we remove another VPN provider.

We recently removed cryptostorm from the VPN providers list so maybe this is worth considering again if anyone is interested.
