### ISSUE TITLE
0bin vs zerobin

### ISSUE THREAD

**Issue by kewde** [privacytoolsIO/privacytools.io#454]
https://0bin.net/ and https://zerobin.net/
both use the same source code, yet zerobin.net provides an onion domain (http://zerobinqmdqd236y.onion).

Perhaps we should consider swapping them?

**Comment by infosec-handbook** [comment]
Some facts for comparison:

**https://0bin.net/**
– uses outdated(?) nginx 1.1.19 (released on Apr 12, 2012), jQuery, Bootstrap
– Let's Encrypt RSA cert (2048 bits), expires in 5 days
– supports TLSv1.0, TLSv1.1, TLSv1.2
– weak DH parameter (1024 bits) for key exchange
– no CT, no OCSP Must-Staple, no HSTS, no CSP, no X-Content-Type-Options, no X-Frame-Options, no X-XSS-Protection, referrers leaked
– not listed on hstspreload.org

**https://zerobin.net**
– uses CloudFlare's WAF, jQuery
– COMODO ECDSA cert (256 bits), valid for dozens of different domain names, expires in 169 days
– supports TLSv1.0, TLSv1.1, TLSv1.2, TLSv1.3 (draft 23)
– sets 1 Cookies (missing SameSite flag)
– no OCSP Must-Staple
– not listed on hstspreload.org

**Comment by kewde** [comment]
@Shifterovich

**Comment by kewde** [comment]
@infosec-handbook 

Please run the same analytics for the following websites, their results will determine the order of the section.
https://ghostbin.com/
https://privatebin.info

I'm currently going to propose a replacement of 0bin with zerobin.net.
Then re-ordering it to: PrivateBin - ZeroBin - Ghostbin (unless your research shows a different picture).
https://github.com/PrivateBin/PrivateBin/wiki/FAQ#should-i-switch-from-zerobin-to-privatebin

**Comment by infosec-handbook** [comment]
@kewde 

>Please run the same analytics for the following websites

I added the results to the overview above. 

zerobin.net seems to be the only recommendable service when I look at the results. However, since zerobin.net doesn't disclose version information we can't be 100% sure that they don't use outdated software, too. Furthermore, I didn't look at the implementation of their code for secure pastebins.

In a nutshell:

1. zerobin.net: seems to be most secure according to the results (in terms of general web server security)
2. privatebin.info: SSH/DNS software may be vulnerable, however, privatebin.net sets most security-related HTTP headers. Worse are about 10 third-party connections and cookies from a privacy perspective.
3. ghostbin.com: seems to use a vulnerable Apache web server, offers broken RC4 encryption, and shouldn't be recommended at all
4. 0bin.net: seems to run mostly outdated and vulnerable software from 2011 and uses weak DH parameter for key exchange, and shouldn't be recommended at all

**Comment by Shifterovich** [comment]
Create a PR changing the order and adding some information. Regarding Ghostbin, we should warn users that while Ghostbin - the software - is good, ghostbin.com's security is worrisome.

**Comment by kewde** [comment]
Also out of curiosity - what tools are you using for the analysis?
It could perhaps be a standard procedure for analyzing websites we recommend.

**Comment by infosec-handbook** [comment]
@kewde 
>I believe the 10 third-party connections are related to the .info website (privatebin.info)?

Right. https://privatebin.net/ has 0 connections to third parties and doesn't set cookies.

>what tools are you using for the analysis?

I use the web services mentioned in the blog article and several well-known tools like nmap, sslyze, sslscan, dig, openssl etc. to analyze web servers.

**Comment by Vincevrp** [comment]
> Regarding Ghostbin, we should warn users that while Ghostbin - the software - is good, ghostbin.com's security is worrisome.

I think we shouldn't recommend it then. (#408)

**Comment by BurungHantu1605** [comment]
hi guys, i've removed zerobin recently because of this message from the dev:

> I dot not have time to maintain ZeroBin any more. For a more up-to-date version, please switch to PrivateBin : https://privatebin.info/ 

Source: https://sebsauvage.net/wiki/doku.php?id=php:zerobin

Seems like PrivateBin is the only choice at the moment? I've decided to link to our installation, too.
https://www.privacytools.io/providers/paste/

Should we remove Ghostbin? Replace it with something or just leave PrivateBin as the only choice?

**Comment by jingofett** [comment]
Ghostbin now displays a message that it will be shutting down this month.

I guess PrivateBin is the only choice. Is there a way to integrate it with ShareX?

**Comment by Spydar007** [comment]
Ghostbin removed via #931

**Comment by blacklight447-ptio** [comment]
as we now list privatebin, this issue seems outdated, closing.
