### ISSUE TITLE
Is your webpage GDPR compliant?

### ISSUE THREAD

**Issue by ghost** [privacytoolsIO/privacytools.io#475]
I think you need to write Privacy Policy because you are collecting data(piwik and Cloudflare Analytics).

**Comment by ohmynameisrico** [comment]
https://www.hallaminternet.com/how-to-make-your-website-gdpr-compliant/
https://getpublii.com/blog/website-gdpr-compliant.html

**Comment by CHEF-KOCH** [comment]
https://github.com/mirkoschubert/gdpr-cli

**Comment by ohmynameisrico** [comment]
@CHEF-KOCH Interesting. But I found a webpage - not a nodejs "tool" -  that create GDPR privacy policy text a month ago. Forgot a URL though.

**Comment by Shifterovich** [comment]
We're not giving any data to third parties (at least as far as *we* know, @privacytoolsIO?), so a page that says we're using Piwik and an option to opt out of Piwik should be enough I think.

**Comment by ohmynameisrico** [comment]
@Shifterovich IP address is a privacy data, read the law. Also the website is proxied by Cloudflare so you should mention piwik, cloudflare and what data(ip, ua, time, uri) you log.

**Comment by ohmynameisrico** [comment]
https://github.com/privacytoolsIO/privacytools.io/issues/374

**Comment by CHEF-KOCH** [comment]
There is a lot of FUD and misinformation traveling through the Internet right now. GDPR is protecting citizens by a few basic mechanisms, such as "[opt-in-by-default](https://matomo.org/blog/2017/09/gdpr-potential-consequences-matomo/)" (instead of opt-out) and minimizing unnecessary data production. The truth is, many plugins and libraries do unnecessarily process data. For example, many website do not effectively function if you disable js or cookies, even if they should based on their contents. There is a lot of good reasoning behind GDPR.

It is simply not true that CMS pages or services like WordPress or Piwik (renamed to [Matomo](https://matomo.org/blog/2018/01/piwik-is-now-matomo/) become "illegal". You can audit the plugins your site is using, e.g. the cookies produced, and for the data produced, whether it allows an instance (third party or not) to create a personal data trail. In those cases, you would need to install a plugin that obtains the consent of website visitors first, i.e. before creating those particular cookies. I have gone through the WP site a few days ago, and the major problem where the "social media sharing" buttons. They are known to be very problematic in terms of privacy. There are other ways to provide the same functionality without proactively creating data trails that allow Google, Facebook, and Twitter to track you across different sites. After removing the particular plugin, the only _remaining issue was Google Fonts_. It is also not true that Google Fonts are "illegal" as such because there are no court cases yet that would determine that, so if people caution against Google Fonts, it is because they could be interpreted within the GDPR as producing personal data trails. I would take this as an opportunity to review how much unnecessary data is actually gathered by fairly simple websites. Keep in mind that every Browser allows you to block third-party cookies, this is usually enough. Keep also in mind that there in Google example here two differences, the fonts directly google and the api which is provided by google (which you can use if you like) in your page, which doesn't collect anything at all (fonts.googleapis.com) while the one from gstatic are the 'problematical' one (but there needed for e.g. reCAPTCHA) and other stuff.

In retrospective:
* Google, Piwik & Co, 'randomize' IP's now (this can ne opted-out) in every CMS/configuration.
* Matomo doesn't need to change anything since they already randomize their IP for every new client, dunno about existent ones but according to a blog post from them, they got [automatically switched](https://piwik.pro/blog/how-will-gdpr-affect-your-web-analytics-tracking/) too the rest is already handled in the cookie policy which is covered (usually) in the sites privacy policy
* I wrote a detailed guide about [GDPR here](https://chefkochblog.wordpress.com/2018/05/25/what-is-gdpr/)

Fun thing is that everyone is complaining about GDPR when [Google's reCAPTCHA](https://www.google.com/recaptcha) collects hardware information (saw their changed reCAPTCHA information yesterday). What's strange is that the explanation that this data is explicitly not collected for advertising reasons, more to improve the product (in this case captcha system). But I wonder why you need to collect hardware for something which should 'only' protect something against DOS attacks.

**Comment by Shifterovich** [comment]
> IP address is a privacy data, read the law.

So what? Even e-shops don't have to care about giving customer data to delivery companies due to consent to that being implied by making the order. Giving the data to third parties that are not vital to the order is what you have to tell your customers about.

What are we doing with the IP address that we need to tell customer about? Mere storing with limited access to it is fine.

**Comment by JonahAragon** [comment]
After #795 I believe this issue can be closed, unless someone has a further concern.
