### ISSUE TITLE
Adding system adblocker and DNS changer for Android

### ISSUE THREAD

**Issue by erotavlas85** [privacytoolsIO/privacytools.io#533]
Hi,
unfortunately, Android only allows to change DNS for WiFi connection. In order to change DNS for cellular connection, it is necessary a workaround.
The following four app allows to change DNS and to block ads at system level:
- [Blokada](https://blokada.org/) without root
- [DNS66](https://github.com/julian-klode/dns66) without root
- [Daedalus](https://github.com/iTXTech/Daedalus) without root
- [AdAway](https://adaway.org/) with root

In my opinion, it would be useful to add a proper section for these adblocker and DNS changer.
Thank you

**Comment by erotavlas85** [comment]
> Daedalus isn't a option. See [iTXTech/Daedalus#45 (comment)](https://github.com/iTXTech/Daedalus/issues/45#issuecomment-333314984)

I did not know about this. I do not have any google services and daedalus works for my lineage os 15.1.

**Comment by Mikaela** [comment]
I am not sure if it's of interest to anyone here, but Blokada breaks IPv6 and may thus especially affect users who have DualStack Lite (native IPv6 + CGNed IPv4) and that is probably the most popular IPv6 transition mechanism. I know that in Finland at least 2/4 carriers have CGN, 3/4 have IPv6 and I the one of which I am not entirely sure of also has CGN. One of them has an option of paying a bit extra for not getting CGNed, but that doesn't seem like a solution to me...

* https://github.com/blokadaorg/blokada/issues/94

**Comment by Atavic** [comment]
- ***personalDNSfilter***: https://zenz-solutions.de/personaldnsfilter/

**Comment by Atavic** [comment]
- **personalDNSfilter**: https://zenz-solutions.de/personaldnsfilter/

**Comment by blacklight447-ptio** [comment]
Wasnt changing dns become a default option since android Pie?

**Comment by Mikaela** [comment]
Android 9 allows specifying hostname for DNS-over-TLS and we have started listing [encrypted DNS providers](https://www.privacytools.io/providers/dns/#icanndns) and some of them do filter ads.

I am closing this issue for now, because I see DNS changers as a step backwards in security unless they support DoH or DoT (or DNSCrypt). Please add a comment and we will reopen, in case something supports those. I only know that Blokada doesn't https://github.com/blokadaorg/blokada/issues/198.

By the way, we already list Blokada [as Android add-on](https://www.privacytools.io/operating-systems/#aaddons).
