### ISSUE TITLE
New Web Brower

### ISSUE THREAD

**Issue by g-monk** [privacytoolsIO/privacytools.io#55]
Epic is a Chromium based web browser that encrypts user identity, lets users browse privately on the internet and also protects users from tracking attempts made by other websites, scripts and other possible vulnerabilities. https://epicbrowser.com/

**Comment by alexbooker** [comment]
Can you please start a discussion about Epic Privacy Browser on our [subreddit](https://www.reddit.com/r/privacytoolsIO/)?

It looks promising but I would like to hear what the community think. There is [one thread](https://www.reddit.com/r/privacytoolsIO/comments/3rs3ra/epic_browser_any_users/) dedicated to Epic Privacy Browser already but there isn't much discussion and things could have changed in the 7 months since it was posted.

Thanks a lot for the suggestion, @g-monk :smile:

**Comment by alexbooker** [comment]
Any update on this, @g-monk?

**Comment by m0lz** [comment]
Epic browser is noted on the following site as not recommended ..
http://chromium.woolyss.com/

Scroll down to notes, and Browsers section. Probably due to being another closed source browser similar to comodo dragon / chromodo with the company having their own long term agenda's which may not be entirely as privacy respecting as you think.

**Comment by xdtnguyenx** [comment]
As @m0lz mentioned, it's probably just another closed source Chromium spin off. Everything that is mentioned on their website of what makes them different is essentially everything you can achieve with the official open source Chromium version.

Here are some of the features they claim:
- Always on private browsing mode
- Ad-blocker/tracker blocking
- Disabled Add-on/Plugin usage
- DNT Always Enabled
- Referer header data not sent
- Encrypted Proxy
- Epic Search integration

So regards to all their features, all of them can be achieved through a couple of setting changes and ad-blocker plugins in Chromium. The only ones unique are the Encrypted Proxy (like Opera) and their own Epic Search, which essentially you have to trust them from the beginning. So my questions are:

- Why is it closed source if it's just a couple of tweaks?
- Can we trust them to updated the browser with security and new features of the main Chromium branch fast enough?
- Can we trust their Epic proxy/EpicSearch to be privacy respecting?
- What is their funding like? How are they sustainable?
- Why are they based in India? (Not saying that really matters but the founder is here in D.C?)

A little plus too: Just going through their forum (http://forum.epicbrowser.com) and Twitter (https://twitter.com/epicbrowser) and reading the posts/tweets, I can't seem to take them seriously enough. On their Twitter, they push themselves as them being the good guys while Firefox is the bad one, etc. Or even on their dead forum, they only have responses to threads that have a very clear cut answer and not ones that challenge the design of their browser.

Regardless, I wouldn't recommend them because there are too many questions. As far as Firefox/Chromium goes, at least they are well documented and tested by lots of people and developers. You're better recommending Firefox with the add ons/user.js.

**Comment by Shifterovich** [comment]
The browser is very questionable and closed-source. We don't recommend closed-source programs.

**Comment by g-monk** [comment]
My view was that as long as anyone is not going to do anything shady or illegal, it should be fine.
