### ISSUE TITLE
Extend VPN section information

### ISSUE THREAD

**Issue by Offpics** [privacytoolsIO/privacytools.io#559]
After some intro text on the site, the first thing that a user sees is a VPN section, that suggests to just click and buy a service.

There is actually no explanation why would anybody need a service like VPN. There should be some information what are the actual risks and benefits of using it in different countries.

**Comment by Shifterovich** [comment]
I wanted to add many tutorials and things like this to the website, but I don't have enough time for that right now.

However, I have a few articles about VPNs, like this one: https://theprivacyguide.org/tutorials/understanding-vpns.html.

**Comment by strypey** [comment]
Maybe worth integrating some of the insights from '[Don't Use VPN Services](https://gist.github.com/joepie91/5a9909939e6ce7d09e29)' and its comment thread. Especially the point that using a commercial VPN is just paying a second ISP to stop potential spying by the ISP you're already paying for your net connection.

A few more criteria for listing commercial VPN vendors on PTIO (examples are from ExpressVPN as this is the vendor I ended up using since I got to China):
* all apps provided to users licensed as free code - no source code is available for any ExpressVPN apps, I've asked customer support about this a number of times. 
* all required [Javascript licensed as free code](https://www.gnu.org/philosophy/javascript-trap.en.html), or no Javascript on the company website at all  - according to NoScript, the ExpressVPN website has a bunch of proprietary JS from third-party domains including Akamized, SnapEngage, Farcebook(!), and 3 goOgle domains(!). AFAIK there is no way to use their service without visiting their site and allowing at least some of this JS.
* no trackers or other privacy-compromising components built into the company website (see above).

Some free code projects relevant to the discussion of [VPN providers/ replacements](https://trisquel.info/en/forum/potential-vpn-options-replacements) (in alphabetical order):
* [Bitmask](https://github.com/leapcode/) - developed by LEAP Encryption Access Project, supported by a number of non-commercial providers including RiseUp.net.
* [Lantern](https://github.com/getlantern) - bills itself as "faster than a VPN". The client code is all free and you get a certain amount of gratis use per month (metred by traffic if I remember rightly), then you have to pay.
* [Mysterium](https://github.com/mysteriumnetwork/) - an experiment with building a decentralized VPN on a blockchain.
* [Wireguard](https://git.zx2c4.com/?q=wireguard) - OpenVPN replacement (see #633 )

**Comment by strypey** [comment]
Compare the ExpressVPN UX to Mullvard, for example, which has a HG repo for all its end-user apps, a website that works without JS (although it does suggest users turn it on), and goes to great lengths to allow folks to use its services anonymously (requires no email address to sign up etc). Not requiring proprietary software to use the actual VPN service ought to be a minimum requirement for endorsement on PTIO.

**Comment by Mikaela** [comment]
Related: https://github.com/privacytoolsIO/guides.privacytools.io/issues/1

**Comment by strypey** [comment]
Arguments have been made in the discussion on adding ProtonVPN (#238) that the page ought to avoid recommending any specific commercial service. Instead, it could focus on a discussion of why a user might choose to use a VPN service, what they can and can't do, the pros and cons of a commercial service vs. self-hosting/ community-hosting (eg RiseUp's gratis service for activists using BitMask), and some information about software options (client-side and server software for self-hosting). 

If there are recommendations of specific commercial vendors, it would make sense to choose ones whose products and services are endorsed elsewhere on the site. ProtonVPN fits in the category, since ProtonMail is recommended. I would also endorse the Librem Tunnel service recently launched by Puri.sm, and RiseUp's service.

**Comment by atomGit** [comment]
this needs changed i think (https://www.privacytools.io/providers/vpn/):

> Note: Using a VPN provider will not make you anonymous. But it will give you a better privacy. A VPN is not a tool for illegal activities. Don't rely on a "no log" policy.

"give you a better privacy" definitely needs changed, but how about something a little more...

Warning: A VPN provider will not make you anonymous, however it can help to protect your privacy. No VPN provider can be considered to be completely trustworthy and therefore one should not rely entirely upon their advertised policies, including 'no log' policies. A VPN is not a tool to be used for illegal activity. Please research multiple providers carefully before committing.

**Comment by blacklight447-ptio** [comment]
since the redesign of the website, vpns are not the first thing users see anymore. Also we now have more info on VPN s on the warning label on the vpn provider page, so i think we can close this issue now, thoughts? @JonahAragon @Mikaela  @nitrohorse

**Comment by Mikaela** [comment]
> In most cases, VPNs do little to protect your privacy or enhance your security, unless paired with other changes.

* https://www.privacytools.io/providers/vpn/#info

Yes, I think we can close this.
