### ISSUE TITLE
Add "Redirect AMP to HTML" to FF addons

### ISSUE THREAD

**Issue by tya99** [privacytoolsIO/privacytools.io#585]
I believe we should consider adding [Redirect AMP to HTML](https://www.daniel.priv.no/web-extensions/amp2html) to the [addons](https://www.privacytools.io/#addons) section.

It was previously discussed in [this reddit thread](https://www.reddit.com/r/privacytoolsIO/comments/9slnf5/redirect_amp_to_html)

**Comment by tya99** [comment]
Why was this closed? Also I dun goofed on the URL it's supposed to be:

https://www.daniel.priv.no/web-extensions/amp2html.html

**Comment by JonahAragon** [comment]
I don't know, I agree this should probably be discussed.

**Comment by blacklight447-ptio** [comment]
to continue discussion: i would say this would be a bit out of scope, we already recommend a lot of extensions, and we cant just keep adding more to fix every single issue on the web. the more extensions a user has to install, the more likely they wont install them at all because they get overwhelmed. furthermore, adding tons of addons can also slow down your browser, increase browsing fingerprint, and add more attack surface. seeing how this addon doesn't even have any direct privacy benefits, i do not think we should add it.

**Comment by JonahAragon** [comment]
Thank you @blacklight447-ptio. 

At another glance I’m going to close this again. Seeing as you’re hitting Google’s servers anyways, even if you’re immediately redirected after, this tool doesn’t appear to add a *privacy* benefit to the user. The actual privacy solution is to stop using Google.
