### ISSUE TITLE
[Software Suggestion] Vuvuzela

### ISSUE THREAD

**Issue by Shifterovich** [privacytoolsIO/privacytools.io#637]
## Basic Information

**Name:** Vuvuzela
**Category:** Instant messenger
**URL:** https://vuvuzela.io/

## Description

> Vuvuzela is a private chat application that hides metadata, including who you chat with and when you are chatting. Vuvuzela supports millions of users and is secure even if the network and a majority of the servers are compromised.

Vuvuzela creates noise indistinguishable from normal traffic when you're not communicating to avoid traffic analysis.

![Noise](https://vuvuzela.io/static/server.gif)

**Comment by gjhklfdsa** [comment]
Very old-looking UI:
![image](https://user-images.githubusercontent.com/45323745/49128032-9e1b4f80-f2c1-11e8-96d5-c522c7f58d65.png)

Not that this should keep it from being listed, I just would only have it under "Worth Mentioning".

**Comment by Shifterovich** [comment]
I agree. It's probably not ideal for most users. Most users don't really care about (metadata) traffic analysis either.

**Comment by lrq3000** [comment]
I just wanted to say I have just discovered this software from this [reddit post](https://www.reddit.com/r/privacytoolsIO/comments/e8ycd0/opinions_on_jami_messenger_e2e_encryption_is_only/fak5amw), and it looks highly interesting. I know about differential privacy as for my work it is one of the possibilities we can use to anonymize datasets. It's however still quite experimental, but it already is seeing a few practical applications, such as anonymizing the inputs automatically for [deep learning neural networks](https://arxiv.org/abs/1607.00133).

I think it may be a worthy mention, but I can't test it as apparently it's [hard to build on Windows](https://github.com/vuvuzela/vuvuzela/issues/53) (which is what I use currently) and the interface indeed looks old (and the software seems to not be actively maintained anymore since 6 months). Note there was also an [unofficial web client](https://github.com/jlmart88/vuvuzela-web-client) but it is now outdated.

I would suggest to reconsider the project if someone comes back to maintain it, as it has a really interesting take on metadata which is mathematically guaranteed via differential privacy.
