### ISSUE TITLE
🆕 Software Suggestion | Ecosia search engine

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#682]
## Basic Information

**Name:** Ecosia
**Category:** Search engine
**URL:** https://www.ecosia.org/
**About URL** https://info.ecosia.org/

## Description

Ecosia is an search engine planting trees with the money they make. They appear to be transparent releasing financial documents at https://documents.ecosia.org/467540 (however I didn't read any).

Their privacy policy looks OK to me, https://info.ecosia.org/privacy . However their results come from Bing, but that is also one of the sources of DuckDuckGo.

**Comment by asddsaz** [comment]
They have a decent privacy policy: https://tosdr.org/#ecosia
But are non-free, therefore don't meet the software criteria.

**Comment by Mikaela** [comment]
DuckDuckGo and StartPage.com are also non-free as far as I can see?

**Comment by Mikaela** [comment]
Oh, you opened https://github.com/privacytoolsIO/privacytools.io/pull/699 and forgot to mention it here.

**Comment by libBletchley** [comment]
Ecosia has always been hostile toward Tor users which makes it a non-starter from a privacy viewpoint.

ATM it's just dropping packets from Tor and timing out, which IMO is even less diplomacy than a "403 forbidden".

**Comment by Mikaela** [comment]
https://github.com/privacytoolsIO/privacytools.io/pull/960#issuecomment-498073312 ?

**Comment by erciccione** [comment]
Why reopen this @Mikaela ?
From the comment of the ghost user looks like Ecosia is not Tor-friendly, which IMO is a big "no no" if we are talking about user privacy. I don't think that them being non-free was the stopper here.

**Comment by Mikaela** [comment]
I don't think we have a formal rule of search engines needing to be Tor friendly in order to be listed. To [quote myself from the forum](https://forum.privacytools.io/t/what-is-your-daily-search-engine/174/7?u=mikaela):

> Ecosia, because I am more worried about the climate change than their Tor hostility.

What do you think @privacytoolsIO/editorial ?

**Comment by erciccione** [comment]
I'm confused now. Isn't this **Privacy**tools.io? Shouldn't this community suggest the best tools to protect people's privacy?

> I don't think we have a formal rule of search engines needing to be Tor friendly in order to be listed

You don't need a formal rule. Supporting Tor is a big point if you are proposing a privacy-oriented browser, planting trees is not...

You are not addressing any of the legit concerns pointed out by the ghost user, but you are reopening this issue anyway. I understand you like Ecosia for the ideology behind it, but that's offtopic. I share your concerns for the environment, but you are suggesting *Privacy* tools to a wide audience here, you have responsabilities. I don't think would be wise to ignore the concerns about privacy because "You are more worried about the climate change".

**Comment by Mikaela** [comment]
Case closed, see comments here and https://github.com/privacytoolsIO/privacytools.io/pull/1036#pullrequestreview-263991424 & below.
