### ISSUE TITLE
✨ Feature Suggestion | Add Voat Subverse

### ISSUE THREAD

**Issue by David-Beetle** [privacytoolsIO/privacytools.io#711]
**Description**: Add [Voat Subverse](https://www.wikipedia.org/wiki/Voat) for discussion.
**Why**: Voat is a free software privacy respecting Reddit alternative. It is important for privacy communities to support private alternatives.

**Comment by Mikaela** [comment]
Does it federate? There is also https://tildes.net/ with no plans for federation and is currently invite-only.

**Comment by David-Beetle** [comment]
@Mikaela I wouldn't be the one to ask, if you have any questions I would recommend posting in [/v/help](https://voat.co/v/help). If you find anything, please reply as I would be interested to know.
Sorry if this wasn't the response you were looking for.

I would also like to note that next-to-zero decentralized social networks are easy to use.
Even less have users, and even less are popular. [Voat](https://voat.co/), is very easy to use and open-source.

Voat is a fairly popular site: https://www.alexa.com/siteinfo/voat.co/

**Comment by Mikaela** [comment]
I think they are wery different, Mastodon is a federated Twitter/TweetDeck, while Voat is a OSS Reddit clone.

**Comment by Shifterovich** [comment]
All of these social networks are like that. Regardless of being decentralized/federated/centralized. If free speech is allowed, "hate" speech will be present.

**Comment by libBletchley** [comment]
# CloudFlare site - must reject
Voat is jailed in the privacy-hostile walled-garden of CloudFlare.  This makes Voat unsuitable for privacy proponents.  In fact, this project should fundamentally reject any product or service that has ties to CloudFlare.

# What is CloudFlare (for the uninitiated)
CloudFlare is a vigilante extremist organization who takes the decentralized web and centralizes it under one corporate power that controls the worlds largest walled-garden. A very large portion of the web (10%+) that was once freely open to all is now controlled and monitored by one central authority who decides for everyone who can see what web content. This does serious damage to net neutrality, privacy, and has immediate serious consequences:
* Cloudflare has a policy to block all Tor users by default. It's a crude, reckless and unsophisticated (but cheap) way to create the illusion of security. Collateral damage is high. Privacy takes a global hit because Cloudflare has decided what best suits their business to the detriment of everyone else.
The damage to anonymity helps spy orgs conduct illegal surveillance.  The consequential access inequality constitutes a network neutrality abuse.  Access equality is central to net neutrality.
* CloudFlare is a man-in-the-middle who sees all traffic [including tunneled HTTPS traffic] (http://cryto.net/~joepie91/blog/2016/07/14/cloudflare-we-have-a-problem/)(and thus passwords!).
* No transparency: as Cloudflare performs a DoS attack on Tor users they obviously do not inform web owners. Web owners are usually unaware that legitimate patrons are being blocked from accessing their site. These businesses are all damaged so that one business can profit.
* Cloudflare shields criminal webmasters by hiding their IP address from the public. A website involved with crime often has other criminal websites on the same IP, but users who try to protect themselves cannot block the IP address of the malicious site.
* Cloudflare makes heavy use of CAPTCHAs. CAPTCHAs put humans to work for machines when it is machines who should be working for humans.  The CAPTCHAs are often broken as well.
* Tor users are driven off of Tor because CloudFlare creates such a hostile environment for them that it becomes impractical to deal with all the CAPTCHAs.
* Cloudflare is potentially [injecting javascript spyware](http://www.crimeflare.com/) into the traffic of their patrons to collect data (this is how cloudflare pays their bills). See  for more details.
* Google has a hand in the CAPTCHAs and as a consequence can track which of their logged-in users are visiting the page presenting the CAPTCHA.
* Deceives users into believing their connection is secure (HTTPS & browser padlock) when in fact the user is MitMd.

**Comment by danarel** [comment]
@libBletchley you may want to check the DNS on PrivacyTools.io then.

**Comment by libBletchley** [comment]
@danarel 
Oh shit that's really despicable.  I couldn't tell from the `dig` output but there is indeed a `cf-ray` in the headers.

**Comment by Shifterovich** [comment]
@BurungHantu1605 used it for HTTPS but GH pages now support HTTPS without CF.

**Comment by libBletchley** [comment]
Is there an onion service?  That wouldn't require HTTPS.

For the surface web combining GH with Netlify will give HTTPS but I'm not sure if that solves your issue.

**Comment by shortenjukebox** [comment]
> Does it federate? There is also https://tildes.net/ with no plans for federation and is currently invite-only.

Tildes is open source, though the project’s focus is just not on federation.

**Comment by atomGit** [comment]
> Voat is social media for neo-nazis and pizzagate conspiracy theorists.

not entirely true, though it seems to be devolving even more as of late - as for pizzagate, look into that deeper than what you read or watch on more mainstream sites/news media - at its core it was never really about a pizza joint in DC with secret tunnels, it's about the larger pedo rings operating globally, especially those with ties to government

there are (or at least were) a small number of very smart and well educated people on Voat who presented many facts and talked about subjects that they couldn't talk about elsewhere (many were reddit refugees)

also i'm not sure the code is open - maybe someone can correct if i'm wrong - i know it was developed with Microsoft tools

**Comment by blacklight447-ptio** [comment]
it seems here that the community has decided that they would not like to add voat, so im closing the issue.

**Comment by Mikaela** [comment]
Yes, and I also see a conflict between PTIO and Voat that I described at https://github.com/privacytoolsIO/privacytools.io/pull/930#discussion_r283827464
