### ISSUE TITLE
💬 Discussion | Aren't you worried about Bitcoins (& other proof-of-work) energy usage and the climate change? Shouldn't proof-of-stake coins be suggested instead?

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#798]
According to find in page, Bitcoin is mentioned on PrivacyTools.io seven times. I am worried about its (proof of work) energy usage and the effect to climate change.

Bitcoin may be private/anonymous, but there are private alternatives that don't use so much energy using proof of stake system and if they aren't migrated to, what do you do with your privacy without there being a planet to enjoy it on?

* [Wikipedia: Bitcoin#Energy consumption](https://en.wikipedia.org/wiki/Bitcoin#Energy_consumption)
* [Digicomist: Bitcoin energy consumption](https://digiconomist.net/bitcoin-energy-consumption)
    * [Digicomist: Ethereum energy consumption](https://digiconomist.net/ethereum-energy-consumption)

I haven't read on the alternatives lately, but when I did the names that stayed in my mind were: Ethereum (I cannot find their status on migrating to proof of stake, only their [Proof of Stake FAQ](https://github.com/ethereum/wiki/wiki/Proof-of-Stake-FAQ)), [Chia](https://www.chia.net/) (which is from author of BitTorrent and has updated their website, but no news on its launch either) and [Filecoin](https://filecoin.io/) (which is the most interesting to me as it's related to [IPFS](https://ipfs.io/) and resolves paying others to pin content so it won't disappear when your node is turned off. They seem to have code at [GitHub](https://github.com/filecoin-project) and some early mining program available).

**Comment by JonahAragon** [comment]
Based on those graphs, Ethereum doesn't look *too* much better. The other coins seem pretty niche and focused on specific platforms (i.e. file hosting) which makes them seem to me at least like they won't work super well just for general payments.

I agree this is a good reason we should stop recommending Bitcoin, as well as the other privacy-related reasons that have been brought up in issues like #256. I just don't know what the best alternatives would be.

**Comment by five-c-d** [comment]
I am against this entire line of thinking.  :-)   I think that privacyToolsIO should be about tools, and about whether those tools are privacy-respecting, and then giving some indication of what the tools are suited for:  splitting the listings into categories (mobile OS versus laptop OS versus liveCD ... VoIP versus IM versus webmail service versus email client).  Then, within each category, highlighting the tools that are 'most recommended for everyday endusers' in the top3, and then in WorthMentioning also specifying alternatives -- some of which might be experimental, or beta software, or hard to use, or whatever.  Because privacy&security are the main purpose of the site, there is a heavy emphasis on libre-licensed tools, and freemium tools or partially-proprietary tools (especially ones with trackers) are discouraged.  

<details><summary>not saying politics is verboten, or does not matter, just, trying to avoid the slippery slope</summary><p> 

There is some political basis for everything on privacyToolsIO, in the abstract: there is a lot of discussion about whether privacy is a civil right, whether privacy is an inherent human right, whether governments protect privacy (and which ones do not), and so on.  Sometimes this impacts the categories:  there are no Five-Eyes-based VPNs or webmail providers, for instance.  But all other categories are exempt from that, because for the most part, only in the vpn and webmail categories is it *possible* to find a lot of high-quality options that are not in FiveEyes countries, especially the USA where most software is written.  

Even in those categories though, VPN and webmail, pragmatic exceptions are made:  there are lots of providers that are in FourteenEyes countries.  There are several providers that are 'legally' incorporated in non-FiveEyes countries but *reside* in FiveEyes jurisdictions (the one that comes to mind is iVPN ... Gibraltar-based legal entity but UK-residency ... there are others like that however).  

If we start eliminating bitcoin -- which is, by far, exponentially more useful/usable than any alternative cryptocurrency -- because the use of bitcoin is energy-intensive, where does that lead?  Should we eliminate any tool, if the developers are not living in carbon-neutral homes and driving green-energy automobiles?  Should we eliminate any tool, if the provider of that tool has any servers or personnel in a country which is not a signatory to the Paris accords?  What if one of the volunteer developers who once submitted a patch with 20 lines of code to the tool, once made a comment on twitter that they are not very sure whether the IPCC reports are not biased... is that sufficient to delist the tool?  

I don't intend these comments to be hyperbolic.  I just am pretty firmly convinced that if privacyToolsIO starts down the road of "we must only list tools that are not guilty of political transgressions" ...which can only mean, that the DEVELOPERS of the tools are not guilty of political transgressions, or that the legal entities (foundation/corporation/etc) which those developers are involved with are not guilty of political transgressions, or that the countries in which those developers and legal entities are located/incorporated/doingBusiness are not guilty of political transgressions... it is a slippery slope.  And it is hard enough to find privacy-respecting libre-licensed codebases that are usable enough for everyday endusers.  

I submit that it is pretty much impossible to find privacy-respecting libre-licensed easy-to-use tools, with developers&backers&suppliers&nations that have NEVER in any way committed any kind of political transgression, nor been linked to nor done business with, developers-or-backers-or-suppliers-or-nations, that did commit such transgressions.  

</p></details> 

Recommend not letting politics that is NOT directly and specifically having an impact on the privacy that the **tool** provides, right now with no prediction needed, have a place here.  If the developer of a tool, or the legal entity of that developer, or the supplies&dependencies that developer&organization utilizes, or the nations-and-provinces that developer&organization operate in, are doing something which *has a direct impact on the tool* in question, then it is not a political question anymore.  

It is a question of, does the tool provide privacy, or does it not, to endusers that are using the tool.  But as soon as indirect arguments are allowed to begin, we're in deep trouble -- this developer said something on twitter about climate change, that developer said something on mastodon about copyleft, their supplier is hosted on AWS, the nation they are in once committed an atrocity during WWII, et cetera, etc.  

p.s.  I think it is fine to mention, in the cryptocurrency section of the website... *is* there going to be such a section?  right now bitcoin is just mentioned as "all vpn providers and most webmail providers and some DNS-related providers accept bitcoin" ... the pros and cons of various cryptocurrencies.  The list would likely be Monero-and-zCash as top1, Bitcoin as top2, and Ethereum as top3, with maybe Ripple as worthMentioning.  

It would make sense to list "con:  massive electricity-usage during transactions" under bitcoin, because it **is** a problem.  Not just for the question of political ramifications should use of cryptocurrency become widespread, but for scalability reasons, for cost-of-transactions reasons, and for risk-of-centralization-and-51%-attack-vector reasons (massive electricity usage is a security risk in theory because it makes 51% attacks vastly more plausible).

**Comment by erciccione** [comment]
I think suggesting a consensus algorithm only according to the amount of electricity consumed would be a terrible idea, there are security and consensus related issues that need to be addressed and all the alternative suggested by @Mikaela are not alternative to Bitcoin (maybe Ethereum is the closest one, but has very big issues and one is decentralization).

> Bitcoin may be private/anonymous

**Bitcoin is not anonymous** and has very limited privacy features. In fact, it's easily traceable[[1]](https://bitcoin.org/en/protect-your-privacy)[[2]](https://cointelegraph.com/news/are-bitcoin-transactions-traceable).

About Bitcoin consumes, take a look at [this report](https://coinshares.co.uk/bitcoin-mining-cost-june-2019/) which investigate the electricy consumption of the bitcoin network. You'll see that about **75% of the electricity that powers Bitcoin come from renewable sources** and this number will only increase, since miners will always look for the cheaper source of electricity. Bitcoin is also being a big incentive for the development of more efficient renewable energies (since more efficient = cheaper for the miners).

Bitcoin shouldn't have space on privacytools because has no (or very limited) privacy, not because it's not enviromental friendly, since as we see from the report, this is not true.

My suggestion would be to list  best Privacy-focused coins in circulation, but keep the mentions to Bitcoin. See #207 and #256 .

**Comment by five-c-d** [comment]
> Bitcoin shouldn't have space on privacytools because has no (or very limited) privacy

Compared to what alternatives?  It is the most ubiquitous cryptocurrency.  It gives a reasonable degree of pseudonymity right out the gate, compared e.g. to paypal or visa.  If you combine bitcoin with a tumbler and/or with forex-into-monero-or-zcash-and-back, you get an improved degree of anonymity as well.  

> **Bitcoin is not anonymous**

This is true, but anonymity is not a dealbreaker-requirement for some people, it depends on their threat-model.  There are ways to get a modicum of anonymity via BTC, per above, and I would argue that even just straight BTC with no extra legwork is considerably more privacy-respecting than visa/paypal/etc type of "typical online transaction mechanisms"  

> about 75% of the electricity that powers Bitcoin come from renewable sources

Yes, this is also true, hydro and geothermal and whatnot rather than solar PV and windfarms methinks.  In the long run my vote is for orbital-solar-thermal as the best way to power bitcoin transaction-processing, but there are some latency constraints  :-)  

However, I don't think that is privacy-relevant, though it is politically-relevant it is not the-politics-of-privacy (e.g. in the same way that key disclosure laws and crypto-backdoor laws and such things are directly privacy-related political issues).  

I think we should list BTC, Monero, and maybe Ethereum (which to me is a "different category entirely") as the top3, if there is to be a dedicated section.  However, for the other sections, e.g. the VPN listings where accepting BTC is a requirement to be listed, I don't think we want to make any changes.  Accepting BTC is "good enough" because it can be converted into Monero and back, if the enduser's threat-model requires that

**Comment by erciccione** [comment]
> Compared to what alternatives?

Compared to other cryptocurrencies.

> It gives a reasonable degree of pseudonymity right out the gate, compared e.g. to paypal or visa

I see your point but it's not always true. For example, using paypal, visa etc. Your privacy is at risk because they can easily see where your money goes and hand over your information to the authorities if asked, but only these subjects can have access to your data (assuming nothing nasty happens in the meantime, obviously). With transparent blockchains anybody can track where you send the money and see where they came from, even with some basic chain analysis.

> If you combine bitcoin with a tumbler and/or with forex-into-monero-or-zcash-and-back, you get an improved degree of anonymity as well.

True, but now you have an extra step that a user should do to get some privacy. This, assuming that the user is aware of the possibility to mix coins and is able to start the process, means that anything can go wrong and the users could easily see their privacy damaged if they do something wrong. Real privacy cannot exist if the base layer is not privacy-focused, Z-Cash is a perfect example. They have great technology powering their shielded (private) transactions, but nobody use it and who does use it can be red flagged, because an authority can think they have something to hide (or they have used the simple transparent transactions).

> However, I don't think that is privacy-relevant, though it is politically-relevant it is not the-politics-of-privacy

I agree and don't agree at the same time :P. Right now every transaction we make with fiat money is checked and authorized. In case of issues my money can be even taken away from me. Having the possibility to manage my money in a private way is extremely important for people's privacy.

> I think we should list BTC, Monero, and maybe Ethereum

I would list Monero Z-Cash and Bitcoin. Ethereum has no privacy features and as you say, it's something different.

**Comment by Mikaela** [comment]
I have warmed a bit towards https://stellar.org/ since opening this issue as its integration to https://keybase.io (#740) made me ask and read about it a bit. However it's not anonymous either.

What is privacy that cryptocurrencies are required to give before getting listed?

**Comment by erciccione** [comment]
> What is privacy that cryptocurrencies are required to give before getting listed?

In my opinion an efficient privacy focused currency should have these proprieties:

1. Decentralized and open source.
2. Fungible (meaning 1 coin is equal to another coin of the same value. This is the biggest problem bitcoin has, it's not fungible and this because it's traceable)
3. Recipients and senders must be hidden by default
4. Transferred amounts must be hidden by default
5. Wallets must be private and the amount contained known only to the owner.

At the moment the only major coin holding all these 5 proprieties is Monero. Other projects like ZCash offer a good amount of privacy, but zcash is not private by default, it's based on a trusted setup and developed by a company. Still worth mention tho.

**Comment by BearerOfHonesty** [comment]
> According to find in page, Bitcoin is mentioned on PrivacyTools.io seven times. I am worried about its (proof of work) energy usage and the effect to climate change.

I think privacy should still count as the most important factor on PTIO.

While POW-coins do use a lot of energy and I agree that every little bit counts there are much more efficient ways to fight climate change, e.g. vegetarianism/veganism (because livestock produce _a lot_ of greenhouse gasses).

**Comment by JonahAragon** [comment]
Seeing as we don't recommend any cryptocurrencies at the moment I'm closing this issue.

**Comment by lrq3000** [comment]
In terms of privacy, anonymity and security, monero seems to check all the marks by default. The only concerns that may remain is its energy consumption, since it's using proof-of-work. If the goal of privacytools.io is to provide privacy aware tools, monero seems to be a good fit for financial transactions, no?

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
You should take a look on Pirate Chain (ARRR), AFAIK they are the most private crypto around although I don't know exactly how much energy they consume, I know that they use Komodo's delayed Proof of Work to protect against double spending and 51% attacks by attaching ARRR's chain to Bitcoin's blockchain, but I don't know they environmental impact of this. Maybe ARRR is not generating too much but if it is dependant on BTC the damage continues.

Aside from that, their blockchain is completely empty and there are no options to unable this, it just show that a transaction was made, they apply fungibility, and some other stuff like the dPoW to provide security to the blockchain.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
There's also DeepOnion which has some good features such as private transactions by default and routing your traffic through Tor but they have made some shitty decisions just as spamming subreddits with posts, still they look promising but ARRR is the best option out there by far.

**Comment by Mikaela** [comment]
Could you open new issues for the suggestions?

**Comment by lrq3000** [comment]
For reference as a side-note: [Bitcoin over Tor isn't a Good Idea](https://www.researchgate.net/publication/305053676_Bitcoin_over_Tor_isn't_a_Good_Idea)

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
> For reference as a side-note: [Bitcoin over Tor isn't a Good Idea](https://www.researchgate.net/publication/305053676_Bitcoin_over_Tor_isn't_a_Good_Idea)

I haven't read the paper yet, but just for clarification in this case Bitcoin is not used as an umbrella term for cryptocurrencies, right? This is only for that specific coin since it has a lot of other features which can de-anonymize users.

**Comment by lrq3000** [comment]
No it's specifically about Bitcoin, not other altcurrencies, although the flaws outlined in this article are probably applicable to most of the other coins based on Bitcoin or using a similar architecture.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
@lrq3000 Could you take a look at my Piratechain issue and tell if it could apply to that altcoin? I don't think so, but just to be sure.

**Comment by lrq3000** [comment]
Ah sorry I'm not competent enough in this topic to give an insightful
opinion, but maybe you could share the paper with the pirate coin authors
and ask them their opinion :-)
