### ISSUE TITLE
💬 Discussion Are translations going to merged to this project at some point?

### ISSUE THREAD

**Issue by cwcopa** [privacytoolsIO/privacytools.io#836]
Hello,
is it planed to make this page multilingual or will translated versions furthermore hosted by extern projects?

Thank you for your time.

**Comment by JonahAragon** [comment]
I think the problem is our regular contributors that keep the site up-to-date can't *also* keep all the translations updated, and the people that *do* run the translation sites often fall behind because this site changes so quickly (see https://victorhck.gitlab.io/privacytools-es/ for example), so keeping them all up-to-date on the official project would be a challenge.

**Comment by victorhck** [comment]
I try to keep the spanish translation update, but with the old style. Trying to update the new style it's a great work to do (and will have to move from html page to new static theme used in English page)

**Comment by cwcopa** [comment]
@johnnagro I currently rework the German version, but I wanted to inform me before I  change everything and the German translation would be merged anyways.

Thank you, can be closed.

**Comment by Shifterovich** [comment]
@JonahAragon When I was considering moving from HTML to MD with YAML lang strings, the thing that turned me away from the idea was that most PRs would be just keeping the translations updated. It's better to have sections as separate files and let forks use that to easily stay up-to-date.

**Comment by linsui** [comment]
Could anyone tell me why don't extract strings into files and host them on such as weblate? :confused: Thanks.
