### ISSUE TITLE
💬 Discussion | Firefox geo.enabled concerns

### ISSUE THREAD

**Issue by JonahAragon** [privacytoolsIO/privacytools.io#841]
I received this via email.

> Hi Jonah,
> 
> I just found that geo.enabled might stop certain website from displaying correctly. Here's something I posted on Reddit describing this issue:
> https://www.reddit.com/r/firefox/comments/bb9vgy/site_broken_under_firefox_unless_geoenabled_is/
> 
> I am not sure if the team is aware of this. I am reporting this to you and see if it's advisable to add some warning in the description part of this item. Thanks.

**Comment by Mikaela** [comment]
I wonder what do Mozilla/Firefox developers say about this. I cannot find open issues [at Bugzilla](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=geo.enabled&list_id=14660229), which might be a better place to discuss this, even if we should probably link to the bug.

**Comment by 3j9fkyahunqoxwqu** [comment]
Hello
AFAIK geo permission won't granted automatically and if a website asks for it, browser will ask from user.
Setting default deny for geo is bad for fingerprinting because it makes the user completely distinct from oyhers while having low benefit.
Anoyther problem with it is geo is mostly absent in laptops/drsktops (although my main reason was above i wrote this also for more reasons.)

Thanks

**Comment by blacklight447-ptio** [comment]
Closing issue as we no longer list this preference.

**Comment by Mikaela** [comment]
#1217 was the deleting PR for future reference.
