### ISSUE TITLE
Intel Management Engine & AMD Secure Technology

### ISSUE THREAD

**Issue by YugiFanGX** [privacytoolsIO/privacytools.io#844]
Backdoor in computers
https://www.youtube.com/watch?v=Lr-9aCMUXzI

You should also make people aware of Firmware Blobs

**Comment by YugiFanGX** [comment]
Alternative seems to be https://en.wikipedia.org/wiki/RISC-V

Is there anything known for ARM architecture?

**Comment by beerisgood** [comment]
I don't see why this YouTube video is related to AMD.
Also the video description recommend NordVPN as protection.
Seriously?

**Comment by libBletchley** [comment]
I asked Purism when they started producing Intel-based machines why the hell they were supporting Intel and its M.E.  They had an /oh shit/ panic moment because they did a bunch of Intel development without knowing about the ME.  They refused to throw away the work they had done.  Eventually someone worked out how to "disable" (*) ME and Purism took that idea and ran with it - using marketing that kind of implies that Purism did the work.  The big problem is not taking credit for someone elses work, but rather that Purism continued to support Intel.  Of all chip makers Intel (founder of ALEC) is the most unethical.  So Purism is leading consumers to feed the worst player because they don't want the effort of changing directions to favor ethics.

(\*) *disable* is in scare quotes because ME is never fully disabled.  It must run to boot the chip, but post-boot it can be disabled to some extent.

## Arm
Arm has *Trustzone*, which is the same problem as ME.  But Arm has multiple producers which at least means there's a competition of pricing and ethics.

## AMD
AMD also [has](https://libreboot.org/faq.html#amd) a *Platform Security Processor*, which uses Arm's Trustzone.

## Privacy and freedom comparison
Intel chips have always been non-free proprietary closed-source.  AMD had a moment of enlightenment where their code was open source for a window of time and this benefited libreboot, which ended in 2013.  All modern chips (x86, amd, arm) are spy chips, and all have a non-free blob.  So strictly in terms of the nuts and bolts of privacy it makes sense to condemn all post-2008 Intel chips and post-2013 AMD and ARM.  If someone must have a modern chip, all chips are equally at risk for privacy abuse AFAIK.

In this situation, ethical consideration needs amplification.  Intel is the most insidiously under-handed and bent against individual consumers.  So I boycott Intel, which also means I will not buy a Purism laptop.  Shame on Purism for discarding ethics in their decision.

**Comment by beerisgood** [comment]
So the Purism team use Intel because of better marketing (disable ME shit)?
Ridiculous

**Comment by libBletchley** [comment]
I'm not sure why Purism chose Intel in the first place, but often people favor Intel if they're performance junkies.  I was already boycotting Intel before the ME scandal hit on ethical grounds.  Why Purism stuck with Intel is likely because they already invested effort into it.. but I can only guess.  Maybe it goes back to whatever their original reason for choosing intel was.

It would be important to Purism to be able to disable ME/PSP/Trustzone.  PSP can also be disabled in the BIOS and the latest UEFI, and the AMD approach is better documented.  Not sure about trustzone.

**Comment by Atavic** [comment]
Intel ME is a chip, a piece of hardware with its own OS, Minix, that totally bypasses windows or any other OS the users install above it. It can communicate with less known protocols as I2C and so Purism users do not have "complete visibility into the deeper levels" of their computers.

Removing any intel related software, service and drivers does nothing to the OS into the ROM of the chip.

The way to go is to flash the ROM, like [this](https://github.com/corna/me_cleaner/issues/201).

**Comment by blacklight447-ptio** [comment]
I agree that purism should largely be avoided where possible, since it is possible to get an x86 based computer which provide more software freedom, for alot less money. Cryptogs.de for example. For modern computers, one could take a look at the Talos II and the Talos lite from Raptor, these computers are based upon the power 9 architecture and allow you to run a fully libre stack. These are sadly still expensive machines, soon the Blackbird, also from raptor, will be released and will be about the price of a high end gaming desktop.

Anyway about hardware freedom on x86, This is impossible going forward. The nasty thing is that even if one where to copy Intel ME bit for bit perfectly, they wouldn't be able to use it because the computer will force shutdown after exactly 30 minutes. This is because the code is not signed by intel. Sure, Purism could claim the are "actively working with Intel", but this is just false hope. Even Google has tried to open up intel ME and didn't succeed. If a immensely powerfull mega corperation like Google cannot convince Intel, then a tiny laptop OEM like Purism won't stand a chance.

As for now: if you have alot of money to burn, one could buy a Talos machine and run debian on it. If this is not the case, one will have to settle with an older x86 machine with libreboot to have full hardware freedom, atleast until alternative architectures like RISC-V (look at Sifive) or power 9 (look at Raptor) are more in the reach of the general population.

**Comment by FrostKnight** [comment]
I have heard something interesting about AMD, their richland processors:
https://freundschafter.com/cybersecurity-cpu-and-system-alternatives-without-intel-me-iamt-and-amd-psp-secure-technology/

IF this is true, the richland processors can be used without a non-free bios, if people do the work of liberating them completely.

**Comment by pahakalle** [comment]
You can always partialy deblob Intel ME/TXE firmware images with [me-cleaner](https://github.com/corna/me_cleaner) but it does require external flashing

**Comment by tya99** [comment]
I think at this point it's really something we can't give advice about. ME can only be partially cleaned on *some* processors.

It's also a very experimental area, which is subject to permanently damage your device if you don't know what you're doing.

There aren't really any *products* to recommend. The closest would be the librem laptops.

**Comment by beerisgood** [comment]
@tya99 Librem use Intel too. Even if they fully can circumstances ME, you have still the much Intel security problems.
And old CPUs: same problem with security holes aka Sidechannel attacks

So I still recommend AMD

**Comment by tya99** [comment]
> @tya99 Librem use Intel too. Even if they fully can circumstances ME, you have still the much Intel security problems.

Yeah I know they use Intel. Part of the reason they're 7th gen and not 8th gen is because of the related progress on disabling ME on 8th gen hadn't progressed as far as it needed to put that on the market.

> And old CPUs: same problem with security holes aka Sidechannel attacks
> 
> So I still recommend AMD

Some of the vulnerabilities haven't effected AMD this is true. However PSP is also not open so there could be something lurking there.

I guess in coming years we will find out, particularly as Ryzen is becoming popular in the desktop market. Unfortunately Intel is still **very** common in the mobile, server markets.

**Comment by atomGit** [comment]
[System76](https://system76.com/laptops) is offering several laptops with coreboot and their pop os - i'm waiting to hear from them about coreboot status regarding their Thelio towers
