### ISSUE TITLE
✨ Feature Suggestion | IzzySoft Applists \o/

### ISSUE THREAD

**Issue by Atavic** [privacytoolsIO/privacytools.io#849]
## Description: @IzzySoft is the person behind https://android.izzysoft.de/applists.php

I strongly suggest to look at his work, I use some of the apps featured with a yellow star that means **no known trackers \o/**

**Comment by IzzySoft** [comment]
And those are not "one-time lists", but updated regularly and automatically so no app should be behind for more than ~3 weeks (it's ~14k apps in those lists).

For the "bad ones" who "can't afford a star", worst trackers are listed (and linked to details). Similar in [my F-Droid repo](https://apt.izzysoft.de/fdroid), which even lists all libraries identified in an app.

Thanks for suggesting, @Atavic :smiley:

**Comment by libBletchley** [comment]
Useful resource.  What do we do with it?  Some ideas:
* PTIO creates a category for "directory services" which list other directories that have some privacy relevance (like IzzySoft and the [FSF directory](http://fsf.org/directory))
* For every tool evaluation we do, we reference the relevant izzy listing if there is one.
* This can go both ways - our findings can (and should) be linked to from the Izzy list as a review, which then further informs prospective users and also improves PTIO awareness.

**Comment by IzzySoft** [comment]
@libBletchley modules used in Playstore apps often differ from those in F-Droid apps. I know no exception to the rule that those my lists warn about are only contained in the former, but not in the latter (as they are proprietary and thus off-limits for F-Droid inclusion).

Modules might also differ between the Playstore variant and the APK available via my repo. But other than with Playstore (or F-Droid at that), my repo lists all contained libraries (including those modules) on its website for each app, so a visitor can look that up directly (via the link given).

My repo has slightly different "inclusion rules" than the official F-Droid repo, and can be considered something between "nonfree" in Debian terms and "testing" (i.e. apps preparing for F-Droid inclusions are available in my repo until they meet the stronger inclusion criteria of F-Droid; when they finally do, they apply for inclusion there and finally "move over" – a process that has happened for over 100 apps as of this writing). Stronger rules apply to apps dealing with sensitive data (e.g. password safes, health apps, apps for children, security apps); those are not permitted to have any "tracker" (so no ads, no analytics). For other apps, at least their count is limited (I don't take in apps with more than 4 – and usually kick out those with 6 or more (added via updates) on pruning runs).

----

That said: it's not feasible to "split the view" in my app listings to show which trackers are available in which place. It would simply become "unreadable". Also, some apps are available from other sources as well, like Aptoide (their "Apps" repo, which is the official curated one, is covered by my lists as well). As advice for "beginners" I'd suggest: count those trackers against the Playstore version, and consider the F-Droid version "privacy friendly"; if you use F-Droid, check the AntiFeatures with the F-Droid client (or website). Ignore the others (i.e. Aptoide and mine) unless you know how to deal with them.

For additional details:

* [details on my F-Droid repo](https://apt.izzysoft.de/fdroid/index/info)
* [details on my app listings](https://android.izzysoft.de/help.php?topic=applists) (including how to read them and what the icons etc. mean; I definitely need to update the screenshots there, but the text is up-to-date)

If there are further questions, don't hesitate to ask.

----

Oh, on the "what to do with it": I'm fine with the entire list – and gladly "link back" where possible. We should check on the "link back" when we know "to what" 😄 I often do that with pages from

* the security expert [Mike Kuketz](https://kuketz-blog.de)
* reports by [MobilSicher](https://mobilsicher.de/)

Two more candidates for the "directory services" category. As I am one of the authors at MobilSicher, and in personal contact with Mike (who also is an author there), I also gladly answer questions on those two if I can.

**Comment by Atavic** [comment]
Closed as it has been referenced above, feel free to reopen (but there are many issues opened).

**Comment by IzzySoft** [comment]
@Atavic Where has it been referenced? :eyes:

**Comment by Mikaela** [comment]
I am reopening as https://github.com/privacytoolsIO/privacytools.io/issues/338 doesn't name any concrete repositories that they wish to see on Privacytools.io.

**Comment by IzzySoft** [comment]
Thanks @Mikaela! Shall I link [my repo](https://apt.izzysoft.de/fdroid/index/info) there (which, as mentioned above, points out potential privacy implications (like trackers and other proprietary components)? Would fit better over there, where the issue explicitly deals with sources to download apps from. On the other hand, that issue already links here.

**Comment by five-c-d** [comment]
I like the IzzySoft applists, but I am unsure how to connect them with what privacyToolsIO aims to accomplish.  Most tools in the listings here are cross-platform, whereas IzzySoft is for android-only (unless I missed it).  There is also a pretty strong level of independent thinking required to use the IzzySoft listings, because e.g. almost every category has something with nine reviews and 99 downloads listed "above" a theoretically-equivalent apk which has 99k reviews and 9M downloads because the former is rated 4.9 stars and the later only 4.8 

That's not problematic for readership that is there to *research* tools and find what best suits their needs, but for more casual less-tech-savvy readership the top3 approach of privacyToolsIO tends to be more easy to stomach.  I would tentatively recommend that in the "RelatedLinks" portions of the privacyToolsIO listings, it could point to the corresponding section of the IzzyTools website?  VPN listing points to the IzzyVPN applist, etc.

**Comment by IzzySoft** [comment]
@five-c-d you got that right, it's Android specific (though cross-platform availability is usually pointed out, and also the "Remote Droide" section involves at least one OS on the computer in addition to Android). And download counts are not evaluated. As the associated help page (just check the upper-right corner for the help icon) states, it's ordered by ratings and votes (so "5@1" means rated 5 stars by 1 user, and unfortunately comes before "4.8@9.999" and "0@0" (the latter being the standard for apps only available at F-Droid or my repo, where there's no rating system). I couldn't find any better automated sorting algorithm, so I decided for KISS.

And yes, independent thinking is to be encouraged over being indoctrinated. Make your own educated decisions :smile:

**Comment by five-c-d** [comment]
Yesss... I must make my own decisions.... IzzySoft demands it.... I must obey.....   ;-) 

Suggest that you say "NA@NA" (with a popup or explanatory link), rather than 0@0 because I was under the mistaken impression it meant 'has zero reviews' rather than what it actually means.  Github stars should be listed when the project has a github-link as well, this is a fine alternative metric of "widely-vetted / popularity-level" methinks, and you can automate with queries to api.github.com -- all of the fdroid projects will have libre-licensed codebases, and most of the fdroid projects will have github stars, so this may alleviate the need to put good projects "at the bottom".  You will have to figure out a way to generate a 'combo-score' that estimates a rating-level from github stars and/or review count and/or playstore stars-rating but I think that even a simplistic algorithm would be an improvement on "0@0" 

> reference the relevant izzy listing

The problem here is that sometimes there is a disconnect... privacyToolsIO has one category for joplin+standardNotes+turtl whereas izzySoft has two categories, https://android.izzysoft.de/applists/category/named/office_office#group_107 for markdown editors like joplin, and https://android.izzysoft.de/applists/category/named/office_notes for note-taking apps like turtl + standardNotes ... though arguably all three belong in both categories.  

The other problem also exists, izzyDroid has a large "text encryption" page with a subcategory for messengers-with-crypto here, https://android.izzysoft.de/applists/category/named/security_textencrypt#group_868 but privacyToolsIO splits them into IM and VoIP categories at the moment.  

@IzzySoft ...are you amenable to altering how you categorize, so that privacyToolsIO categories and your categories are more of a unified ontology than currently is the case, i.e. rather than the differing and incompatible categorization-systems which are in place at the moment?  It would also work to have privacyToolsIO change *their* categories to match izzySoft, of course  ;-)   But I'm going to be blunt and say that I think privacyToolsIO is more well-known in terms of mindshare in 2019... judging by alexa pagerank at least... which of course, does not mean that it has **better** categorization system, obviously, just that, more endusers are vaguely familiar with the privacyToolsIO way of splitting things up, than with the izzySoft way of splitting things up.

**Comment by IzzySoft** [comment]
> Yesss... I must make my own decisions.... IzzySoft demands it.... I must obey..... ;-)

:rofl: If you wish to interprete it such… I give Android courses for beginners at several of our "adult schools" (called "Volkshochschule" in Germany). I always tell the participants I show them both sides of the medal (usefulness of a certain functionality as well as its risks) so they can make an educated decision – but I can't decide *for them.* I can however decide *for me,* and when they ask tell them what *that* decision was.

> I was under the mistaken impression it meant 'has zero reviews'

Well, that's correct in a sense: when from Playstore, it has zero reviews because nobody reviewed it. When from F-Droid, it has zero reviews because there are none. And it's an integer field in the database in both cases, so n/a doesn't fit. As it must match both, I neither can put in "-1". Sure, I could render it as "-/-" in the lists when it's only available from sites not supporting reviews. Will think about that.

> Github stars … You will have to figure out a way to generate a 'combo-score'

Nice idea – but for one it would clutter the list even more – and for another one, this is a one-man-show, and I have a lot of other tasks – so no idea when I should implement that…

> are you amenable to altering how you categorize, so that privacyToolsIO categories

In a very limited way. I e.g. already considered splitting out the messengers from the text encryption page (to make them easier to spot), but I certainly lack the time for a full reorganization. *would also work to have privacyToolsIO change* and then meet in the middle, yeah. I've got no idea how Alexa page ranking works (i.e. how they get their numbers) and whether not including any external sources (especially no Javascript) in my sites makes it harder for them. Be that as it may: I can only spend so much time on things.

**Comment by dngray** [comment]
Closing in preference to https://github.com/privacytoolsIO/privacytools.io/issues/1800

**Comment by IzzySoft** [comment]
@dngray that issue does not even mention above referenced app lists. Just saying, you might wish to check the link :wink:

**Comment by dngray** [comment]
We won't be using the above list.

The shortlist will be a verified list by us of applications that are in the official F-droid repository.

**Comment by IzzySoft** [comment]
I see – then I misinterpreted your "closing in favor of" as meaning the other issue covers this one – while you meant "we use the other list instead of the one proposed here". Thanks for clarifying!
