### ISSUE TITLE
✨ Feature Suggestion | Better Browser Addons Section

### ISSUE THREAD

**Issue by JonahAragon** [privacytoolsIO/privacytools.io#852]
## Description:

We recommend, in an experimental capacity at least, a Chromium based browser (Brave). We also recommend a lot of extensions that are available on *any* browser, not just Firefox. Therefore, we should rename the "Excellent Firefox Privacy Add-ons" section on the site to just "Privacy Browser Extensions" and include buttons that link directly to the download page for either Firefox or Chrome for each extension.

**Comment by five-c-d** [comment]
My understanding is that as of December 2018 the brave4desktop codebase has finished transitioning away from the Muon-fork-of-Electron and is now based on the upstream chromium project, just like the brave4android has been architected for some time now.  Therefore I believe that chromium-compatible-extensions should "just work" but they do need to be *chromium*-compatible (which I'm pretty sure is **not** quite 100% identical to chrome-compatible).  

https://support.brave.com/hc/en-us/articles/360017909112-How-can-I-add-extensions-to-Brave- claims that 'most' chromium-compatible extensions in the ChromeStore will work on braveBrowser.  There is a first-draft-whitelist of 3800 extensions -- https://github.com/brave/brave-browser/issues/951#issuecomment-443255980 -- which passed a basic smoke-test.  They do not have their own extensionStore yet, but this is probably planned 'eventually' to occur.  https://github.com/brave/brave-browser/issues/637#issuecomment-425966213  

See also this tracking-issue about chrome://extensions where the installed ones would get listed & configured == https://github.com/brave/brave-browser/issues/1178#issuecomment-455055710  One pretty-severe limitation is that when in Tor-mode and/or private-mode, extensions 'suddenly' do not really work right anymore!  https://github.com/brave/brave-browser/issues/2761#issuecomment-453375541  There is ongoing effort to solve that but nothing trumpeted as a successful resolution, yet.  One not-as-severe but painful limitation is that extensions, once installed, are auto-update with no way to switch to manual-approval-of-each-extension-update, nor to selectively disable auto-updates on a per-extension basis.  https://github.com/brave/brave-browser/issues/3811

ChromeApps also are currently causing a crashing-bug, but it seems to have a workaround of sorts since the crash is 'handled' somewhat-gracefully?  https://github.com/brave/brave-browser/issues/3766#issuecomment-476893075

**Comment by blacklight447-ptio** [comment]
this should be more trivial as most browsers all use the web extentions model, which makes most plugins cross browser.

**Comment by JonahAragon** [comment]
This was resolved in #1149
