### ISSUE TITLE
✨ Feature Suggestion | Split the recommendations for regular and privacy concious users

### ISSUE THREAD

**Issue by Mikaela** [privacytoolsIO/privacytools.io#880]
## Description:

> I think it's time to split content on privacytools.io into two sections:
>
>    Aimed at regular users who are looking for an easy to use alterantive for lets say "WhatsApp" and we could for example suggest "Telegram" with some notes.
> 
>    Aimed at very privacy conscious users who want to walk to extra mile, join discussions like this one.
> 
> We can't please both groups with the same recommendations.

Suggested @BurungHantu1605 at https://github.com/privacytoolsIO/privacytools.io/issues/779#issuecomment-481921674

**Comment by libBletchley** [comment]
I've moved my reply from [that thread](https://github.com/privacytoolsIO/privacytools.io/issues/779#issuecomment-482096319) to here where it's relevant:

----
@BurungHantu1605 
> I think it's time to split content on privacytools.io into two sections:
> 
> 1. Aimed at regular users who are looking for an easy to use alterantive for lets say "WhatsApp" and we could for example suggest "Telegram" with some notes.
> 2. Aimed at very privacy conscious users who want to walk to extra mile, join discussions like this one.

Both kinds of users are ***equally*** entitled to avoiding mass surveillance.  The difference likely motivating your comment for the separation is that they are unequal in technical competency.  It should be addressed in a careful way.

> We can't please both groups with the same recommendations.

Some categories *could* serve both groups with the same recommendations, others not.  The separation may be a necessary evil in some categories, but should be avoided when possible because all such cases would entail normies getting a reduced privilege to avoid mass surveillance.

The problem with introducing this split for every single category is that it would create a counter-productive temptation for PTIO to let feature richness *needlessly* undermine privacy.  For example, specifically in the context of #779, neither advanced users nor simple users need to give up as much privacy as Signal requires.  But a "simple user endorsement" could easily become so relaxed that Signal would be endorsed despite other user-friendly options that avoid mass surveillance to a greater extent.

## communication tools are special - more complex in this case
Most of the categories do not deal with p2p communication.  But the IM and voice categories have an extra complexity: nerds need to communicate with non-nerds.  How can I talk to my mom if she is getting different advice?  Will I have to say "mom, sorry I don't call home as much anymore, but @BurungHantu1605 recommends incompatible tools for us"?

This touches on the viral privacy abuse problem (1.vii).  Walled-gardens are totally structured to conquer the market of normal non-expert masses, not nerds.  So privacy becomes marginalized and nerds get isolated.  IOW, when it comes to communication tools, a split endorsement (if not done carefully enough) could support viral privacy abuse.

## PTIO could become a filter bubble
Another possible problem with splitting the whole page and all categories is that users with a misplaced low confidence will be guided away from challenges that improve them, or simply tools that they actually can handle without issue, because the better options won't even be in sight (depending on how it's done).

## nerds are hard to cater for
Is it even worth it to try to make recommendations to highly advanced nerds?  When nerds work securely, configuration becomes as relevant as the tool.  One tool may be better than another out of the box in one circumstance, but the lesser tool is better if you sandbox it in a firejail and isolate the uplink to a tor middlebox, perhaps compile it with different options for a specific use-case, etc.. Is PTIO up to the task of making a competition out of complex installations and configurations?

Signal is a disaster out of the box, but maybe someone would travel to Czech for a burner phone, compile the code, use a special ungoogled ROM, etc, purely to get notifications from the Haven app.  It's hard to give general advice to advanced users with specific needs.

## possible approach
If a particular endorsement is a tool that is not user-friendly, it could be tagged as such as a warning to simple users, and we could take care to ensure that every category has at least one user-friendly endorsement.  I suggest an icon of a big brain for the advanced tools, because those on the fence about what they can handle may be encouraged to try the big-brain tool.  And yet if they can't handle it in the end they won't be frustrated with PTIO b/c they were sufficiently warned about what they were getting into.

**Comment by Meteor0id** [comment]
> We can't please both groups with the same recommendations.
Quite debatable.

I think the solution is to start with a few paragraphs of summing up the basics, and than continue onwards into details. Like well written articles should always do.

Privacytools.io should always provide a little more info than a user was looking for. Privacytools.io also has a job of educating people; pushing them to learn more, understand privacy related criteria more in dept. That is perhaps the greatest service privacytools.io is providing.

**Comment by 4udr4n** [comment]
Why not provide a good/better/best tiered system for recommendations?

Good would be solutions such as Signal, Brave, Protonmail, Startpage - all multi-platform alternatives which vastly increase privacy over the usual suspects without increasing complexity or cost. So long as they are framed as being improvements but not perfect, they should suffice to help newcomers without putting off those with more knowledge.

Better might be Firefox + ghacks+/12bytes, LineageOS, Debian, Email with catchall etc. All further improvements but requiring investments in knowledge, maintenance and/or money. Still imperfect but worthwhile.

Best probably needs a lot of context around threat models. Here we would find Tor, Qubes, GrapheneOS, Self hosted services, Briar.

Many of the issues here are ideological, with privacy advocates/experts not wishing to recommend what they see as and what may in fact be flawed tools and approaches. This is admirable, but as a user on the matrix chat is fond of saying, sometime it is important not to let the perfect be the enemy of the good.

**Comment by five-c-d** [comment]
Potentially related is #896 about having a /summary page with a nice top3-oriented overview aimed at readership that does not have a lot of time to spend.  Should the /summary also be squarely aimed at endusers that want increased privacy without much cost&complexity?  Possibly yes, though to me these are slightly different things (being short on time does not mean being short on expertise and tech-savvy-ness needed to manage the complex tools).  

group|'good'|'better'|'best'
---|---|---|---
browser| brave | firefox<br />(ghacks.js) |torBrowser
comms|signalapp|email<br />(selfhost)|briar
laptop|osx|debian|qubes
phone|iOS|lineageOS|grapheneOS <br />(or librem5)  

No, to me that is the wrong approach.  For starters, briar is not even listed on privacyToolsIO *at all* (and I don't think it is TheBest either), nor is grapheneOS (though it is proposed at least now), ditto for librem5 which I added (since it is not yet launched).  People that use signalapp with all the bells and whistles are going to be getting close to the 'best' privacy in some sense... but this requires a significant amount of work because you have to combine it with acquiring a phone-num not linked to financials/identity, some kind of container-crypto like samsungKnox or lineageOS secondary-system-profiles, non-default addressbook app & vkeyb, and a bunch of off-by-default settings and optional high-security stuff.  Even when you go through all that setup-hassle though, it is still signalapp and thus fairly easy to use and well-vetted and so on.  

To  me, that is the primary differentiator:  hassle invested, and privacy ROI therefrom.  Services which don't provide a significant amount of privacy, relative to other available options in the segment, should simply *not be listed* on privacyToolsIO at all.  Services which in theory provide a significant amount of privacy, but are not well-vetted (because they are too new and/or too unknown), should also just not be listed until they are "reasonably" field-vetted... and this differs by category, an OS or a browser needs more field-vetting than a calendar-sync or a note-taking app does.  

subgroup|hassle: 🧙|hassle: 🧙🧙|hassle: 🧙🧙🧙|
---|---|---|---
browser: ESR| torBrowser <br /> sans TorNetwork | torBrowser <br /> +noscript | torBrowser <br /> +multi VPN
browser: gecko| firefox <br /> +3 addons| firefox <br /> +6 addons| firefox  +9 addons<br />+ghacks+orbot
browser: chromium| brave | brave <br /> +noscript | ungoogledChromium <br />+orbot
msgr:  signal protocol | signalapp <br /> w/cell num<br /> +defaults | signalapp <br /> w/2ndary num<br /> +disappear | signalapp <br /> w/anon'd num<br /> +max'd out
msgr:  SMTP protocol | protonmail | protonmail <br /> +expiring w/<br /> blank subjects | selfhost MTA <br />+neomutt 
OS: desktop | qubes<br /> +osx | qubes<br /> +debian  | qubes<br /> +tails 
OS: mobile | iOS<br /> +tweaks <br />(or samsungKnox) | lineageOS <br /> +tweaks <br /> (or /e/) | grapheneOS <br /> sans playStore <br />(or librem5)  

>  Many of the issues here are ideological

Yes  :-)   The question is, how do we square what the listing present, with the various types of threat-models and privacy-purist viewpoints, while not accidentally making the webpages so dense with eye-glazing info that everyday endusers tune out?  

>  let not the perfect be the enemy of the good

Fully agree.  I think we can go far, if we have a portion of the site which concentrates on "here are some low-hassle tools you can put to use immediately" and then a bit deeper in we provide some details pros-n-cons which clue people in on advanced tools that come with higher hassle (and require a higher degree of tech-wizardry to install/use/etc).

**Comment by blacklight447-ptio** [comment]
@five-c-d Just to make it clear, we should absolutly NOT under ANY circumstance recommend people to use a VPN with tor, it gives  a false sense of security, and can harm users.

**Comment by five-c-d** [comment]
We should probably split the discussion about tor+vpn versus vpn+tor versus just plain tor, away from the discussion about recommendation-listing-splitting  :-)  

<details><summary>some links on torBrowser with VPN usage</summary><p> 

*  https://protonvpn.com/blog/tor-vpn 
*  https://www.bestvpn.com/guides/using-vpn-tor-together
*  https://www.deepdotweb.com/jolly-rogers-security-guide-for-beginners/combining-tor-with-a-vpn/

Some people recommend it... including VPN providers  ;-)  Some people definitely don't.  

*  https://www.reddit.com/r/TOR/comments/9q3len/is_using_a_vpn_with_tor_a_bad_idea/
*  https://www.reddit.com/r/TOR/comments/960syc/why_is_a_vpn_considered_bad_in_combination_with/
*  https://www.reddit.com/r/TOR/comments/5qmqw4/should_i_be_using_a_vpn_with_tor/

Tor doesn't specifically say that VPNs are a *terrible* idea, just that, the purpose of the VPN is distinct from Tor's purpose (whether you use a VPN boils down to whether you trust your ISP/dataplan more or less than you trust the vpn-provider).  https://2019.www.torproject.org/docs/faq.html.en#IsTorLikeAVPN 

</p></details>

But yeah, that is specifically why I put torBrowser+multiVpn in the triple-wizards-of-skill-and-hassle category:  because unless you are ***very*** clear on exactly what you are doing, and willing to go through a huge amount of r&d + setup testing, that is a bad thing to attempt.  And some people are ideologically against such combos, for want of a better term to describe the stance that "under no circumstances combine the two technologies".  

For the same sort of rationale, I similarly would not recommend command-line Mutt and self-hosting your own MTA to **anybody** not willing to undergo a gigantic amount of pain and suffering, to actually get their mail through to normal SMTP endusers like gmail/outlook/etc.  Same deal with ungoogledChromium, there are no official builds, so if you want to use it, you really need to hand-compile, which is three-wizards of hassle for sure.  GrapheneOS requires that you buy a Pixel at the moment, or hand-compile self-audit.  Getting a *truly* anonymized telco-num is extremely difficult for use with signalapp, etc.  GHacks-user.js should not be applied by random endusers that don't know what they are doing, and so on.

**Comment by blacklight447-ptio** [comment]
It is says that one can use it in case someone cannot connect to tor, but it should absolutly not be used for increasing anonimity, it does not help, it only slows the network down, and even if we give it as an option(which we shouldn't) it should only be presented as a way to connect to tor where bridges don't work. Advicing To use a vpn with tor is a dangerous idea and should not be done. https://forum.privacytools.io/t/why-you-should-not-use-a-vpn-with-tor/182

(this is a person who works daily with paul syverson at the naval research lab, one of the original designers of the tor network.

**Comment by five-c-d** [comment]
> I don't see a reason to discuss it further sinc it is already an esthablished fact that tor should not be used together when we have bridges

That is your position, yes  :-)   But it is NOT what privacyToolsIO listings, actually say.  They list, very first thing after the intro, VPNs.  

TorBrowser, and other TorNetwork tools, are waaaay down the /classic portion of the page.  

> My point here is that any attempts to encourage user to use a vpn should be shutdown as fast as possible as it can really harm users.

Right.  And **my** point is that, privacyToolsIO encourages VPN usage.  Prominently!  So you should open a discussion, not say you consider it closed and pointless to discuss further.  Please open it **somewhere else** rather than here in the thread, about whether to split off recommendations for everyday endusers, and recommendations for extra-privacy-conscious endusers.  And maybe, versus super-duper uber-privacy-conscious folks.  

It is pretty pertinent, in some sense, to this thread, however. Everyday endusers **will not** put up with TorBrowser, because they want a browser that works 99.999% of the time like BraveBrowser, or 99.99% of the time like Firefox, and they don't think 99.9% of the time is reliable enough.  Everyday endusers are not going to be using TorNetwork, for hardly anything, because it is too much hassle for them.  What everyday endusers **will** use, though, is protonVPN ... because it doesn't cost them anything, they can still make signalapp cryptocalls even when using the VPN (something almost impossible to make work via TorNetwork unless they are willing to use async voiceNotes rather than quasi-realtime VoIP because of the jitter-problem).  Can everyday endusers be taught to use meek bridges that aren't baked into Tor, at gunpoint?  Yes-in-theory.  If their threat model does NOT include actual guns pointed at their heads, however, then the answer is probably no-in-practice.    

VPNs that don't require payment of any fees, are hassle=🧙.   Nice boost versus doing nothing.  Using the TorBrowser where you can, and using VPN whenever you are **not** using TorBrowser or another TorNetwork piece of software, is hassle=🧙🧙.  Figuring out in your head, on the fly, the exact consequences of using Tor+VPN, or of using VPN+Tor, or of using VPN1+VPN2+Tor, or bridge+Tor, or VPN+bridge+Tor, or various other exotic combinations such as where you travel to a public wifi location but access it with a pringles-can wardriving antenna from afar to help anonymize your location... that kind of stuff is very firmly in the zone I call hassle=🧙🧙🧙.  

If you tell everyday endusers "oh just use Tor for everything and never login to something with your legal name or buy anything with a credit-card just get a fake ID and use only Monero and tumbled bitcoin from now on" they are going to suddenly LOL rather than suddenly BTC.  Then they will go back to using Chrome and Windows10, whilst shaking their heads.  We need good recommendations for people just beginning to realize they might value privacy, people that have never *heard* of Tor yet.

**Comment by blacklight447-ptio** [comment]
@five-c-d You can use tor browser safely and login, tor browser gives every site its own circuit and seperated state. Also you VASTLY under estimating the current capabilties of the tor network, latency is only about 3 seconds these days. And I have been able to watch 1080p videos on it on frequent basis. So to recommend the heavily limited free protonvpn servers over tor for speed reason, is rather stupid. 

In my opinion, we should shove the VPN all the way down, and a big section explaining about how Tor works, how it helps you, and why I should generally be preffered over a VPN. Regarding "figuring out" of Tor its simple: use Tor browser normally. Doesn't it work? Use a bridge with the included instructions which are simpel and easy to follow. A lot easier to follow then the ENORMOUS rabbit hole, that is known as the VPN provider industry.

**Comment by dngray** [comment]
I think we can close this.

The site has moved on to having a criteria, and listing the best options which have reasonable user experience and privacy expectations. There's no point in recommending unusable or alpha-quality products.
