### ISSUE TITLE
💬 Discussion | Remove Non-Free Search Engines

### ISSUE THREAD

**Issue by gjhklfdsa** [privacytoolsIO/privacytools.io#912]
Most of the recommended search engines on the privacytools.io website are [non-free](https://www.wikipedia.org/wiki/non_free_software).
Including [StartPage](https://www.wikipedia.org/wiki/Startpage.com), [DuckDuckGo](https://www.wikipedia.org/wiki/DuckDuckGo), and [Qwant](https://www.wikipedia.org/wiki/Qwant).

**Despite there being several amazing [free software](https://www.wikipedia.org/wiki/Free_software) search engines:**
_Open issues/PR:_ 
- Sarchy (#907)
https://github.com/agnelvishal/yacy_search_server

_Closed issues/PR:_
- Gigablast (#700)
https://github.com/gigablast/open-source-search-engine

_Accepted Issues/PR:_
- Jive Search (#701)
https://github.com/jivesearch/jivesearch
- Yacy (#702)
https://github.com/yacy/yacy_search_server
- SearX
https://github.com/asciimoo/searx

Related to #699 

Why is this the current status of the privacytools.io search engine section?
Please discuss! :)

**Comment by blacklight447-ptio** [comment]
While I like open source, I doubt how much actule difference this will make. How can we verify that the one hosting the search engine runs this code?

**Comment by gjhklfdsa** [comment]
> While I like open source, I doubt how much actule difference this will make. How can we verify that the one hosting the search engine runs this code?

LibreJS, it currently has limited support among search engines but many have made some progress to support it or have open issues.

Jive Search: https://github.com/jivesearch/jivesearch/issues/89

Yacy and Sarchy: https://github.com/yacy/yacy_search_server/pull/56

Gigablast (no response): https://github.com/gigablast/open-source-search-engine/issues/146

Many are also [self-hostable](https://www.wikipedia.org/wiki/Self-hosting) like [SearX](https://github.com/asciimoo/searx) which has an instance run by [PrivacyTools.io](https://archive.fo/m9keo) and one ran by [Disroot](https://archive.fo/cpY26).

**Comment by JonahAragon** [comment]
It should be noted that while we prefer open source applications in general, it is not a requirement to be listed. We list the best overall tools in each category because if they are privacy-respecting and *people will use them*, then they are better for most users.

Not that we can't discuss this issue, but "because they're not open source" can't be the *only* reason we remove tools. Open source alternatives need to either be significantly better, or the closed source ones we recommend need to have significant real-world or privacy-related drawbacks.

**Comment by FrostKnight** [comment]
I use searx, but as long as they don't spy/have severe issues, I see no problem with keeping duckduckgo. Startpage and ixquick are different though, because I don't know much code they use that is actually freely licensed.  That being said, duckduckgo isn't completely free either.

**Comment by gjhklfdsa** [comment]
@JonahAragon To chime in a bit here.
How many reasons are needed to remove something? If not just one?

Cuz, we don't list VPNs in the United States and discourage utilization of US services.
Yet DuckDuckGo is US based and doesn't hide you searches at a local level.[1](https://choosetoencrypt.com/search-engines/duckduckgos-biggest-privacy-flaw/)

Plus services like Qwant reserve the right to change their ToS at any time.[1](https://tosdr.org/#qwant)

Privacytools.io also does not recommend centralized social networks on the premise it gives one entity to much power.  However, non-free search engines are inherently not self-hostable. 
While networks like SearX and JiveSearch promote healthy competition between hosts.

**Comment by atomGit** [comment]
**gigablast** is dead - unmaintained for a long time
**yacy** is an excellent idea i think (future is p2p apps?), but at this time it's essentially useless as a search engine since it's index is so small
**searx** is the best of the meta search engines IMO, but it relies largely on the commercial indexes (google, etc., though you can adjust that)

the other 2 i have to check out - thanks for mentioning them

if anyone's interested, i keep a list of (hopefully) privacy-centric search engines...
[Alternative Search Engines That Respect Your Privacy](https://12bytes.org/articles/tech/alternative-search-engines-that-respect-your-privacy)

**Comment by gjhklfdsa** [comment]
@atomGit I'll have to disagree with you on Yacy.
However, 2+ free software search engines are more than enough. 

SearX is great, however I prefer Jive Search's UI.
More sleek IMHO. 

I used SearX for a long time. :)

**Comment by atomGit** [comment]
maybe their index has gotten significantly bigger since i last checked - i'd like to test again, but the instance at yacy.snopyta.org is down - do you know of another instance? or, better yet, a list of instances? or perhaps you're running an installed version?

**Comment by gjhklfdsa** [comment]
@atomGit https://yacy.net/en/Searchportal.html

**Comment by BurungHantu1605** [comment]
https://github.com/privacytoolsIO/privacytools.io/issues/912#issuecomment-491544094
