### ISSUE TITLE
🆕 Software Suggestion | PureOS, Librem

### ISSUE THREAD

**Issue by youngbasta** [privacytoolsIO/privacytools.io#932]
## Basic Information
A privacy and freedom respecting company. Has their own 100% libre software, and hardware if you buy their laptops or phone. Also their own OS, called PureOS.

**Name:**
PureOS
Librem5
Librem13
Librem15

**Category:**
Operating System

**URL:**
https://puri.sm
https://pureos.net/

## Description
I think at least the PureOS OS should be featured in the list as it is the same as Trisquel

**Comment by blacklight447-ptio** [comment]
Wasn't pure os basically with a skin over it?

**Comment by youngbasta** [comment]
Over what?

**Comment by five-c-d** [comment]
> Wasn't pure os basically Debian with a skin over it?

Sort of, it is a libre-only variant.  From the original post == 

> PureOS OS should be featured in the list as it is the same as Trisquel

Currently the desktop-OS-listings have Qubes + Debian + Trisquel as top3.  

The proposal here, is to have PureOS added to the WorthMentioning, and it would say something like "PureOS is a respin of Trisquel/Debian, made by Puri.sm the social-non-profit, which also produces Librem15 + Librem13 laptops, etc etc".   

Related:  proposal to add a new HardwareCategory https://github.com/privacytoolsIO/privacytools.io/issues/904

**Comment by blacklight447-ptio** [comment]
@five-c-d From what i understood, debian was also fully libre, with only a repo that you can optionally enable for closed source stuff?

**Comment by gjhklfdsa** [comment]
Just to be clear, Purism's laptops are far from fully free.
**Examples:**
[Bluetooth](https://www.wikipedia.org/wiki/Bluetooth) requires non-free drivers
https://forums.puri.sm/t/does-bluetooth-work-if-no-any-idea-when/5612

[Intel ME](https://www.wikipedia.org/wiki/Intel_Management_Engine#Claims_that_ME_is_a_backdoor) despite being partially removed via [ME Cleaner](https://github.com/corna/me_cleaner) is still alive.
https://puri.sm/learn/intel-me/

[Intel FSP](https://www.intel.com/content/www/us/en/intelligent-systems/intel-firmware-support-package/intel-fsp-overview.html) is still active
https://puri.sm/learn/freedom-roadmap/

And many other components have non-free firmware:
https://forums.puri.sm/t/purisms-purist-build/4739/2

**Comment by gjhklfdsa** [comment]
> Wasn't pure os basically Debian with a skin over it?
> 
> EDIT: words

No, it is generaally more geared towards end users while Debian is consider a universal OS.

IMHO, trying to meet everyone's needs is impossible. Although, I do run Debian.

As I understand it, PureOS is also FSDG certified and makes it a bit easier to install apps with their PureOS app store.

Many repos like `non-free` and `contrib` are also missing from PureOS.
They also refuse to recommend installing non-free firmware.

**Comment by gjhklfdsa** [comment]
I would appreciate GnewSense to be listed as a fully free'd alternative to Debian.
https://www.wikipedia.org/wiki/GNewSense

**Comment by five-c-d** [comment]
> appreciate gNewSense to be listed 

Please open a different thread, so we don't get side-tracked from PureOS... but it looks like the last gNewSense release was in 2016, and they have the same goals as Trisquel, so if you do propose it, please explain why gNewSense is superior to seemingly-very-similar Trisquel? 

So basically, for <a href="https://www.privacytools.io/operating-systems/">desktop-OS listings</a>, we have:  

*  top3 == Trisquel, 100% libre with no binary blobs (same as gNewSense basically but non-dormant), about like Replicant for smartphones -- can still be firmware in the device e.g. the BIOS/UEFI.   Personally used by RMS, as of 2015 at least, FSF certified. 

*  proposed == PureOS, 100% libre userland (correct me if I'm wrong) and LibreBoot on their hardware devices, but some binary blobs for specific firmware, about like LineageOS for smartphones with a modded cpu-microcode to cripple baseband-spying, roughly?  Lists privacy as a goal of the distro, however, and not sure Trisquel nor gNewSense do that, so maybe more like /e/ Foundation than like typical LineageOS.  Not quite FSF certified, but working that direction, and Librem5 might be FSF-listed. 

*  top2 == Debian, pretty-libre userland but kernel has binary blobs, and optional multiverse-equivalent repo contains non-libre software offerings.  Mainstream server-side linux distro, not a niche product like the others.  Something that an everyday enduser could conceivably install and utilize themselves, though it is a huge leap from win10.  Debian is therefore like a more-mature LineageOS, which tends to work on almost any desktop-hardware (and a lot of non-desktop-hardware also), and is aimed at normal endusers though still tends to be just Linux-savvy folks running Linux-for-the-Desktop, in practice. 

*  top1 == Qubes OS, extremely strong concentration on compartmentalization/security, not anything special that is specifically about privacy, but can run in windows (i.e. something an everyday enduser might already be familiar with), and give a *strongly* isolated set of VMs to segment the highly-private from the less-private from the really-ought-to-be-separate stuff.  Also runs great on Debian, once the enduser gets more serious and makes the leap.  There is no equivalent-to-QubesOS for smartphones, unfortunately, unless you count the secondary-android-system-profiles and Samsung SecureFolder things, as kinda-similar-ish.  

And I was mis-remembering, Trisquel is from the ubuntu 16.04 LTS kernel (libre-variant sans binary blobs), and thus one hop further downstream from debian.  

Worth mentioning:  
*  OpenBSD which is the most-security-oriented BSD flavor, 
*  Arch&Parabola which is a rolling-release distro for people who prefer that to DebianUnstable (cf Manjaro versus DebianTesting), 
*  Whonix which is the anonymity-oriented Debian respin, 
*  Subgraph (alpha-phase still) which is a QubesOS and Whonix combo-competitor 

If we were to add PureOS, it would likely appear above alpha-Subgraph but below Whonix.  How many people run PureOS that are not owners of laptops from Purism, would be my main question... if it is a very small percentage, then I would rather just list the Librem15+13 over in the hardware-section, since PureOS would mostly be a debian-for-Librem-laptops respin.  https://distrowatch.com/table.php?distribution=pureos  mentions some problems with wifi support (lack of binary blobs presumably) and recent instability.  

> debian was also fully libre

Well, there is fully-libre, and then there is FULLY-libre  :-)   Debian is libre-software, and they are strongly committed to that worldview, but they make some pragmatic exceptions, because they intend to be a universal OS for all platforms/endusers/situations.  Purism is more purist, and is attempting to eliminate all non-libre software from being mentioned, and gradually cut out whatever can be cut out.  Trisquel is purist even when that makes the distro unusable, though even they cannot get rid of Intel ME is my understanding.   It is possible to run a purist debian, but by default, the kernel has binary blobs, the multiverse-equivalent repos are easy to access, and the helpdocs mention things from time to time.  Qubes is mostly-GPLv2 but purposely runs fine on windows-boxen, i.e. not very purist at all.

**Comment by gjhklfdsa** [comment]
> > appreciate gNewSense to be listed
> 
> Please open a different thread, so we don't get side-tracked from PureOS... but it looks like the last gNewSense release was in 2016, and they have the same goals as Trisquel, so if you do propose it, please explain why gNewSense is superior to seemingly-very-similar Trisquel?
> 
> So basically, for [desktop-OS listings](https://www.privacytools.io/operating-systems/), we have:
> 
>     * top3 == Trisquel, 100% libre with no binary blobs (same as gNewSense basically but non-dormant), about like Replicant for smartphones -- can still be firmware in the device e.g. the BIOS/UEFI.   Personally used by RMS, as of 2015 at least, FSF certified.
> 
>     * proposed == PureOS, 100% libre userland (correct me if I'm wrong) and LibreBoot on their hardware devices, but some binary blobs for specific firmware, about like LineageOS for smartphones with a modded cpu-microcode to cripple baseband-spying, roughly?  Lists privacy as a goal of the distro, however, and not sure Trisquel nor gNewSense do that, so maybe more like /e/ Foundation than like typical LineageOS.  Not quite FSF certified, but working that direction, and Librem5 might be FSF-listed.
> 
>     * top2 == Debian, pretty-libre userland but kernel has binary blobs, and optional multiverse-equivalent repo contains non-libre software offerings.  Mainstream server-side linux distro, not a niche product like the others.  Something that an everyday enduser could conceivably install and utilize themselves, though it is a huge leap from win10.  Debian is therefore like a more-mature LineageOS, which tends to work on almost any desktop-hardware (and a lot of non-desktop-hardware also), and is aimed at normal endusers though still tends to be just Linux-savvy folks running Linux-for-the-Desktop, in practice.
> 
>     * top1 == Qubes OS, extremely strong concentration on compartmentalization/security, not anything special that is specifically about privacy, but can run in windows (i.e. something an everyday enduser might already be familiar with), and give a _strongly_ isolated set of VMs to segment the highly-private from the less-private from the really-ought-to-be-separate stuff.  Also runs great on Debian, once the enduser gets more serious and makes the leap.  There is no equivalent-to-QubesOS for smartphones, unfortunately, unless you count the secondary-android-system-profiles and Samsung SecureFolder things, as kinda-similar-ish.
> 
> 
> And I was mis-remembering, Trisquel is from the ubuntu 16.04 LTS kernel (libre-variant sans binary blobs), and thus one hop further downstream from debian.
> 
> Worth mentioning:
> 
>     * OpenBSD which is the most-security-oriented BSD flavor,
> 
>     * Arch&Parabola which is a rolling-release distro for people who prefer that to DebianUnstable (cf Manjaro versus DebianTesting),
> 
>     * Whonix which is the anonymity-oriented Debian respin,
> 
>     * Subgraph (alpha-phase still) which is a QubesOS and Whonix combo-competitor
> 
> 
> If we were to add PureOS, it would likely appear above alpha-Subgraph but below Whonix. How many people run PureOS that are not owners of laptops from Purism, would be my main question... if it is a very small percentage, then I would rather just list the Librem15+13 over in the hardware-section, since PureOS would mostly be a debian-for-Librem-laptops respin. https://distrowatch.com/table.php?distribution=pureos mentions some problems with wifi support (lack of binary blobs presumably) and recent instability.
> 
> > debian was also fully libre
> 
> Well, there is fully-libre, and then there is FULLY-libre :-) Debian is libre-software, and they are strongly committed to that worldview, but they make some pragmatic exceptions, because they intend to be a universal OS for all platforms/endusers/situations. Purism is more purist, and is attempting to eliminate all non-libre software from being mentioned, and gradually cut out whatever can be cut out. Trisquel is purist even when that makes the distro unusable, though even they cannot get rid of Intel ME is my understanding. It is possible to run a purist debian, but by default, the kernel has binary blobs, the multiverse-equivalent repos are easy to access, and the helpdocs mention things from time to time. Qubes is mostly-GPLv2 but purposely runs fine on windows-boxen, i.e. not very purist at all.

Common misconception, Ubuntu is based on Debian. Trisquel is based on Ubuntu.
Therefore much of the code is the same. However, much of the code included in Ubuntu or Trisquel and not Debian is not included in GnewSense.

As for the report on when it was last released. I can only say that Debian doesn't make a new major release but every few years. I would assume this is the reason for them not having a newer version

**Comment by blacklight447-ptio** [comment]
lets now go over this question, what would Pure OS bring to the table, when its compared to other os's we already list.

**Comment by youngbasta** [comment]
It's pretty sad how you guys make comments on this privacytools.io git page and so shouldn't you already know what PureOS is? Atleast what Purism is.

FYI, PureOS isn't just a spin-off of Debian, sure it is based on Debian, it has binary-blobs removed, but most importantly, it comes with privacy features preinstalled like for example- DuckDuckGo out-of-the-box, uBlock Origin and HTTPS.  It is basically orientated around privacy, security and freedom. 

It shouldn't just be mentioned in the WorthMentioning list. It should take the place of Trisquel and climb the ranking list above Debian tbh. But I'd like to keep Debian #2 and PureOS #3. While Triquel takes the place in the WorthMentioning list or just the 4th place.

**Comment by blacklight447-ptio** [comment]
@youngbasta You should know that most of us (especially me in particular) are not big fans of Purism, as I consider it a company that is not trustworthy, an I meet all Purism products with a natural distrust, anyhow explaining why that is is out of the scope of this issue.

Anyway to continue, what PureOS does
remove the contrib repo and has a firefox install with some plugins, is this correct?

**Comment by gjhklfdsa** [comment]
@blacklight447-ptio Plus, it is more user friendly than many of the other distros.
Arch, Debian, OpenBSD, Whonix, e.c.t aren't really made for end users.

I will say that Trisquel is the exception. But, it still lacks in certain areas.
PureOS does add some important features especially with their mobile version on the way.

**Comment by gjhklfdsa** [comment]
> @youngbasta You should know that most of us (especially me in particular) are not big fans of Purism, as I consider it a company that is not trustworthy, an I meet all Purism products with a natural distrust, anyhow explaining why that is is out of the scope of this issue.

This is most likely off topic but, I've been looking into a lot of laptop suppliers.
There really aren't that many.

Name | OS | Coreboot/LibreBoot | Works without Non-free Drivers | RYF Certified
--- | --- | ---
Dell | Ubuntu + Windows | No | Not a Priority | No
System76 | PopOS + Ubuntu | WIP | Not a Priority | No
Technoethical | Trisquel | LibreBoot | Yes | Yes
Minifree | Trisquel | LibreBoot | Yes | Yes
Purism | PureOS | Coeboot Listed Vendor | Yes (not bluetooth) | No
EOMA68 (not launched) ARM | Parabola | LibreBoot | Yes | Yes

**Comment by five-c-d** [comment]
> It's pretty sad how you guys make comments on this privacytools.io git page and so shouldn't you already know what PureOS is? Atleast what Purism is

Yes, pretty sure everybody in this thread has heard of Purism, and from what I know, PureOS is their rebranded OS project that runs on their hardware.  They just launched a rebranded thing called "Librem One" which is a mixture of Jitsi+RiotAndroid+MatrixSelfHosted + encryptedEmail + ActivityPub+Fediverse + "end2end" VPN (sigh... not sure if they still use PIA or something else now), which is trying to broaden their appeal beyond their own hardware-customers.  

But as far as I'm aware, PureOS is used by people that own Librem15 or Librem13 and that is the extent of the userbase.  Is that wrong?  And yes, when it ships, some variant of Debian/PureOS will also be on the Librem 5 smartphone-Linux, and like the LibremOne software-as-a-service will be https://news.ycombinator.com/item?id=15090156 Matrix-based (or maybe OMEMO-based or maybe both), but likely unable to run signalapp and other android-linux-smartphone-apps for that reason, on launch-day most likely anyways. 

tier|debian&ubuntu | otherMajorDistro | privacy&securityDistros 
---|---|---|---
A|	20.720x	mint=3			|32.131x	manjaro=2	|	(nothing in topTen)
B|	13.916x	ubuntu=5		| 9.636x	fedora=7	|	(" " ")
C|	11.991x	**debian**=6		| 5.888x	centos=13		|(" " ")
D|	 3.813x	lubuntu=23		| 5.439x	**arch**=16			| 5.178x	parrot=17
E|	 3.393x	ubuntuKylin=27		| 3.785x	mageia=24		| 4.467x	kali=20
F|	 3.000x	ubuntuMate=32		| 3.636x	**puppy**=25		| 2.991x	**tails**=33
G|	 2.925x	xubuntu=35		| 3.533x	freebsd=26		| 2.972x	<ins>popos</ins>V34
H|	 2.477x	kubuntu=43		| 3.065x	slackware=31		| 2.355x	rhel=45		
I|	 1.636x	ubuntuBudgie=67		| 2.206x	gentoo=50		| 1.523x	**qubes**=76
J|	 1.542x	ubuntuStudio=74		| 1.626x	**knoppix**=68		| 1.383x **tinyCore**=84
K|	 1.430x	emmabuntüs=78	 |1.374x	**openbsd**=86	| 1.271x	**trisquel**=95
L|	 1.NNNx	(lots of others)	 |1.NNNx	(lots of others)	| 1.000x	<ins>pureos</ins>=111

Distrowatch is not a good metric, a better one is wikipedia-pageviews -- but PureOS does not have a dedicated article so that cannot be checked -- or maybe google-trends.  You can also use alexa-rank, pureos DOT net is around global#420k down from global#305k a month back (privacyToolsIO is global#214k and was global#196k recently).  

> especially me in particular) are not big fans of Purism, as I consider it a company that is not trustworthy, an I meet all Purism products with a natural distrust, 

This is where you would link to the rationale and reasoning, for your assertion.  

>  anyhow explaining why that is is out of the scope of this issue

This issue is about whether to add purism to the listings, of course whether they are a "trustworthy" firm matters.  @blacklight447-ptio Please give details and links.

**Comment by danarel** [comment]
> lets now go over this question, what would Pure OS bring to the table, when its compared to other os's we already list.

instability...

**Comment by erciccione** [comment]
> most of us (especially me in particular) are not big fans of Purism, as I consider it a company that is not trustworthy

@blacklight447-ptio Could you expand on why you don't consider them trustworthy?

**Comment by blacklight447-ptio** [comment]
This link sums it up nicely:https://trisquel.info/fr/forum/fsf-has-sold-out-and-endorsed-purism

purism librem computers are not free, and will never be free, as long as they depend on modern x86 laptops. Anything else is a flat out lie. The fact that they charge a premium price for low quality, non free hardware, while claiming they respect your freedom is a major red flag.

**Comment by danarel** [comment]
I discussed this stuff briefly on Mastodon as to why I think Purism is bad for FOSS and Linux.

https://mastodon.technology/@danarel/102219826982389721

**Comment by blacklight447-ptio** [comment]
As it stands, there seems to be no reason to recommend this over debian, so i will be closing this issue, if people have further argumentation on why it SHOULD be added, feel free to comment to open it up again.
